---
title: "deseq"
author: "lital barak"
date: "2022-11-27"
output: html_document
---
```{r}
library(stringr)
library(tibble)
library(dplyr)
library(data.table)
library(tidyr)
library(ggplot2)
library(gplots)
library(ggthemes)
library(ggrepel)
library(pheatmap)
library(gridExtra)
library(patchwork)
library(openxlsx)
library(readxl)
library(RColorBrewer)
library(DESeq2)
library(Rtsne)
library(factoextra)
library(vegan)
library(biomaRt)
library(flowCore) 
library(corrplot)
library(psych)
library(DataExplorer)
library(apeglm)
library(GGally)
library(Rcpp)
library(EnrichmentBrowser)
library(mygene)
library(plotly)
#library(xlsx)
library(stringr)
library(EnhancedVolcano)
library("png")
library("plotly")
library(grid)
```



```{r}

DE_result_dir<-"E:/seq_data"
cts <- (read.csv("E:/seq_data/Salmon_TPM_wCounts.csv",sep=",",row.names="GeneSymbol"))
coldata <- read.csv("E:/seq_data/npfr/only_npfr_metaNooutliers.csv", row.names=1)


data_noTPM <- select(cts, -contains("TPM"))
data<-data.frame(row.names=rownames(cts))


coldata$condition <- factor(coldata$condition)

coldata$repeat.<-factor(coldata$repeat.)

NPF_cell<-data_noTPM %>%
  select(matches("NPFR"))


NPF_cell<-NPF_cell %>%
  select(matches(
rownames(coldata)))


colnames(NPF_cell)<-gsub("_counts","",colnames(NPF_cell))

coldata$condition <- factor(coldata$condition)
coldata$repeat. <- factor(coldata$repeat.)

all(rownames(NPF_cell) %in% colnames(NPF_cell))
all(rownames(coldata) == colnames(NPF_cell))

dds <- DESeqDataSetFromMatrix(countData = round(NPF_cell),
                              colData = coldata,
                              design= ~repeat.+condition)

#dds$cell <- relevel(dds$cell, ref = "Npfr") 
dds$condition <- relevel(dds$condition, ref = "Rejected") 

dds <- DESeq(dds)
# Returns the names of the estimated effects (coefficents) of the model
resultsNames(dds) #"Group_Post_vs_CTRL"
# Get the Pval, Padj and LFC for each gene
res <- results(dds)
# Print a summary of the results from a DESeq analysis
summary(res) # ~19000 genes

dds <- dds[rowMeans(counts(dds))>25, ]
dds <- DESeq(dds)
resultsNames(dds) 

res <- results(dds, name = "condition_Virgin_vs_Rejected")

summary(res) # ~6000 genes


#res_treat <- results(dds, name = "cell_Tdc2_vs_Npfr")
#write.csv(res_treat,  file=paste0(DE_result_dir,"/Genes_info.csv"),
#          row.names = TRUE)

```





```{r}
vsd <- vst(dds, blind=FALSE)
DESeq2::plotPCA(vsd, intgroup="condition") + geom_label(aes(label=name)) + labs(title = "PCA according to group - Before removing batch effect")


DESeq2::plotPCA(vsd, intgroup="repeat.") + geom_label(aes(label=name)) + labs(title = "PCA according to group - Before removing batch effect")

```

### Remove the batch effect:
```{r}
mat <- assay(vsd)
mat <- limma::removeBatchEffect(mat, vsd$repeat.)# remove according to experiment
assay(vsd) <- mat
```

```{r}
DESeq2::plotPCA(vsd, intgroup="condition") + geom_label(aes(label=name)) + labs(title = "PCA according to group - After removing batch effect")


DESeq2::plotPCA(vsd, intgroup="repeat.") + geom_label(aes(label=name)) + labs(title = "PCA according to group - After removing batch effect")

```

```{r}
pheatmap(cor(assay(vsd)), main="Samples Correlation Heatmap")
```
```{r}


res_treat <- results(dds, name = "condition_Virgin_vs_Rejected")
res_df<- as.data.frame(res_treat)
thresh<-0.58
pVal<-0.05
pAdj<-0.1

# Padj = FDR correction - all the genes that Padj <= 0.1
gene_res_padj_sig <- subset(res_df, padj <= pAdj)
print(paste("gene_res_padj_sig:",nrow(gene_res_padj_sig)))

# Pval - all the genes that Pval <= 0.05
gene_res_pval_sig <- subset(res_df, pvalue <= pVal)
print(paste("gene_res_pval_sig:",nrow(gene_res_pval_sig)))

# Padj - all the genes that Padj<=0.1 and LFC>=thresh
gene_res_padj_sig <- subset(gene_res_padj_sig,abs(log2FoldChange) >=thresh)
print(paste("gene_res_padj_sig",thresh,":",nrow(gene_res_padj_sig)))

# Pval - all the genes that Pval<=0.05 and LFC>=thresh
gene_res_pval_sig <- subset(gene_res_pval_sig,abs(log2FoldChange) >=thresh)
print(paste("gene_res_pval_sig",thresh,":",nrow(gene_res_pval_sig)))

write.table(rownames(gene_res_padj_sig), 
              file = paste0(DE_result_dir,"/sig_genes_padj_lfc",".txt"),  
              sep = "\t", row.names = F, col.names = FALSE, quote = FALSE)

write.table(rownames(gene_res_pval_sig), 
              file = paste0(DE_result_dir,"/sig_genes_pval_lfc",".txt"),  
              sep = "\t", row.names = F, col.names = FALSE, quote = FALSE)

openxlsx::write.xlsx (gene_res_padj_sig, paste0(DE_result_dir,"/gene_res_padj_sig_all_data",".xlsx"),
                              rowNames = TRUE, colNames = TRUE) 

openxlsx::write.xlsx (gene_res_pval_sig, paste0(DE_result_dir,"/gene_res_pval_sig_all_data",".xlsx"),
                              rowNames = TRUE, colNames = TRUE) 
```


