---
title: "Untitled"
author: "Lital Barak"
date: "2023-08-02"
output: html_document
---

```{r}
sc_data<-read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/mat_avg_elav_wo_tbh.csv",check.names=FALSE,row.names = 1)
# write.csv(all,"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/mat_avg_elav_wo_tbh.csv")
sc_genes<-read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/sig_elav_gene.csv")

bulk_gene<-read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/yulia_de_genes.csv")


bulk_data<-read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/14.8.23/wo_dh44/yulia_data.csv",row.names = 1)

```




```{r}
avarges<-NULL



main_data<-as.data.frame(bulk_data)
#avarges$Geneid<-main_data$Geneid
avarges$fru<-rowMeans(x=main_data[ , grepl( "fru" , names( main_data ) ) ], na.rm = TRUE)
#avarges$dh44<-rowMeans(x=main_data[ , grepl( "dh44" , names( main_data ) ) ], na.rm = TRUE)
avarges$npf<-rowMeans(x=main_data[ , grepl( "npf" , names( main_data ) ) ], na.rm = TRUE)
avarges$npfr<-rowMeans(x=main_data[ , grepl( "npfr" , names( main_data ) ) ], na.rm = TRUE)
avarges$tdc2<-rowMeans(x=main_data[ , grepl( "tdc2" , names( main_data ) ) ], na.rm = TRUE)
avarges$crz<-rowMeans(x=main_data[ , grepl( "crz" , names( main_data ) ) ], na.rm = TRUE)
avarges$th<-rowMeans(x=main_data[ , grepl( "th" , names( main_data ) ) ], na.rm = TRUE)
#avarges$trh<-rowMeans(x=main_data[ , grepl( "trh" , names( main_data ) ) ], na.rm = TRUE)
avarges$ok107<-rowMeans(x=main_data[ , grepl( "ok107" , names( main_data ) ) ], na.rm = TRUE)

avarges$elav<-rowMeans(x=main_data[ , grepl( "elav" , names( main_data ) ) ], na.rm = TRUE)


avarges<-as.data.frame(avarges)

rownames(avarges)<-rownames(main_data)
```

```{r}
genes_bulk <- c((bulk_gene$gene))


bulk<-avarges[genes_bulk, ]


  genes_sc <- c((sc_genes$X))


sc<-sc_data[genes_sc, ]
sc<-na.omit(sc)


```

```{r}

scale_rows = function(x){
    m = apply(x, 1, mean, na.rm = T)
    s = apply(x, 1, sd, na.rm = T)
    return((x - m) / s)
}

scale_mat = function(mat, scale){
    if(!(scale %in% c("none", "row", "column"))){
        stop("scale argument shoud take values: 'none', 'row' or 'column'")
    }
    mat = switch(scale, none = mat, row = scale_rows(mat), column = t(scale_rows(t(mat))))
    return(mat)
}


normlized_bulk<-scale_mat(bulk,"row")
normlized_sc<-scale_mat(sc,"row")

# 
# enriched_bulk<-normlized_bulk[abs(normlized_bulk$npfr) > 1,]
# 
# enriched_sc<-normlized_sc[abs(normlized_sc$NPFR) > 1,]


bulk_main_genes<-c("fru" ,"th" ,"Crz"   , "npfr" ,"tdc2", "npf"   ,  "ok107"   )

#this is to get the genes that are high in the clustring (going up)
current_gene<-"fru"

enriched_bulk<-normlized_bulk[abs(normlized_bulk$fru) > 1.5,]

enriched_sc<-normlized_sc[abs(normlized_sc$fru) > 1.5,]

write.csv(enriched_bulk,paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/bulk_abs_",current_gene,".csv"))
write.csv(enriched_sc,paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/sc_abs_",current_gene,".csv"))



```

```{r}


# 
# gene_bulk<-bulk_gene$X
# gene_sc<-sc_genes$X
# 
# Overlap <- calculate.overlap(x = list(gene_bulk,gene_sc))
# plot(Overlap)
```
```{r}


current_gene<-"th"

    enriched_bulk<-normlized_bulk[(normlized_bulk$th) < (-1.5),]

    #enriched_sc<-normlized_sc[(normlized_sc$ple) < (-1.5),]

write.csv(enriched_bulk,paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/bulk_down_",current_gene,".csv"))
#write.csv(enriched_sc,paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/sc_down_",current_gene,".csv"))



all<-bulk_data
# write.csv(all,"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/mat_avg_elav_wo_tbh.csv")
sig_genes<-rownames(enriched_bulk)

all<-as.matrix(all) 
# write.csv(avarges,"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/yulia_gene_sc_data.csv")

#this is the genes from yulia

tmp_gene<-c((sig_genes))
mat<-all[row.names(all) %in% tmp_gene, ]
#test_scale<-scale(mat)
mat<-as.data.frame(mat)
mat<-mat[apply(mat, 1, function(x) !all(x==0)),]

#test_scale<-mat+0.001


  plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/14.8.23/wo_dh44/",current_gene,"_down_bulk.tiff")
 tiff(file=plotname,units="in",height=11,width=11,res=600)

pheatmap(mat, scale = "row", cluster_cols = T,cluster_rows  = T,show_rownames = T,fontsize_row = 3, fontsize_col = 8,color=colorRampPalette(c("navy", "white", "red"))(50))

dev.off()



all<-sc_data
# write.csv(all,"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/mat_avg_elav_wo_tbh.csv")
sig_genes<-rownames(enriched_sc)

all<-as.matrix(all) 
# write.csv(avarges,"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/yulia_gene_sc_data.csv")


tmp_gene<-c((sig_genes))
mat<-all[row.names(all) %in% tmp_gene, ]
#test_scale<-scale(mat)
mat<-as.data.frame(mat)
mat<-mat[apply(mat, 1, function(x) !all(x==0)),]

#test_scale<-mat+0.001

  plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/14.8.23/wo_dh44/",current_gene,"_down_sc.tiff")
 tiff(file=plotname,units="in",height=11,width=11,res=600)

pheatmap(mat, scale = "row", cluster_cols = T,cluster_rows  = T,show_rownames = T,fontsize_row = 8, fontsize_col = 8,color=colorRampPalette(c("navy", "white", "red"))(50))

dev.off()

```

```{r}
all<-sc_data
# write.csv(all,"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/mat_avg_elav_wo_tbh.csv")
sig_genes<-rownames(enriched_sc)

all<-as.matrix(all) 
# write.csv(avarges,"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/yulia_gene_sc_data.csv")


tmp_gene<-c((sig_genes))
mat<-all[row.names(all) %in% tmp_gene, ]
#test_scale<-scale(mat)
mat<-as.data.frame(mat)
mat<-mat[apply(mat, 1, function(x) !all(x==0)),]

#test_scale<-mat+0.001

  plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/14.8.23/npfr_up_sc.tiff")
 tiff(file=plotname,units="in",height=11,width=11,res=600)

pheatmap(mat, scale = "row", cluster_cols = T,cluster_rows  = T,show_rownames = T,fontsize_row = 8, fontsize_col = 8,color=colorRampPalette(c("navy", "white", "red"))(50))

dev.off()
```




```{r}
sc_splited_genes<-split(sc_genes, sc_genes$from_where)
bulk_splited_genes<-split(bulk_gene, bulk_gene$list_of_name.i.)


outersect <- function(x, y) {
  sort(c(setdiff(x, y),
         setdiff(y, x)))
}

unique(sc_genes$from_where)
unique(bulk_gene$list_of_name.i.)

sc_main_genes<-c(" fru"  , " ple"  , " Crz"  , " NPFR" , " Tdc2" , " NPF"  , " OK107")
bulk_main_genes<-c("fru" ,"th" ,"Crz"   , "npfr" ,"tdc2", "npf"   ,  "ok107"   )


mybiglist <- list()
for(i in 1:length(sc_main_genes)){
  sc_current_gene<-sc_splited_genes[[sc_main_genes[i]]]$X
  bulk_current_gene<-bulk_splited_genes[[bulk_main_genes[i]]]$X
setdiff(sc_current_gene, bulk_current_gene)

    
  #tmp <- list(genes=intersect(sc_current_gene, bulk_current_gene), from_where =bulk_main_genes[i])
  tmp <- list(genes=outersect(sc_current_gene, bulk_current_gene), from_where =bulk_main_genes[i])

  mybiglist[[bulk_main_genes[i]]] <- tmp
  
    current_gene<-names(mybiglist[i])
write.csv(mybiglist[[i]]$genes,paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/27.8.23/up_down_regulated_van_diagram/differ_",current_gene,".csv"))
}


```

```{r}

bulk_main_genes<-c("fru" ,"th" ,"Crz"   , "npfr" ,"tdc2", "npf"   ,  "ok107"   )

mybiglist[[bulk_main_genes[3]]][["genes"]]


current_gene<-bulk_main_genes[7]

all<-bulk_data
# write.csv(all,"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/mat_avg_elav_wo_tbh.csv")
sig_genes<-c(mybiglist[[bulk_main_genes[7]]][["genes"]])

all<-as.matrix(all) 
# write.csv(avarges,"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/yulia_gene_sc_data.csv")

#this is the genes from yulia

tmp_gene<-c((sig_genes))
mat<-all[row.names(all) %in% tmp_gene, ]
#test_scale<-scale(mat)
mat<-as.data.frame(mat)
mat<-mat[apply(mat, 1, function(x) !all(x==0)),]
s
#test_scale<-mat+0.001


  plotname<-paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/27.8.23/",current_gene,"_bulk.tiff")
 tiff(file=plotname,units="in",height=11,width=11,res=600)

pheatmap(mat, scale = "row", cluster_cols = T,cluster_rows  = T,show_rownames = T,fontsize_row = 8, fontsize_col = 8,color=colorRampPalette(c("navy", "white", "red"))(50))

dev.off()

```
```{r}

current_gene<-bulk_main_genes[7]

all<-sc_data
# write.csv(all,"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/mat_avg_elav_wo_tbh.csv")
sig_genes<-c(mybiglist[[bulk_main_genes[7]]][["genes"]])

all<-as.matrix(all) 
# write.csv(avarges,"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/yulia_gene_sc_data.csv")


tmp_gene<-c((sig_genes))
mat<-all[row.names(all) %in% tmp_gene, ]
#test_scale<-scale(mat)
mat<-as.data.frame(mat)
mat<-mat[apply(mat, 1, function(x) !all(x==0)),]

#test_scale<-mat+0.001

  plotname<-paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/27.8.23/",current_gene,"_sc.tiff") 
  tiff(file=plotname,units="in",height=11,width=11,res=600)

pheatmap(mat, scale = "row", cluster_cols = T,cluster_rows  = T,show_rownames = T,fontsize_row = 8, fontsize_col = 8,color=colorRampPalette(c("navy", "white", "red"))(50))

dev.off()
```



```{r}

all<-bulk_data
# write.csv(all,"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/mat_avg_elav_wo_tbh.csv")
sig_genes<-c(sc_genes$X)

all<-as.matrix(all) 
# write.csv(avarges,"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/yulia_gene_sc_data.csv")


tmp_gene<-c((sig_genes))
mat<-all[row.names(all) %in% tmp_gene, ]
#test_scale<-scale(mat)
mat<-as.data.frame(mat)
mat<-mat[apply(mat, 1, function(x) !all(x==0)),]

#test_scale<-mat+0.001
  plotname<-paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/27.8.23/bulkdata_sc_degenes_sc.tiff") 
  tiff(file=plotname,units="in",height=11,width=11,res=600)

pheatmap(mat, scale = "row", cluster_cols = T,cluster_rows  = T,show_rownames = T,fontsize_row = 2, fontsize_col = 8,color=colorRampPalette(c("navy", "white", "red"))(50))

dev.off()
```





```{r}
sc_genes<-read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/sig_elav_gene.csv")

bulk_gene<-read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/yulia_de_genes.csv")

sc_splited<-split(sc_genes, sc_genes$from_where)


bulk_splited<-split(bulk_gene, bulk_gene$list_of_name.i.)

for(i in 1:length(sc_splited)){
  current_gene<-names(sc_splited[i])
write.csv(sc_splited[[i]],paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/27.8.23/up_down_regulated_van_diagram/sc_",current_gene,".csv"))
}

for(i in 1:length(bulk_splited)){
  current_gene<-names(bulk_splited[i])
write.csv(bulk_splited[[i]],paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/27.8.23/up_down_regulated_van_diagram/bulk_",current_gene,".csv"))
}


```




```{r}


sc_genes<-read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/sig_elav_gene.csv")

bulk_gene<-read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/yulia_de_genes.csv")

sc_splited<-split(sc_genes, sc_genes$from_where)


bulk_splited<-split(bulk_gene, bulk_gene$list_of_name.i.)





sub_Seted<-readRDS("D:/seq_data/FCA/17_7_reclustered_head_elav_genes.rds")
Idents(object = sub_Seted) <- sub_Seted@meta.data$names

 t<-SplitObject(sub_Seted, split.by = "names")
NPF_CELLS<-t[[" NPF"]]
NPFR_CELLS<-t[[" NPFR"]]

CountMyGeneMyCell<-GetAssayData(object = NPFR_CELLS, slot = "data")
CountMyGeneMyCell<-as.data.frame(CountMyGeneMyCell)
CountMyGeneMyCell<-as.matrix(CountMyGeneMyCell)

mat<-CountMyGeneMyCell
mat<-mat[apply(mat, 1, function(x) !all(x==0)),]





mat<-mat[row.names(mat) %in% sc_splited[[" NPFR"]]$X, ]



  plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/27.8.23/de_genes_of_npfr_sc.tiff")
 tiff(file=plotname,units="in",height=11,width=11,res=600)

pheatmap(mat,scale = "row",cluster_rows  = T,cluster_cols = TRUE,show_rownames = F,show_colnames  = F,fontsize_row = 5, fontsize_col = 20,color=colorRampPalette(c("navy", "white", "red"))(50))

dev.off()
```

```{r}
WHAT_TYPE<-"NPFR"
number<-30
# 
# sc_data<-read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/mat_avg_elav_wo_tbh.csv",check.names=FALSE,row.names = 1)
# 
# 
# sub_Seted<-readRDS("D:/seq_data/FCA/17_7_reclustered_head_elav_genes.rds")
# Idents(object = sub_Seted) <- sub_Seted@meta.data$names
# 
#  t<-SplitObject(sub_Seted, split.by = "names")
# NPF_CELLS<-t[[" NPF"]]
# NPFR_CELLS<-t[[" NPFR"]]

if(WHAT_TYPE == "NPF"){
  CountMyGeneMyCell<-GetAssayData(object = NPF_CELLS, slot = "data")
CountMyGeneMyCell<-as.data.frame(CountMyGeneMyCell)
CountMyGeneMyCell<-as.matrix(CountMyGeneMyCell)

mat<-CountMyGeneMyCell


mat<-as.data.frame(mat)


names_of_npfr<-paste0("NPF_rep",1:ncol(mat))
colnames(mat)<-(names_of_npfr)

elav<-sc_data["elav"]

mat<-cbind(mat,sc_data["elav"])

mat<-mat[apply(mat, 1, function(x) !all(x==0)),]


new_mat<-mat/mat[,ncol(mat)]

#lfc<-log2(new_mat)
lfc<-(new_mat)

lfc[lfc == -Inf] <- 0


colnames(lfc)<-rep("REP", ncol(mat))


temp<-1:150
the_genes<- NULL

the_genes<-cbind(the_genes,temp)

for(i in 1:ncol(lfc)){
   if(i==ncol(mat)){
   break
   }else{
     tmp_current_rep<-lfc[i]
 log_fold_change_3<-subset(tmp_current_rep, abs(REP) > number)
 tmp_names<-rownames(log_fold_change_3)
 the_genes<-bind_cols(the_genes,tmp_names)
 #the_genes[[i]]<-(rownames(log_fold_change_3))

 }

}

testy<-as.matrix(the_genes)

out <- do.call(cbind, lapply(my.list, function(x) x[1:n, , drop = FALSE]))
rownames(out) <- NULL
out

tmp_genes<-unique(the_genes)
tmp_genes<-as.data.frame(tmp_genes)


CountMyGeneMyCell<-GetAssayData(object = NPF_CELLS, slot = "data")
CountMyGeneMyCell<-as.data.frame(CountMyGeneMyCell)
CountMyGeneMyCell<-as.matrix(CountMyGeneMyCell)

mat<-CountMyGeneMyCell
mat<-as.data.frame(mat)

mat<-mat[row.names(mat) %in% tmp_genes$tmp_genes, ]

  plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/3.9.23/",number,"_npf_all_40_cells_gene_clusters_DE_GENES_TOELAV_PER_CELL.jpeg")
 jpeg(file=plotname,units="in",height=11,width=11,res=600)

pheatmap(mat,scale = "row",cluster_rows  = T,cluster_cols = TRUE,show_rownames = F,show_colnames  = F,fontsize_row = 5, fontsize_col = 20,color=colorRampPalette(c("navy", "white", "red"))(50))

dev.off()
}


if(WHAT_TYPE == "NPFR"){
  CountMyGeneMyCell<-GetAssayData(object = NPFR_CELLS, slot = "data")
CountMyGeneMyCell<-as.data.frame(CountMyGeneMyCell)
CountMyGeneMyCell<-as.matrix(CountMyGeneMyCell)

mat<-CountMyGeneMyCell


mat<-as.data.frame(mat)


names_of_npfr<-paste0("NPF_rep",1:ncol(mat))
colnames(mat)<-(names_of_npfr)

elav<-sc_data["elav"]

mat<-cbind(mat,sc_data["elav"])

mat<-mat[apply(mat, 1, function(x) !all(x==0)),]


new_mat<-mat/mat[,ncol(mat)]

#lfc<-log2(new_mat)
lfc<-(new_mat)

lfc[lfc == -Inf] <- 0


colnames(lfc)<-rep("REP", ncol(mat))

the_genes<-NULL

for(i in 1:ncol(lfc)){
   if(i==ncol(mat)){
   break
   }else{
     tmp_current_rep<-lfc[i]
 log_fold_change_3<-subset(tmp_current_rep, abs(REP) > number )
 the_genes<-c(the_genes,rownames(log_fold_change_3))

 }

}

tmp_genes<-unique(the_genes)
tmp_genes<-as.data.frame(tmp_genes)


CountMyGeneMyCell<-GetAssayData(object = NPFR_CELLS, slot = "data")
CountMyGeneMyCell<-as.data.frame(CountMyGeneMyCell)
CountMyGeneMyCell<-as.matrix(CountMyGeneMyCell)

mat<-CountMyGeneMyCell
mat<-as.data.frame(mat)

mat<-mat[row.names(mat) %in% tmp_genes$tmp_genes, ]

  plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/3.9.23/",number,"_npfr_all_100_cells_gene_clusters_DE_GENES_TOELAV_PER_CELL.jpeg")
 jpeg(file=plotname,units="in",height=11,width=11,res=600)

pheatmap(mat,scale = "row",cluster_rows  = T,cluster_cols = TRUE,show_rownames = F,show_colnames  = F,fontsize_row = 5, fontsize_col = 20,color=colorRampPalette(c("navy", "white", "red"))(50))

dev.off()
}
```


```{r}

```



```{r}
library(htmltools)
library(DESeq2)
library(ggplot2)
library(autoplotly)
library(factoextra)
library("pheatmap")
library("RColorBrewer")
#library(limma)
library("manhattanly")
library("ggrepel")
library(plotly)
library("heatmaply")
library(dplyr)
library("DESeq2")



cts <- mat
coldata <- read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/3.9.23/meta_data_elav_npf.csv", row.names=1)
coldata_not_factorial <-  read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/3.9.23/meta_data_elav_npf.csv")
data_noTPM <- (cts)
#data<-data.frame(row.names=rownames(cts))
data<-cts

num_of_exp =49
for (i in 1:num_of_exp){
  temp.df<-data.frame()
  temp.df<-data_noTPM %>%
    select(starts_with(coldata_not_factorial[i,1]))


  data[coldata_not_factorial[i,1]]<- (temp.df)
}

coldata$type <- factor(coldata$type)
#coldata$cell <- factor(coldata$cell)

all(rownames(coldata) %in% colnames(data))
all(rownames(coldata) == colnames(data))
data <- data[, rownames(coldata)]
all(rownames(coldata) == colnames(data))
coldata$type <- factor(coldata$type)


dds <- DESeqDataSetFromMatrix(countData = round(data),
                              colData = coldata,
                              design = ~ type)
dds
dds$type<-relevel(dds$type,ref = "elav")

dds <- DESeq(dds)
#dds$condition<-relevel(dds$condition,ref = "Mated")


resultsNames(dds)

res <- results(dds,name ="type_NPF_vs_elav")

tmp_all<-subset(res, padj<0.05 & abs(log2FoldChange)>=1)
tmp_all<-as.data.frame(tmp_all)


write.csv(tmp_all,"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/3.9.23/npf_de_genes.csv")

```

