```{r}

library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
loom_file <- connect(filename = "D:/seq_data/FCA/s_fca_biohub_male_reproductive_glands_10x.loom", mode = "r+", skip.validate=TRUE)
matrix_data <- as.data.frame(loom_file[["matrix"]][,])
  rownames(matrix_data) <- loom_file[["col_attrs/CellID"]][]
  colnames(matrix_data) <- loom_file[["row_attrs/Gene"]][]
  SERUAT_Antena <- CreateSeuratObject(counts = t(matrix_data), project = "antena", min.cells = 0, min.features=0)
 # saveRDS(SERUAT_antena_N, "/home/alu/aluguest/Lital_galitLab/seuruat_antena_non_normelize.rds")
  
  
SERUAT_Antena <- NormalizeData(object = SERUAT_Antena)
SERUAT_Antena <- FindVariableFeatures(object = SERUAT_Antena)
SERUAT_Antena <- ScaleData(object = SERUAT_Antena)
SERUAT_Antena <- RunPCA(object = SERUAT_Antena)
ElbowPlot(SERUAT_Antena)
SERUAT_Antena <- FindNeighbors(object = SERUAT_Antena, dims = 1:20)
SERUAT_Antena <- FindClusters(object = SERUAT_Antena)
SERUAT_Antena <- RunUMAP(object = SERUAT_Antena, dims = 1:20)

saveRDS(SERUAT_Antena, "D:/seq_data/FCA/seuruat_male_reproductive_glands_13_9.rds")
```



```{r}
library(tidyr)
library(dplyr)
library(stringr)
SERUAT_HEAD<- readRDS("D:/seq_data/FCA/seuruat_male_reproductive_glands_13_9.rds")

SERUAT_HEAD$sample <- rownames(SERUAT_HEAD@meta.data)

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "__", "_")

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "-", "_")

View(SERUAT_HEAD@meta.data)
SERUAT_HEAD@meta.data <- separate(SERUAT_HEAD@meta.data, col = 'sample', into = c("test",'Barcode','identity', 'Sex'),
                                  sep = '_')

SERUAT_HEAD@meta.data$obp69a<- FetchData(SERUAT_HEAD, vars = "Obp69a")

SERUAT_HEAD@meta.data$lush<- FetchData(SERUAT_HEAD, vars = "lush")
SERUAT_HEAD@meta.data$obp28a<- FetchData(SERUAT_HEAD, vars = "Obp28a")

   plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/male_reproductive_glands_sex.tiff")
  
 tiff(file=plotname,units="in",height=11,width=11,res=600)

DimPlot(SERUAT_HEAD, reduction = 'umap', group.by = 'Sex',raster=FALSE)+guides(color = guide_legend(override.aes = list(size=1), ncol=2) )+theme(legend.title = element_text(size = 5), 
               legend.text = element_text(size = 7))

dev.off()




plotname<-"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/male_reproductive_glands_Obp28a_wo_threshold_Sex.tiff"

tiff(file=plotname,units="in",height=13,width=18,res=600)

#FeaturePlot(SERUAT_HEAD,features ="Obp28a",split.by = "Sex")

FeaturePlot(SERUAT_HEAD,features ="Obp28a")

dev.off()


plotname<-"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/male_reproductive_glands_Obp69a_wo_threshold_Sex.tiff"

tiff(file=plotname,units="in",height=13,width=18,res=600)

#FeaturePlot(SERUAT_HEAD,features ="Obp69a",split.by = "Sex")

FeaturePlot(SERUAT_HEAD,features ="Obp69a")
dev.off()



plotname<-"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/male_reproductive_glands_lush_wo_threshold_Sex.tiff"

tiff(file=plotname,units="in",height=13,width=18,res=600)

#FeaturePlot(SERUAT_HEAD,features ="lush",split.by = "Sex")
FeaturePlot(SERUAT_HEAD,features ="lush")

dev.off()

```

```{r}

    all_genes<-as.data.frame(rownames(SERUAT_HEAD))
```

