---
title: "Untitled"
author: "lital barak"
date: "2023-05-28"
output: html_document
---

```{r}
sub_Seted <-readRDS("D:/seq_data/FCA/seuruat_head30_5_elav.rds")

library(Seurat)

genes_splited<-SplitObject(sub_Seted,split.by = "names" )

fru<-genes_splited[[1]]
Tbh<-genes_splited[[2]]
ple<-genes_splited[[3]]
Crz<-genes_splited[[4]]
NPFR<-genes_splited[[5]]
Tdc2<-genes_splited[[6]]
NPF<-genes_splited[[7]]


Idents(object = fru) <- fru@meta.data$identity

Idents(object = Tbh) <- Tbh@meta.data$identity
Idents(object = ple) <- ple@meta.data$identity
Idents(object = Crz) <- Crz@meta.data$identity
Idents(object = NPFR) <- NPFR@meta.data$identity
Idents(object = Tdc2) <- Tdc2@meta.data$identity
Idents(object = NPF) <- NPF@meta.data$identity


avg_fru<-as.data.frame(AverageExpression(object = fru,slot = 'counts' ))

avg_Tbh<-as.data.frame(AverageExpression(object = Tbh,slot = 'counts' ))
avg_ple<-as.data.frame(AverageExpression(object = ple,slot = 'counts' ))
avg_Crz<-as.data.frame(AverageExpression(object = Crz,slot = 'counts' ))
avg_NPFR<-as.data.frame(AverageExpression(object = NPFR,slot = 'counts' ))
avg_Tdc2<-as.data.frame(AverageExpression(object = Tdc2,slot = 'counts' ))
avg_NPF<-as.data.frame(AverageExpression(object = NPF,slot = 'counts' ))


colnames(avg_fru) = gsub("RNA.FCA", "fru_rep", colnames(avg_fru))
colnames(avg_Tbh) = gsub("RNA.FCA", "Tbh_rep", colnames(avg_Tbh))
colnames(avg_ple) = gsub("RNA.FCA", "ple_rep", colnames(avg_ple))
colnames(avg_Crz) = gsub("RNA.FCA", "Crz_rep", colnames(avg_Crz))
colnames(avg_NPFR) = gsub("RNA.FCA", "NPFR_rep", colnames(avg_NPFR))
colnames(avg_Tdc2) = gsub("RNA.FCA", "Tdc2_rep", colnames(avg_Tdc2))
colnames(avg_NPF) = gsub("RNA.FCA", "NPF._rep", colnames(avg_NPF))


```

```{r}
avg_fru<-readRDS("D:/seq_data/FCA/avg_exp_fru.rds")

avg_Tbh<-readRDS("D:/seq_data/FCA/avg_exp_tbh.rds")
avg_ple<-readRDS("D:/seq_data/FCA/avg_exp_ple.rds")
avg_Crz<-readRDS("D:/seq_data/FCA/avg_exp_Crz.rds")
avg_NPFR<-readRDS("D:/seq_data/FCA/avg_exp_NPFR.rds")
avg_Tdc2<-readRDS("D:/seq_data/FCA/avg_exp_tdc2.rds")
avg_NPF<-readRDS("D:/seq_data/FCA/avg_exp_NPF.rds") 
elav<-readRDS("D:/seq_data/FCA/avg_exp_elav.rds")

colnames(avg_fru) = gsub("RNA.FCA", "fru_rep", colnames(avg_fru))
colnames(avg_Tbh) = gsub("RNA.FCA", "Tbh_rep", colnames(avg_Tbh))
colnames(avg_ple) = gsub("RNA.FCA", "ple_rep", colnames(avg_ple))
colnames(avg_Crz) = gsub("RNA.FCA", "Crz_rep", colnames(avg_Crz))
colnames(avg_NPFR) = gsub("RNA.FCA", "NPFR_rep", colnames(avg_NPFR))
colnames(avg_Tdc2) = gsub("RNA.FCA", "Tdc2_rep", colnames(avg_Tdc2))
colnames(avg_NPF) = gsub("RNA.FCA", "NPF._rep", colnames(avg_NPF))
colnames(elav) = gsub("RNA.FCA", "elav_rep", colnames(elav))


```




```{r}
meta_data<-NULL

meta_data<-colnames(avg_fru)
meta_data<-as.data.frame(meta_data)
colnames(meta_data)<-"sample"

meta_data$type<-"fru"


temp_<-NULL

temp_<-colnames(avg_NPF)
temp_<-as.data.frame(temp_)
colnames(temp_)<-"sample"
temp_$type<-"NPF."



meta_data<-rbind(meta_data,temp_)




 write.csv(meta_data, "C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/28.5.23/meta_data_elav.csv", row.names=FALSE)

```



```{r}
# write.csv(avg_fru, "C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/28.5.23/fru_avg_sc.csv", row.names=TRUE)
# write.csv(avg_Tbh, "C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/28.5.23/Tbh_avg_sc.csv", row.names=TRUE)
# write.csv(avg_ple, "C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/28.5.23/ple_avg_sc.csv", row.names=TRUE)
# write.csv(avg_Crz, "C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/28.5.23/Crz_avg_sc.csv", row.names=TRUE)
# write.csv(avg_NPFR, "C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/28.5.23/NPFR_avg_sc.csv", row.names=TRUE)
# write.csv(avg_Tdc2, "C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/28.5.23/Tdc2_avg_sc.csv", row.names=TRUE)
# write.csv(avg_NPF, "C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/28.5.23/NPF_avg_sc.csv", row.names=TRUE)
# write.csv(elav, "C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/28.5.23/elav_avg_sc.csv", row.names=TRUE)

library("readxl")

all_genes<-read_excel("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/28.5.23/all_gene_Avg_Elav.xlsx",)

rowname_allgenes<-all_genes$...1


all_genes<-all_genes[,-1]

all_genes<-as.data.frame(all_genes)
row.names(all_genes)<-rowname_allgenes

# 
# write.csv(all_genes, "C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/28.5.23/NPF_avg_sc.csv", row.names=TRUE)
```




```{r}
library(htmltools)
library(DESeq2)
library(ggplot2)
library(autoplotly)
library(factoextra)
library("pheatmap")
library("RColorBrewer")
#library(limma)
library("manhattanly")
library("ggrepel")
library(plotly)
library("heatmaply")
library(dplyr)
library("DESeq2")
```



```{r}
cts <- all_genes
coldata <- read.csv("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/28.5.23/meta_data_elav.csv", row.names=1)
coldata_not_factorial <-  read.csv("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/28.5.23/meta_data_elav.csv")
data_noTPM <- (cts)
data<-data.frame(row.names=rownames(cts))
```



```{r}
num_of_exp =104
for (i in 1:num_of_exp){
  temp.df<-data.frame()
  temp.df<-data_noTPM %>%
    select(starts_with(coldata_not_factorial[i,1]))
  
  
  data[coldata_not_factorial[i,1]]<- rowMeans(temp.df)
}

coldata$type <- factor(coldata$type)
#coldata$cell <- factor(coldata$cell)

all(rownames(coldata) %in% colnames(data))
all(rownames(coldata) == colnames(data))
data <- data[, rownames(coldata)]
all(rownames(coldata) == colnames(data))
coldata$type <- factor(coldata$type)

```


```{r}
dds <- DESeqDataSetFromMatrix(countData = round(data),
                              colData = coldata,
                              design = ~ type)
dds
dds$type<-relevel(dds$type,ref = "elav")

dds <- DESeq(dds)
#dds$condition<-relevel(dds$condition,ref = "Mated")


resultsNames(dds)



#res <- results(dds)


table_counts_normalized <- counts(dds, normalized=TRUE)


#keep <- ((counts(dds,normalized=TRUE)) >= 30)


#and a minimum of least of 30 normalized counts in
#one of the repeats


#keep <-  rowSums( counts(dds, normalized=TRUE) >= 30 ) >= 1  
keep <- rowSums(counts(dds,normalized=TRUE)) >= 0
dds <- dds[keep,]

dds <- DESeq(dds)

res <- results(dds)

all<-subset(res, pvalue<0.05 & abs(log2FoldChange)>=1)
all<-as.data.frame(all)

```




```{r}
fru_elav_tmp<-results(dds,name = "type_fru_vs_elav")
elav_fru_res_tmp<-subset(fru_elav_tmp, pvalue<0.05 & abs(log2FoldChange)>=1)
elav_fru_res_tmp<-as.data.frame(elav_fru_res_tmp)
```

```{r}
elav_fru <- lfcShrink(dds, coef="type_fru_vs_elav")

elav_fru_res<-subset(elav_fru, pvalue<0.05 & abs(log2FoldChange)>=1)
elav_fru_res<-as.data.frame(elav_fru_res)
```

