---
title: "Untitled"
output: html_document
date: '2022-08-21'
---

```{r}
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_github("mojaveazure/seurat-disk")
```

#HEAD relaxed


```{r}
library(Seurat)
library(SeuratDisk)
path_to_fca<-"D:/seq_data/FCA/r_fca_biohub_head_10x.h5ad"

#l6.immune <- Connect(filename = "C:/Users/barakli8/Downloads/s_fca_biohub_head_10x.loom", mode = "r")
#l6.immune
#l6.seurat <- as.Seurat(l6.immune)
#Idents(l6.seurat) <- "ClusterName"
#VlnPlot(l6.seurat, features = c("Sparc", "Ftl1", "Junb", "Ccl4"), ncol = 2)

Convert(path_to_fca,dest = "h5seurat",overwrite = TRUE)
seurat_anndata<-LoadH5Seurat("D:/seq_data/FCA/r_fca_biohub_head_10x.h5seurat")

pbmc <- seurat_anndata


```



```{r}
l6.immune <- Connect(filename = "D:/seq_data/FCA/r_fca_biohub_head_10x.loom", mode = "r")
l6.immune

gene_names <-  l6.immune[["row_attrs/Gene"]][]

gene_of_interest <- "NPFR"

gene_of_interest %in% gene_names
l6.seurat <- as.Seurat(l6.immune)
```

#head s

```{r}
library(Seurat)
library(SeuratDisk)
path_to_fca<-"D:/seq_data/FCA/s_fca_biohub_head_10x.h5ad"

#l6.immune <- Connect(filename = "C:/Users/barakli8/Downloads/s_fca_biohub_head_10x.loom", mode = "r")
#l6.immune
#l6.seurat <- as.Seurat(l6.immune)
#Idents(l6.seurat) <- "ClusterName"
#VlnPlot(l6.seurat, features = c("Sparc", "Ftl1", "Junb", "Ccl4"), ncol = 2)

Convert(path_to_fca,dest = "h5seurat",overwrite = TRUE)
seurat_anndata<-LoadH5Seurat("D:/seq_data/FCA/s_fca_biohub_head_10x.h5seurat")

pbmc <- seurat_anndata


```

```{r}


which(grepl("NPF",rownames(x = pbmc)))
rownames(x = pbmc)[1078]

test<-rownames(x = pbmc)
test<-as.data.frame(test)
which(rownames(x = pbmc) == "NPF")


pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(pbmc), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(pbmc)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2


all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)

pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
# Examine and visualize PCA results a few different ways
print(pbmc[["pca"]], dims = 1:5, nfeatures = 5)


VizDimLoadings(pbmc, dims = 1:2, reduction = "pca")


DimPlot(pbmc, reduction = "pca")

DimHeatmap(pbmc, dims = 1, cells = 500, balanced = TRUE)

DimHeatmap(pbmc, dims = 1:20, cells = 500, balanced = TRUE)


# NOTE: This process can take a long time for big datasets, comment out for expediency. More
# approximate techniques such as those implemented in ElbowPlot() can be used to reduce
# computation time
#pbmc <- JackStraw(pbmc, num.replicate = 100)
#pbmc <- ScoreJackStraw(pbmc, dims = 1:20)
#JackStrawPlot(pbmc, dims = 1:15)

ElbowPlot(pbmc)

pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5)
# Look at cluster IDs of the first 5 cells
head(Idents(pbmc), 5)
# If you haven't installed UMAP, you can do so via reticulate::py_install(packages =
# 'umap-learn')
pbmc <- RunUMAP(pbmc, dims = 1:10)
# note that you can set `label = TRUE` or use the LabelClusters function to help label
# individual clusters
DimPlot(pbmc, reduction = "umap")

cluster2.markers <- FindMarkers(pbmc, ident.1 = 2, min.pct = 0.25)
head(cluster2.markers, n = 5)


pbmc.markers <- FindAllMarkers(pbmc, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
pbmc.markers %>%
    group_by(cluster) %>%
    slice_max(n = 2, order_by = avg_log2FC)



cluster0.markers <- FindMarkers(pbmc, ident.1 = 0, logfc.threshold = 0.25, test.use = "roc", only.pos = TRUE)

VlnPlot(pbmc, features = c("NPFR"))

```

#anetna
```{r}
library(Seurat)
library(SeuratDisk)
path_to_fca<-"C:/Users/barakli8/Downloads/s_fca_biohub_antenna_10x.h5ad"

#l6.immune <- Connect(filename = "C:/Users/barakli8/Downloads/s_fca_biohub_head_10x.loom", mode = "r")
#l6.immune
#l6.seurat <- as.Seurat(l6.immune)
#Idents(l6.seurat) <- "ClusterName"
#VlnPlot(l6.seurat, features = c("Sparc", "Ftl1", "Junb", "Ccl4"), ncol = 2)

Convert(path_to_fca,dest = "h5seurat",overwrite = TRUE)
seurat_anndata<-LoadH5Seurat("C:/Users/barakli8/Downloads/s_fca_biohub_antenna_10x.h5seurat")

pbmc <- seurat_anndata

test<-rownames(x = pbmc)


```


```{r}
library(Seurat)
library(SeuratDisk)
library(tidyverse)
```

