---
title: "Untitled"
output: html_document
date: "2023-05-24"
---


```{r}
SERUAT_HEAD  <-readRDS("D:/seq_data/FCA/seuruat_head5_12.rds")

#mat_avg_per_gene<-as.matrix(avg_per_gene)
#Idents(object = sub_Seted) <- sub_Seted@meta.data$names

#head(AverageExpression(object = sub_Seted))
library("pheatmap")



above_70<-avg_per_gene[rowSums(avg_per_gene[,c(1,3,4,8,11,15,17)])>70,]

plotname<-"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/14.05.23/pheatmap_all_main_genes_above70.tiff"

tiff(file=plotname,units="in",height=13,width=18,res=600)

pheatmap(as.matrix(above_70[,c(1,3,4,8,11,15,17)]), scale = "none",cluster_rows  = F,show_rownames = T,cutree_cols =7 ,color=colorRampPalette(c("navy", "white", "red"))(50),fontsize_row = 3, fontsize_col = 8)

dev.off()

```

```{r}
sub_Seted <-readRDS("/home/alu/aluguest/Lital_galitLab/seuruat_head18_5.rds")


genes_splited<-SplitObject(sub_Seted,split.by = "names" )

fru<-genes_splited[[1]]
Tbh<-genes_splited[[2]]
ple<-genes_splited[[3]]
Crz<-genes_splited[[4]]
NPFR<-genes_splited[[5]]
Tdc2<-genes_splited[[6]]
NPF<-genes_splited[[7]]


Idents(object = fru) <- fru@meta.data$identity

Idents(object = Tbh) <- Tbh@meta.data$identity
Idents(object = ple) <- ple@meta.data$identity
Idents(object = Crz) <- Crz@meta.data$identity
Idents(object = NPFR) <- NPFR@meta.data$identity
Idents(object = Tdc2) <- Tdc2@meta.data$identity
Idents(object = NPF) <- NPF@meta.data$identity


avg_fru<-as.data.frame(AverageExpression(object = fru,slot = 'counts' ))

avg_Tbh<-as.data.frame(AverageExpression(object = Tbh,slot = 'counts' ))
avg_ple<-as.data.frame(AverageExpression(object = ple,slot = 'counts' ))
avg_Crz<-as.data.frame(AverageExpression(object = Crz,slot = 'counts' ))
avg_NPFR<-as.data.frame(AverageExpression(object = NPFR,slot = 'counts' ))
avg_Tdc2<-as.data.frame(AverageExpression(object = Tdc2,slot = 'counts' ))
avg_NPF<-as.data.frame(AverageExpression(object = NPF,slot = 'counts' ))



summary(avg_Tdc2)


saveRDS(avg_fru,"/home/alu/aluguest/Lital_galitLab/avg_exp_fru.rds")

saveRDS(avg_Tbh,"/home/alu/aluguest/Lital_galitLab/avg_exp_tbh.rds")
saveRDS(avg_ple,"/home/alu/aluguest/Lital_galitLab/avg_exp_ple.rds")
saveRDS(avg_Crz,"/home/alu/aluguest/Lital_galitLab/avg_exp_Crz.rds")
saveRDS(avg_NPFR,"/home/alu/aluguest/Lital_galitLab/avg_exp_NPFR.rds")
saveRDS(avg_Tdc2,"/home/alu/aluguest/Lital_galitLab/avg_exp_tdc2.rds")
saveRDS(avg_NPF,"/home/alu/aluguest/Lital_galitLab/avg_exp_NPF.rds")

```

