---
title: "Untitled"
author: "lital barak"
date: "2023-07-18"
output: html_document
---
```{r}

sub_Seted<-readRDS("D:/seq_data/FCA/17_7_reclustered_head_elav_genes.rds")
Idents(object = sub_Seted) <- sub_Seted@meta.data$names
# 
# test<-AverageExpression(sub_Seted,slot = 'counts', group.by="ident",features = )
```

```{r}
main_genes<-c(" fru" , " Tbh" , " ple" , " Crz" , " NPFR", " Tdc2", " NPF"," OK107")

all<-NULL
for(j in 1:length(main_genes)){
  
  sub_Seted@meta.data$names<-""

SERUAT_HEAD<-sub_Seted
for(i in 1:nrow(SERUAT_HEAD@meta.data)){
# 
  if(j == 1) {
              if(SERUAT_HEAD@meta.data$s_fru[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"fru")

        }
  }
  if(j == 2){
    
    #removed
    #       if(SERUAT_HEAD@meta.data$s_Tbh[i] == TRUE){
    # SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tbh")
    # 
    #   }
  }

  if(j == 3){
        if(SERUAT_HEAD@meta.data$s_ple[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"ple")

}
  }
  if(j == 4){
    
          if(SERUAT_HEAD@meta.data$s_Crz[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Crz")

      }
  }
  if(j == 5 ){
    
        if(SERUAT_HEAD@meta.data$s_NPFR[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPFR")

    }
  }
  
  if( j == 6){
        if(SERUAT_HEAD@meta.data$s_Tdc2[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tdc2")

    }
  }

  if(j== 7){
    if(SERUAT_HEAD@meta.data$s_NPF[i] == TRUE){
SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPF")

      }
  }

  if(j == 8){
          if(grepl("Kenyon cell",SERUAT_HEAD@meta.data$tissu[i])){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"OK107")

  
}
  }







}


for(i in 1:nrow(SERUAT_HEAD@meta.data)){
  if(SERUAT_HEAD@meta.data$names[i] == ""){
   SERUAT_HEAD@meta.data$names[i]<-" elav"
   }
}

if(j!=2){
  
sub_Seted<-SERUAT_HEAD
Idents(object = sub_Seted) <- sub_Seted@meta.data$names

avg_exprs<-AverageExpression(sub_Seted, group.by="ident" )

tmp<-as.data.frame(avg_exprs[["RNA"]])
current_gene<-as.data.frame(tmp[,main_genes[j]])
rownames(current_gene)<-rownames(tmp)
colnames(current_gene)<-main_genes[j]
all<-bind_cols(all,current_gene)
}



}






```



```{r}
SERUAT_HEAD<-sub_Seted
main_genes<-c(" fru" , " Tbh" , " ple" , " Crz" , " NPFR", " Tdc2", " NPF"," OK107")
SERUAT_HEAD@meta.data$names<-""

for(i in 1:nrow(SERUAT_HEAD@meta.data)){

    if(SERUAT_HEAD@meta.data$s_ple[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"ple")

  }
    if(SERUAT_HEAD@meta.data$s_NPF[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPF")

    }
    if(SERUAT_HEAD@meta.data$s_NPFR[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPFR")

    }
    if(SERUAT_HEAD@meta.data$s_Tdc2[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tdc2")

    }
      if(SERUAT_HEAD@meta.data$s_Crz[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Crz")

      }
      if(SERUAT_HEAD@meta.data$s_Tbh[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tbh")

      }
        if(SERUAT_HEAD@meta.data$s_fru[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"fru")

        }
  

}
for(i in 1:nrow(SERUAT_HEAD@meta.data)){
  if(SERUAT_HEAD@meta.data$names[i] == ""){
   SERUAT_HEAD@meta.data$names[i]<-" elav"
   }
}

Idents(object = SERUAT_HEAD) <- SERUAT_HEAD@meta.data$names

 t<-SplitObject(SERUAT_HEAD, split.by = "names")
my_elav<-t[[" elav"]]
Idents(object = my_elav) <- my_elav@meta.data$names

avg_exprs<-AverageExpression(my_elav )

tmp<-as.data.frame(avg_exprs[["RNA"]])
current_gene<-as.data.frame(tmp[,"all"])
rownames(current_gene)<-rownames(tmp)
colnames(current_gene)<-" elav"
all<-bind_cols(all,current_gene)
```




```{r}

library(pheatmap)
all<-read.csv("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/mat_avg_elav_wo_tbh.csv",check.names=FALSE,row.names = 1)
# write.csv(all,"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/mat_avg_elav_wo_tbh.csv")
sig_genes<-read.csv("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/16.7.23/sig_elav_gene.csv")

all<-as.matrix(all)

genes <- c((sig_genes$X))



mat<-all[row.names(all) %in% genes, ]



  plotname<-paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/23.7.23/sc_clustering_wo_clust_colums.tiff")
  
 tiff(file=plotname,units="in",height=11,width=11,res=600)
pheatmap(mat, scale = "row",cluster_rows  = T,cluster_cols = FALSE,show_rownames = F,fontsize_row = 3, fontsize_col = 20,cutree_cols =8,color=colorRampPalette(c("navy", "white", "red"))(50))

dev.off()
```



```{r}

write.csv(avarges,"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/yulia_gene_sc_data.csv")

#this is the genes from yulia
unq_gene<-read.csv("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/yulia_de_genes.csv")

tmp_gene<-c((unq_gene$gene))
mat<-all[row.names(all) %in% tmp_gene, ]
#test_scale<-scale(mat)
mat<-as.data.frame(mat)
mat<-mat[apply(mat, 1, function(x) !all(x==0)),]

#test_scale<-mat+0.001

  plotname<-paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/30.07.23/new_markers/sc_clustering_marker_of_yulia_not_scaled.tiff")
 tiff(file=plotname,units="in",height=11,width=11,res=600)

pheatmap(mat, scale = "row", cluster_cols = T,cluster_rows  = T,show_rownames = F,fontsize_row = 3, fontsize_col = 8,cutree_cols =8,color=colorRampPalette(c("navy", "white", "red"))(50))

dev.off()
```





```{r}


library("dendsort")
phtmap <- pheatmap(mat)
row_dend <- phtmap[[2]]
main_genes<-c("fru" , "ple" , "Crz" , "NPFR", "Tdc2", "NPF","OK107")

  row_dend<-rotate(row_dend,res)
  
    t<-pheatmap(mat, cluster_rows =as.hclust(row_dend))


# i did tanformation so i could show the groups and not the features statistic
all_together_transformed <- as.data.frame(t(all_together))


##all together is ready and now we creating the heatmap itself

#install.packages("pvclust")

library(pvclust)

library("pheatmap")



test<-t(all)
library(seriation)
library(dendextend)
library(svDialogs)

if(change == "yes"){
  res<-c()
  for(i in 1:num_of_pop){
    res[i] <- dlg_list(groupsNames, multiple = TRUE,title="order for the heatmap")$res
  }
  t<-pheatmap(all_together, cluster_rows =as.hclust(row_dend))
  setwd((choose.dir(caption = "Select folder for saving the heatmap")))
  ggsave(plot = t, filename = "heatmap.jpeg", units = "cm")
  jpeg(filename = "dendrogram_p_val.jpeg", width = 1200, height = 800)
  plot(result)
  pvrect(result, alpha=0.95)
  dev.off()
  
}else{
  t <- pheatmap(all_together)
  setwd((choose.dir(caption = "Select folder for saving the heatmap")))
  ggsave(plot = t, filename = "heatmap.jpeg",units = "cm")
  jpeg(filename = "dendrogram_p_val.jpeg", width = 1200, height = 800)
  plot(result)
  pvrect(result, alpha=0.95)
  dev.off()

}

# Finding distance matrix
distance_mat <- dist(all_together, method = 'euclidean')
distance_mat





```




```{r}
library(pheatmap)
#> [1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"

callback = function(hc, mat){
  sv = svd(t(mat))$v[,c(1)]
  dend = reorder(as.dendrogram(hc), wts = sv^2)
  as.hclust(dend)
}

mat<-as.data.frame(mat)

data <- subset(mat, select=c("NPF", "Tdc2","ple","NPFR","elav","OK107","fru","Crz"))

#svd(t(iris[c(4, 2, 3, 1)]))$v[,1]
t<-mat[,c("NPF", "Tdc2","ple","NPFR","elav","OK107","fru","Crz")]
pheatmap(data, clustering_callback = callback)
```





```{r}
library(gplots)

data<-as.matrix(data)

ht <- heatmap.2(
    x = data,
    col = colorRampPalette(c("navy", "white", "red"))(50),
    trace = "none",
    key = FALSE,
    dendrogram = "both",
    main = "Example Data",
    labRow = FALSE,
    scale="row"
)
```

