
---
  title: "Untitled"
author: "lital barak"
date: "2023-05-15"
output: html_document
---
  
  
  
  ```{r}

```

```{r}


library("stringr")

list_of_cells<-c("dh44","npf","npfr","tdc2","crz","th","trh","fru","ok107","elav")
list_of_counts<-list.files("D:/seq_data/yulia",full.names = TRUE,pattern = "counts")

list_of_counts<-as.data.frame(list_of_counts)
main_data<-NULL

#to get the gene id
test<-read.table(gzfile(list_of_counts$list_of_counts[1]), header=TRUE) 
main_data$Geneid<-test$Geneid
main_data<-as.data.frame(main_data)


for(cell_name in 1:length(list_of_cells)){
  tmp_file_names_current_gene <- list_of_counts %>%
    filter(str_detect( list_of_counts,list_of_cells[cell_name]))
  for(reapts_current_gene in 1:nrow(tmp_file_names_current_gene)){
    
    tmp<-read.table(gzfile(tmp_file_names_current_gene$list_of_counts[reapts_current_gene]), header=TRUE)
    
    tmp_newname<-as.data.frame(tmp$Counts)
    
    colnames(tmp_newname)<-paste(list_of_cells[cell_name],"_rep",reapts_current_gene,"_counts",sep = "")
    
    main_data<-cbind(main_data,tmp_newname)
  }
}

rownames(main_data) <- main_data[,1]


write.csv(main_data, "C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/14.05.23/ten_cell_type.csv", row.names=FALSE)


```


```{r}

list_of_marker_fru<-c("fru","Pzl",
                      "Rgk1",
                      "rad",
                      "pros",
                      "lncRNA:CR44024",
                      "CG42613",
                      "dati",
                      "ab",
                      "CG32204"
)



main_fru <- main_data[ , grepl( "fru" , names( main_data ) ) ]

main_markers_fru<-NULL

for(i in 1:length(list_of_marker_fru)){
  main_markers_fru<-rbind(main_markers_fru,main_fru[list_of_marker_fru[i],]) 
}


main_markers_fru<-na.omit(main_markers_fru)
#rownames(main_markers_fru) <- main_data[,1]

#df1['fru',]
```



```{r}
main_data<-read.csv("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/14.05.23/ten_cell_type.csv")


list_of_cells<-c("dh44","npf","npfr","tdc2","crz","th","trh","fru","ok107","elav")
avarges<-NULL
#avarges$Geneid<-main_data$Geneid
avarges$fru<-rowMeans(x=main_data[ , grepl( "fru" , names( main_data ) ) ], na.rm = TRUE)
avarges$dh44<-rowMeans(x=main_data[ , grepl( "dh44" , names( main_data ) ) ], na.rm = TRUE)
avarges$npf<-rowMeans(x=main_data[ , grepl( "npf" , names( main_data ) ) ], na.rm = TRUE)
avarges$npfr<-rowMeans(x=main_data[ , grepl( "npfr" , names( main_data ) ) ], na.rm = TRUE)
avarges$tdc2<-rowMeans(x=main_data[ , grepl( "tdc2" , names( main_data ) ) ], na.rm = TRUE)
avarges$crz<-rowMeans(x=main_data[ , grepl( "crz" , names( main_data ) ) ], na.rm = TRUE)
avarges$th<-rowMeans(x=main_data[ , grepl( "th" , names( main_data ) ) ], na.rm = TRUE)
avarges$trh<-rowMeans(x=main_data[ , grepl( "trh" , names( main_data ) ) ], na.rm = TRUE)
avarges$ok107<-rowMeans(x=main_data[ , grepl( "ok107" , names( main_data ) ) ], na.rm = TRUE)

avarges$elav<-rowMeans(x=main_data[ , grepl( "elav" , names( main_data ) ) ], na.rm = TRUE)


avarges<-as.data.frame(avarges)

rownames(avarges)<-main_data$GeneSymbol
# 
# plotname<-"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/14.05.23/pheatmap_all_main_genes_yulia.tiff"
# 
# tiff(file=plotname,units="in",height=13,width=18,res=600)
# 
# pheatmap(as.matrix(avarges), scale = "none",cluster_rows  = F,show_rownames = F, color=colorRampPalette(c("navy", "white", "red"))(50))
# 
# dev.off()
# 
# write.csv(avarges, "C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/14.05.23/avg_ten_cell_type.csv", row.names=TRUE)
```



```{r}
library(htmltools)
library(DESeq2)
library(ggplot2)
library(autoplotly)
library(factoextra)
library("pheatmap")
library("RColorBrewer")
#library(limma)
library("manhattanly")
library("ggrepel")
library(plotly)
library("heatmaply")
library(dplyr)
library("DESeq2")
```


```{r}

cts <- (read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/14.05.23/ten_cell_type.csv",sep=",",row.names="GeneSymbol"))
coldata <- read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/14.05.23/meta_test.csv", row.names=1)
coldata_not_factorial <- read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/14.05.23/meta_test.csv")
data_noTPM <- (cts)
data<-data.frame(row.names=rownames(cts))
```



```{r}

num_of_exp =30
for (i in 1:num_of_exp){
  temp.df<-data.frame()
  temp.df<-data_noTPM %>%
    select(starts_with(coldata_not_factorial[i,1]))
  
  
  data[coldata_not_factorial[i,1]]<- rowMeans(temp.df)
}

coldata$reapet <- factor(coldata$reapet)
coldata$cell <- factor(coldata$cell)

all(rownames(coldata) %in% colnames(data))
all(rownames(coldata) == colnames(data))
data <- data[, rownames(coldata)]
all(rownames(coldata) == colnames(data))


```
```{r}
dds <- DESeqDataSetFromMatrix(countData = round(data),
                              colData = coldata,
                              design = ~ cell)
dds
dds$cell<-relevel(dds$cell,ref = "elav")

dds <- DESeq(dds)

resultsNames(dds)



#res <- results(dds)




#keep <- ((counts(dds,normalized=TRUE)) >= 30)


#and a minimum of least of 30 normalized counts in
#one of the repeats

#keep <-  rowSums( counts(dds, normalized=TRUE) >= 30 ) >= 1  
keep <- rowSums(counts(dds,normalized=TRUE)) >= 30
#dds <- dds[keep,]
res <- results(dds)

#vsdata <-vst(dds,blind=FALSE)

#autoplotly::autoplotly((plotPCA(vsdata, intgroup="cell")+geom_text(aes(label=name),vjust=3)+labs(title = "PCA:  10 cell type"))
#             , data = vsdata, colour = 'Species', frame = TRUE)


#elav is my control
#dds$cell<-relevel(dds$cell,ref = "elav")
table_counts_normalized <- counts(dds, normalized=TRUE)

resultsNames(dds)

```

```{r}

list_of_name<-c("inter","Crz","dh44","fru","npf","npfr","ok107","tdc2","th","trh")

names_of_comp<-resultsNames(dds)

final_all<-NULL
for(i in 1:length(list_of_name)){
  all<-NULL
  if(!(list_of_name[i] =="inter" | list_of_name[i]=="dh44" | list_of_name[i]=="trh")){
    res_tmp <- results(dds, name=names_of_comp[i])
    all<-subset(res_tmp, padj<0.05 & abs(log2FoldChange)>=1)
    all<-as.data.frame(all)
    all<-cbind(all,list_of_name[i])
    all<-cbind(all,gene=rownames(all))
   final_all<- rbind(final_all,all)
  }
  #res_tmp <- results(dds, name="condition_treated_vs_untreated")
}


```



```{r}
up<-subset(res, padj<.05 & log2FoldChange>=1)
up<-as.data.frame(up)
write.csv(up, "C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/14.05.23/upregulated.csv",
          row.names = TRUE)

#creating a csv file with all the values with pval<.05 & log2FoldChange>=1 from T VS NT for down regulated genes
down<-subset(res, padj<.05 & log2FoldChange<=-1)
down<-as.data.frame(down)
write.csv(down, "C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/14.05.23/downregulated.csv",
          row.names = TRUE)



all<-subset(res, padj<0.05 & abs(log2FoldChange)>=1)
all<-as.data.frame(all)

# # 
# data_frame_merge <- merge(up, down,
#           by = 'row.names', all = TRUE)
```



```{r}
#data_frame_merge <- merge(up, down,
#      by = 'row.names', all = TRUE)
genes <- c(row.names(all))


mat<-table_counts_normalized[genes, ]
#mat <- assay(dds)[genes, ]
#mat<-scale(mat)
#mat <- mat - rowMeans(mat)
df <- as.data.frame(colData(dds)[,c("cell","reapet")])


pheatmap(mat, annotation_col = df,  scale = "row",cluster_cols=TRUE,show_rownames=TRUE,cluster_rows=FALSE)

```

```{r}


# dt[dt$fct %in% data_frame_merge$Row.names,]
# 
# pheatmap(data_subset_norm_all,cluster_cols = FALSE, color = my_palette, annotation_col = my_sample_col,main= paste("sig genes pvalue <= 0.05 and threshold LFC=0.58 ",nrow(data_subset_norm_all)), fontsize_row=5)
# # avarges[apply(avarges, 1, function(x) all(is.finite(x))), ]
# # 
# # 
# # heatmap(as.matrix(avarges))

```



```{r}

#data_frame_merge <- merge(up, down,
#                by = 'row.names', all = TRUE)
#genes <- c(data_frame_merge$Row.names)
#mat <- assay(dds)[genes, ]

#list_of_cells<-c("dh44","npf","npfr","tdc2","crz","th","trh","fru","ok107","elav")
list_of_cells<-c("npf","npfr","tdc2","crz","th","fru","ok107","elav")

avarges<-NULL



main_data<-as.data.frame(mat)
#avarges$Geneid<-main_data$Geneid
avarges$fru<-rowMeans(x=main_data[ , grepl( "fru" , names( main_data ) ) ], na.rm = TRUE)
#avarges$dh44<-rowMeans(x=main_data[ , grepl( "dh44" , names( main_data ) ) ], na.rm = TRUE)
avarges$npf<-rowMeans(x=main_data[ , grepl( "npf" , names( main_data ) ) ], na.rm = TRUE)
avarges$npfr<-rowMeans(x=main_data[ , grepl( "npfr" , names( main_data ) ) ], na.rm = TRUE)
avarges$tdc2<-rowMeans(x=main_data[ , grepl( "tdc2" , names( main_data ) ) ], na.rm = TRUE)
avarges$crz<-rowMeans(x=main_data[ , grepl( "crz" , names( main_data ) ) ], na.rm = TRUE)
avarges$th<-rowMeans(x=main_data[ , grepl( "th" , names( main_data ) ) ], na.rm = TRUE)
#avarges$trh<-rowMeans(x=main_data[ , grepl( "trh" , names( main_data ) ) ], na.rm = TRUE)
avarges$ok107<-rowMeans(x=main_data[ , grepl( "ok107" , names( main_data ) ) ], na.rm = TRUE)

avarges$elav<-rowMeans(x=main_data[ , grepl( "elav" , names( main_data ) ) ], na.rm = TRUE)


avarges<-as.data.frame(avarges)

rownames(avarges)<-rownames(main_data)


# 
# genes <- c(row.names(all))
# 
# 
# mat<-table_counts_normalized[genes, ]
# #mat <- assay(dds)[genes, ]
# #mat<-scale(mat)
# #mat <- mat - rowMeans(mat)
# df <- as.data.frame(colData(dds)[,c("cell","reapet")])


#avarges<-scale(avarges, center = TRUE, scale = TRUE)


mat_new<-as.matrix(avarges)


#pheatmap(mat_new,  cluster_cols=FALSE,show_rownames=FALSE,cluster_rows=FALSE)



  plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/23.7.23/yulia_clustering.tiff")
  
 tiff(file=plotname,units="in",height=11,width=11,res=600)

pheatmap(mat_new, scale = "row",cluster_rows  = T,show_rownames = F, color=colorRampPalette(c("navy", "white", "red"))(50),fontsize_row = 3, fontsize_col = 8,cutree_cols =8)
#plot(t,xaxt = "n")
dev.off()


```




```{r}
# cts <- (read.csv("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/14.05.23/avg_ten_cell_type.csv",sep=",",row.names="GeneSymbol"))
# coldata <- read.csv("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/14.05.23/meta_test_for_avg.csv", row.names=1)
# coldata_not_factorial <- read.csv("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/14.05.23/meta_test_for_avg.csv")
# data_noTPM <- (cts)
# data<-data.frame(row.names=rownames(cts))
# 
# 
# 
# 
# num_of_exp =10
# for (i in 1:num_of_exp){
#   temp.df<-data.frame()
#   temp.df<-data_noTPM %>%
#     select(starts_with(coldata_not_factorial[i,1]))
#   
#   
#   data[coldata_not_factorial[i,1]]<- rowMeans(temp.df)
# }
# 
# #coldata$reapet <- factor(coldata$reapet)
# coldata$cell <- factor(coldata$cell)
# 
# all(rownames(coldata) %in% colnames(data))
# all(rownames(coldata) == colnames(data))
# data <- data[, rownames(coldata)]
# all(rownames(coldata) == colnames(data))
# 
# 
# dds <- DESeqDataSetFromMatrix(countData = round(data),
#                               colData = coldata,
#                               design = ~ cell)
# dds
# dds$cell<-relevel(dds$cell,ref = "elav")
# 
# dds <- DESeq(dds)
# 
# resultsNames(dds)
# 
# 
# res <- results(dds)

#pheatmap(as.matrix(above_30th_avg), scale = "none",cluster_rows  = F,show_rownames = T, color=colorRampPalette(c("navy", "white", "red"))(50),fontsize_row = 3, fontsize_col = 8,cutree_cols =10)
```

