---
title: "Untitled"
author: "lital barak"
date: "2023-06-06"
output: html_document
---

```{r}
library(spatstat.utils)
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)
library(tidyr)

elav_only <-readRDS("D:/seq_data/FCA/elav.rds")

SERUAT_HEAD <-readRDS("D:/seq_data/FCA/seuruat_head5_12.rds")

SERUAT_HEAD<-elav_only
```

```{r}
SERUAT_HEAD@meta.data$Syt1<- FetchData(SERUAT_HEAD, vars = "Syt1",)


SERUAT_HEAD@meta.data$elav<- FetchData(SERUAT_HEAD, vars = "elav")
SERUAT_HEAD@meta.data$brp<- FetchData(SERUAT_HEAD, vars = "brp")



SERUAT_HEAD@meta.data$NPF<- FetchData(SERUAT_HEAD, vars = "NPF")

SERUAT_HEAD@meta.data$ple<- FetchData(SERUAT_HEAD, vars = "ple")
SERUAT_HEAD@meta.data$NPFR<- FetchData(SERUAT_HEAD, vars = "NPFR")
SERUAT_HEAD@meta.data$Tdc2<- FetchData(SERUAT_HEAD, vars = "Tdc2")
SERUAT_HEAD@meta.data$Crz<- FetchData(SERUAT_HEAD, vars = "Crz")

SERUAT_HEAD@meta.data$Tbh<- FetchData(SERUAT_HEAD, vars = "Tbh")
SERUAT_HEAD@meta.data$fru<- FetchData(SERUAT_HEAD, vars = "fru")


SERUAT_HEAD$sample <- rownames(SERUAT_HEAD@meta.data)

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "__", "_")

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "-", "_")

SERUAT_HEAD@meta.data <- separate(SERUAT_HEAD@meta.data, col = 'sample', into = c("test",'Barcode','identity', 'Sex'), 
                                  sep = '_')

SERUAT_HEAD@meta.data$identity<-as.factor(SERUAT_HEAD@meta.data$identity)
View(SERUAT_HEAD@meta.data)
```

```{r}
all_gene_csv<-as.data.frame(read.csv("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/2.7.23/all_genes.csv"))



```

```{r}
number_of_fca<-c("1","4","5","6","7","8","9","10","11","12","13","14","15")
names_of_fca<-paste("FCA",number_of_fca,sep="")

#threshold_values<-c(0.36,0.3,0.18,0.05,0.16,0.33,0.57)
gene_names<-c("Syt1","elav","brp","ple","NPF","NPFR","Tdc2","Crz","Tbh","fru")

fullname<-paste("s_",gene_names,sep="")


SERUAT_HEAD@meta.data$s_ple<-""
SERUAT_HEAD@meta.data$s_NPF<-""
SERUAT_HEAD@meta.data$s_Tdc2<-""
SERUAT_HEAD@meta.data$s_Crz<-""
SERUAT_HEAD@meta.data$s_Tbh<-""
SERUAT_HEAD@meta.data$s_fru<-""
SERUAT_HEAD@meta.data$s_Syt1<-""
SERUAT_HEAD@meta.data$s_brp<-""
SERUAT_HEAD@meta.data$s_elav<-""
```


```{r}
elav_only <-readRDS("D:/seq_data/FCA/elav.rds")

SERUAT_HEAD<-readRDS("D:/seq_data/FCA/elav_genes_reclustred.rds")

# SERUAT_HEAD<-readRDS("D:/seq_data/FCA/elav_genes_reclustred.rds")

```



```{r}


SERUAT_HEAD<-elav_only
for(gene_i in 1:length(gene_names)){

for(fca_i in 1:length(names_of_fca)){
FCA_LIST<- all_gene_csv[all_gene_csv$FCA %in% names_of_fca[fca_i],]

current_value_threshold<- FCA_LIST[FCA_LIST$Gene %in% gene_names[[gene_i]],]$value


SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],fullname[gene_i]]<-c(SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],gene_names[[gene_i]]] >current_value_threshold)

  
}
}


SERUAT_HEAD@meta.data$names<-""




# for(i in 1:nrow(SERUAT_HEAD@meta.data)){
#       if(SERUAT_HEAD@meta.data$s_elav[i] == TRUE){
#     SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"elav")
# 
#   }
# }


# for(i in 1:nrow(SERUAT_HEAD@meta.data)){
#   if(SERUAT_HEAD@meta.data$s_Syt1[i] == TRUE){
#     SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Syt1")
# 
#   }
#     if(SERUAT_HEAD@meta.data$s_brp[i] == TRUE){
#     SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"brp")
# 
#     }
#       if(SERUAT_HEAD@meta.data$s_elav[i] == TRUE){
#     SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"elav")
# 
#       }
# }

#SERUAT_HEAD<-sub_seted




for(i in 1:nrow(SERUAT_HEAD@meta.data)){
  # if(SERUAT_HEAD@meta.data$s_Syt1[i] == TRUE){
  #   SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Syt1")
  # 
  # }
  #   if(SERUAT_HEAD@meta.data$s_brp[i] == TRUE){
  #   SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"brp")
  # 
  #   }
  #     if(SERUAT_HEAD@meta.data$s_elav[i] == TRUE){
  #   SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"elav")
  # 
  #     }
    if(SERUAT_HEAD@meta.data$s_ple[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"ple")

  }
    if(SERUAT_HEAD@meta.data$s_NPF[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPF")

    }
    if(SERUAT_HEAD@meta.data$s_NPFR[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPFR")

    }
    if(SERUAT_HEAD@meta.data$s_Tdc2[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tdc2")

    }
      if(SERUAT_HEAD@meta.data$s_Crz[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Crz")

      }
      if(SERUAT_HEAD@meta.data$s_Tbh[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tbh")

      }
        if(SERUAT_HEAD@meta.data$s_fru[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"fru")

        }
  

}




# for(i in 1:nrow(SERUAT_HEAD@meta.data)){
#   if(SERUAT_HEAD@meta.data$names[i] == ""){
#    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"elav")
#    }
# }
# 

SERUAT_HEAD@meta.data$names<-as.factor( SERUAT_HEAD@meta.data$names)

#sub_Seted<-subset(SERUAT_HEAD, names = ' Syt1 brp elav')

t<-grepl(" Syt1 brp elav",SERUAT_HEAD@meta.data$names)
sub_Seted<-subset(SERUAT_HEAD, names != "")


temp<-SERUAT_HEAD
t<-SplitObject(SERUAT_HEAD, split.by = "names")


sub_seted<-t[[" Syt1 brp elav"]]

test<-as.data.frame(table(sub_Seted@meta.data$names))

order_test<-test[order(test$Freq,decreasing=TRUE),]



fru<-t[[" Syt1 brp elav fru"]]
Crz<-t[[" Syt1 brp elav Crz"]]
Tdc2<-t[[" Syt1 brp elav Tdc2"]]
ple<-t[[" Syt1 brp elav ple"]]
Tbh<-t[[" Syt1 brp elav Tbh"]]
NPFR<-t[[" Syt1 brp elav NPFR"]]
NPF<-t[[" Syt1 brp elav NPF"]]

pbmc.big <- merge(fru, y = c(Crz, Tdc2,ple,Tbh,NPFR,NPF))
Idents(object = pbmc.big) <- pbmc.big@meta.data$names


# 
 saveRDS(SERUAT_HEAD,"D:/seq_data/FCA/11_7_head_elav_genes.rds")



glu<-sub_Seted
glu <- NormalizeData(object = glu)
glu <- FindVariableFeatures(object = glu)
glu <- ScaleData(object = glu)
glu <- RunPCA(object = glu)
glu <- FindNeighbors(object = glu, dims = 1:20)
glu <- FindClusters(object = glu)
glu <- RunUMAP(object = glu, dims = 1:20)


plotname<-"C:/Users/Lital/OneDrive - Bar Ilan University/Lital/weekly presentation/25.6.23/recclsuted_wo_elav/elav_genes_reclustered_all_genes.tiff"

tiff(file=plotname,units="in",height=13,width=18,res=600)

Idents(object = glu) <- glu@meta.data$names


# t<-SplitObject(glu, split.by = "names")
# # label=TRUE
# elav<-DimPlot(object = t[[" elav"]],label.size
# =3.5,pt.size = 1.5,cols ="white")


DimPlot(object = glu,label.size
=3.5,pt.size = 1.5)

dev.off()


table(glu@meta.data$names)

# write.csv(order_test,"C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/5.6.23/gene_with_neruons.csv",row.names = FALSE)

```

```{r}
glu<-SERUAT_HEAD
Idents(object = glu) <- glu@meta.data$names

library(stringr)
list_of_gene<-c("ple","NPFR","fru","Tdc2","NPF","Crz","Tbh")







#par(mfrow = c(3, 3),mar = c(2.1, 3, 9, 3),xaxs = "i",yaxs = "i",cex.axis=1.1,cex.lab=1.1)

for(gene in 1:length(list_of_gene)){
  Main_gene<-list_of_gene[gene]
  

  num_of_genes<-length(table(glu@meta.data$names))


my_cols<-DiscretePalette(num_of_genes, palette = NULL)

list_of_gene_names<-names(table(glu@meta.data$names))

my_plot_order_names<-c()
the_last_to_plot_names<-c()
names(my_cols)<-list_of_gene_names
my_cols[" Crz"]<-"#fffdb6"
my_cols[" fru"]<-"#ffc3ba"
my_cols[" NPF"]<-"#adffbf"
my_cols[" NPFR"]<-"#9fbdf8"
my_cols[" ple"]<-"#9f9ff8"
my_cols[" Tbh"]<-"#ff9ff8"
my_cols[" Tdc2"]<-"#a4ceff"

my_cols[" Crz fru"]<-"#564baa"
my_cols[" NPF fru"]<-"#8e2baa"
my_cols[" NPFR fru"]<-"#8e2b5c"
my_cols[" NPFR Tdc2 Tbh"]<-"#1b7c4a"
my_cols[" ple Tdc2"]<-"#1b5c9d"
my_cols[" Tbh fru"]<-"#1b5433"
my_cols[" Tdc2 fru"]<-"#089b33"
my_cols[" Tdc2 Tbh"]<-"#593831"




  for(i in 1:num_of_genes){
    if(!grepl(Main_gene, list_of_gene_names[i], fixed=TRUE)){
      my_plot_order_names<-c(my_plot_order_names,list_of_gene_names[i])
      my_cols[list_of_gene_names[i]]<-"#e2e2e2"
      print(i)
    }else{
      the_last_to_plot_names<-c(the_last_to_plot_names,list_of_gene_names[i])
    }
  }
#NPF
if(gene == 5){
  my_cols[list_of_gene_names[6]]<-"#e2e2e2"
  my_cols[list_of_gene_names[7]]<-"#e2e2e2"
  my_cols[list_of_gene_names[8]]<-"#e2e2e2"
}
#my_plot_order_names<-c(my_plot_order_names,the_last_to_plot_names)


   plotname<-paste0("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/2.7.23/recclsuted_wo_elav/",Main_gene,".tiff")
  
 tiff(file=plotname,units="in",height=11,width=11,res=1000)

t<-DimPlot(object = glu,cols = my_cols,label=FALSE,pt.size = 1,order =the_last_to_plot_names )+ guides(color = guide_legend(override.aes = list(size=11,face="bold"), ncol=1) )+ggtitle(Main_gene)+ theme(plot.title = element_text(hjust = 0.5,size = 20, face = "bold"))
plot(t)
#plot(t,xaxt = "n")
dev.off()

}


# Idents(object = sub_Seted) <- sub_Seted@meta.data$names
#Main_gene<-"Tdc2"
# num_of_genes<-length(table(glu@meta.data$names))
# 
# my_cols<-DiscretePalette(num_of_genes, palette = NULL)
# 
# 
# list_of_gene_names<-names(table(glu@meta.data$names))
# 


#nums<- str_which(list_of_gene_names, "Crz")


# names(my_cols)<-list_of_gene_names
# 
#   for(i in 1:num_of_genes){
#     if(!grepl(Main_gene, list_of_gene_names[i], fixed=TRUE)){
#       my_cols[list_of_gene_names[i]]<-"#FFFFFF"
#       print(i)
#     }
#  #   
#  #   if(i == any(nums)){
#  #     print(i)
#  #   }
#   }


 



# plotname<-paste0("C:/Users/Lital/OneDrive - Bar Ilan University/Lital/weekly presentation/18.6.23/",Main_gene,".tiff")
#  
# plotname<-"C:/Users/Lital/OneDrive - Bar Ilan University/Lital/weekly presentation/5.6.23/umap_elav_Brp_syt1.tiff"

# tiff(file=plotname,units="in",height=13,width=18,res=600)
# 
# 
# 
# DimPlot(object = glu,cols = my_cols,label=TRUE,label.size
# =3.5,pt.size = 1.5)
# dev.off()
```

```{r}
glu<-SERUAT_HEAD
#saveRDS(glu,"D:/seq_data/FCA/recluster_syt1_brp_elav_genes.rds")
   plotname<-paste0("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/2.7.23/recclsuted_wo_elav/splited.tiff")


tiff(file=plotname,units="in",height=15,width=20,res=1000)

DimPlot(glu,split.by = "names",pt.size = 2.5)+facet_wrap(~names)

dev.off()

```
```{r}

```


```{r}

#saveRDS(glu,"D:/seq_data/FCA/recluster_syt1_brp_elav_genes.rds")
# glu<-readRDS("D:/seq_data/FCA/elav_genes_reclustred.rds")
list_of_gene<-c("ple","NPFR","fru","Tdc2","NPF","Crz","Tbh")



 plotname<-paste0("C:/Users/Lital/OneDrive - Bar Ilan University/Lital/weekly presentation/25.6.23/featureplot_elavpos.tiff")
  tiff(file=plotname,units="in",height=20,width=20,res=1000)

FeaturePlot(glu, features = list_of_gene, pt.size =5 )
dev.off()


```



```{r}
library(ggplot2)

 SERUAT_HEAD<-readRDS("D:/seq_data/FCA/11_7_head_elav_genes.rds")
glu<-SERUAT_HEAD
Idents(object = glu) <- glu@meta.data$names

t<-SplitObject(glu, split.by = "names")

library(stringr)
list_of_gene<-c("ple","NPFR","fru","Tdc2","NPF","Crz","Tbh")

list_of_gene_names<-names(table(glu@meta.data$names))

 num_of_genes<-length(table(glu@meta.data$names))


my_cols<-DiscretePalette(num_of_genes, palette = "glasbey")


list_of_gene_names<-names(table(glu@meta.data$names))

my_plot_order_names<-c()
the_last_to_plot_names<-c()
names(my_cols)<-list_of_gene_names
# my_cols[" Crz"]<-"#fffdb6"
# my_cols[" fru"]<-"#ffc3ba"
# my_cols[" NPF"]<-"#adfff8"
# my_cols[" NPFR"]<-"#9fbdf8"
# my_cols[" ple"]<-"#9f9ff8"
# my_cols[" Tbh"]<-"#ff9ff8"
# my_cols[" Tdc2"]<-"#a4ceff"
# 
# my_cols[" Crz fru"]<-"#564baa"
# my_cols[" NPF fru"]<-"#8e2baa"
# my_cols[" NPFR fru"]<-"#8e2b5c"
# my_cols[" NPFR Tdc2 Tbh"]<-"#1b7c4a"
# my_cols[" ple Tdc2"]<-"#1b5c9d"
# my_cols[" Tbh fru"]<-"#1b5433"
# my_cols[" Tdc2 fru"]<-"#089b33"
# my_cols[" Tdc2 Tbh"]<-"#593831"



for(gene in 2:length(list_of_gene_names)){
  #Main_gene<-list_of_gene[gene]
  
# 
#   num_of_genes<-length(table(glu@meta.data$names))
# 
# 
# my_cols<-DiscretePalette(num_of_genes, palette = NULL)


# my_plot_order_names<-c()
# the_last_to_plot_names<-c()
# names(my_cols)<-list_of_gene_names


  # for(i in 1:num_of_genes){
  #   if(!grepl(Main_gene, list_of_gene_names[i], fixed=TRUE)){
  #     my_plot_order_names<-c(my_plot_order_names,list_of_gene_names[i])
  #     my_cols[list_of_gene_names[i]]<-"#e2e2e2"
  #     print(i)
  #   }else{
  #     the_last_to_plot_names<-c(the_last_to_plot_names,list_of_gene_names[i])
  #   }
  # }
#NPF
# if(gene == 5){
#   my_cols[list_of_gene_names[6]]<-"#e2e2e2"
#   my_cols[list_of_gene_names[7]]<-"#e2e2e2"
#   my_cols[list_of_gene_names[8]]<-"#e2e2e2"
# }
#my_plot_order_names<-c(my_plot_order_names,the_last_to_plot_names)



   plotname<-paste0("C:/Users/Lital/OneDrive - Bar Ilan University/Lital/weekly presentation/2.7.23/recclsuted_per_genes_croess_elav/",trimws(list_of_gene_names[gene]),".tiff")
  
 tiff(file=plotname,units="in",height=11,width=11,res=1000)

 
 if(nrow(t[[list_of_gene_names[gene]]]@meta.data) > 1){
   
   if(nrow(t[[list_of_gene_names[gene]]]@meta.data) > 1 && nrow(t[[list_of_gene_names[gene]]]@meta.data) < 20){
        my_plot<-DimPlot(object = t[[list_of_gene_names[gene]]],cols = my_cols[list_of_gene_names[gene]],pt.size = 5 )+guides(color = guide_legend(override.aes = list(size=11,face="bold"), ncol=1) )+ggtitle(list_of_gene_names[gene])+ theme(plot.title = element_text(hjust = 0.5,size = 20, face = "bold"))


plot(my_plot)
#plot(t,xaxt = "n")
dev.off()
   }else{
             my_plot<-DimPlot(object = t[[list_of_gene_names[gene]]],cols = my_cols[list_of_gene_names[gene]],pt.size = 1.1 )+guides(color = guide_legend(override.aes = list(size=11,face="bold"), ncol=1) )+ggtitle(list_of_gene_names[gene])+ theme(plot.title = element_text(hjust = 0.5,size = 20, face = "bold"))

plot(my_plot)
#plot(t,xaxt = "n")
dev.off()
   }

 }


}

```

```{r}


library(ggplot2)

SERUAT_HEAD<-readRDS("D:/seq_data/FCA/elav_genes_reclustred.rds")
glu<-SERUAT_HEAD
Idents(object = glu) <- glu@meta.data$names

t<-SplitObject(glu, split.by = "names")

library(stringr)
list_of_gene<-c("ple","NPFR","fru","Tdc2","NPF","Crz","Tbh")

list_of_gene_names<-names(table(glu@meta.data$names))

 num_of_genes<-length(table(glu@meta.data$names))


my_cols<-DiscretePalette(num_of_genes, palette = NULL)

list_of_gene_names<-names(table(glu@meta.data$names))

my_plot_order_names<-c()
the_last_to_plot_names<-c()
names(my_cols)<-list_of_gene_names
my_cols[" Crz"]<-"#fffdb6"
my_cols[" fru"]<-"#ffc3ba"
my_cols[" NPF"]<-"#adfff8"
my_cols[" NPFR"]<-"#9fbdf8"
my_cols[" ple"]<-"#9f9ff8"
my_cols[" Tbh"]<-"#ff9ff8"
my_cols[" Tdc2"]<-"#a4ceff"

my_cols[" Crz fru"]<-"#564baa"
my_cols[" NPF fru"]<-"#8e2baa"
my_cols[" NPFR fru"]<-"#8e2b5c"
my_cols[" NPFR Tdc2 Tbh"]<-"#1b7c4a"
my_cols[" ple Tdc2"]<-"#1b5c9d"
my_cols[" Tbh fru"]<-"#1b5433"
my_cols[" Tdc2 fru"]<-"#089b33"
my_cols[" Tdc2 Tbh"]<-"#593831"



for(gene in 1:length(list_of_gene_names)){

   plotname<-paste0("C:/Users/Lital/OneDrive - Bar Ilan University/Lital/weekly presentation/2.7.23/recclsuted_per_genes_croess_elav/",trimws(list_of_gene_names[gene]),".tiff")
  
 tiff(file=plotname,units="in",height=11,width=11,res=1000)

 
 if(nrow(t[[list_of_gene_names[gene]]]@meta.data) > 1){
   
   if(nrow(t[[list_of_gene_names[gene]]]@meta.data) > 1 && nrow(t[[list_of_gene_names[gene]]]@meta.data) < 10){
     
     md <- t[[list_of_gene_names[gene]]]
    coords <- Embeddings(glu[["umap"]])

        my_plot<-DimPlot(object = t[[list_of_gene_names[gene]]],cols = my_cols[list_of_gene_names[gene]],pt.size = 3 )+guides(color = guide_legend(override.aes = list(size=11,face="bold"), ncol=1) )+ggtitle(list_of_gene_names[gene])+ theme(plot.title = element_text(hjust = 0.5,size = 20, face = "bold"))+  scale_shape_manual(values=21:22)


plot(my_plot)
#plot(t,xaxt = "n")
dev.off()
   }else{
             my_plot<-DimPlot(object = t[[list_of_gene_names[gene]]],cols = my_cols[list_of_gene_names[gene]],pt.size = 1 )+guides(color = guide_legend(override.aes = list(size=11,face="bold"), ncol=1) )+ggtitle(list_of_gene_names[gene])+ theme(plot.title = element_text(hjust = 0.5,size = 20, face = "bold"))+  scale_shape_manual(values=21:22)

plot(my_plot)
#plot(t,xaxt = "n")
dev.off()
   }

 }


}
# get metadata
md <- glu[[]]

# get embeddings
coords <- Embeddings(glu[["umap"]])

# combine dataframes
md <- cbind(md, coords)

# plot
ggplot(md, aes(x = UMAP_1, y = UMAP_2, fill = md$names)) +
  geom_point(shape = 21, size = 2) + theme_classic()
```

