---
title: "analysis_for_thesis"
author: "lital barak"
date: "2023-10-15"
output: html_document
---



```{r}
library(spatstat.utils)
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)



library(edgeR) # BiocManager::install("edgeR")
library(limma)
library(Seurat)
library(ggplot2)
library(dplyr)
library(ggplot2)
library(Matrix)
library(tidyr)
library(stringr)
library("gridExtra")
library(loomR)



#OK107 <-readRDS("D:/seq_data/FCA/17_7_head_elav_genes.rds")
 

#SERUAT_HEAD <-readRDS("D:/seq_data/FCA/elav.rds")

SERUAT_HEAD <-readRDS("D:/seq_data/FCA/15_10_elav_pos_ok107_all_genes.rds")



# 
# SERUAT_HEAD$sample <- rownames(SERUAT_HEAD@meta.data)
# 
# SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "__", "_")
# 
# SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "-", "_")
# 
# View(SERUAT_HEAD@meta.data)
# SERUAT_HEAD@meta.data <- separate(SERUAT_HEAD@meta.data, col = 'sample', into = c("test",'Barcode','identity', 'Sex'), 
#                                   sep = '_')

new<-SplitObject(SERUAT_HEAD, split.by = "identity")


all.genes_head<-as.data.frame(rownames(SERUAT_HEAD))

head_FCA_sum<-function(gene_name,y_value,bottom_x_value,top_x_value,FCA,NUMBER_OF_FCA,path_of_photos,to_plot){
  
  #remmber to rename the path to the username of he computer
  plotname<- paste(path_of_photos,"/",NUMBER_OF_FCA,".tiff",sep = "")
  #plotname<-paste("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/27.2.23/",gene_name,"/",NUMBER_OF_FCA,".tiff",sep = "")
  
  #precnt_name<- paste(gene_name,"$",gene_name,sep="")

 # precnt_name<-paste("percent.",gene_name,sep="")
  #FCA[[precnt_name]] <- PercentageFeatureSet(FCA,features =gene_name)
  
  #gene_head<-as.data.frame(get(precnt_name,FCA@meta.data))
  gene_head<-as.data.frame(FCA@meta.data[[gene_name]])
  colnames(gene_head)<-"head"
  
  
  #gene_head_density <- hist(gene_head$head, breaks=seq(0,10,l=1000),plot = FALSE)         # Store output of hist function
  #gene_head_density$density <- gene_head_density$counts /    # Compute density values
  # sum(gene_head_density$counts) * 100
  
  
  gene_sum_head <- hist(gene_head$head, breaks=seq(0,20,l=20000),plot = FALSE)                       # Store histogram info
  gene_sum_head$counts <- revcumsum((gene_sum_head$counts)) 
  
  
  main_title <-paste("cumilative garph in ",NUMBER_OF_FCA,"need to be " ,y_value," cells of ",gene_name)

  new_yval<-y_value + 0.5*(y_value)
  
  
  exp_per_counts<-gene_sum_head[["breaks"]][max(which(gene_sum_head[["counts"]] > y_value))]
  
  if(to_plot == TRUE){
      tiff(file=plotname,units="in",height=13,width=18,res=600)
      t<-plot(gene_sum_head,col=alpha('red',0.5), main=main_title, xlab='% expression',ylab='number of cells',ylim =c(0,new_yval),xlim =rev(c(bottom_x_value, top_x_value)),cex.axis=2.2,cex.lab=1.5, cex.main=2,xaxt = "n")
  abline(h = y_value, col = "darkgreen")
  abline(v =exp_per_counts, col = "blue") 
  
  axis(1, at = rev(seq(bottom_x_value,top_x_value, by =
                         0.01)),
       labels = rev(seq(bottom_x_value,top_x_value, by = 0.01)))
  
  
  dev.off()
  }else{
      return(exp_per_counts)
      dev.off()

  }

}
```



```{r}
#max(which(gene_sum_head[["counts"]] > 4))

number_of_fca<-c("1","4","5","6","7","8","9","10","11","12","13","14","15")
names_of_fca<-paste("FCA",number_of_fca,sep="")

plot_or_not<-FALSE
# path_of_photos<-"C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/18.6.23/"

path_of_photos<-"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/threshold/"
#gene<-"ple"
#expceted_cell_num<-515


list_of_gene<-c("ple","NPFR","fru","Tdc2","NPF","Crz","Tbh")
list_of_expected_cells<-c(515,100,1454,265,40,300,265)

all_gene_csv<-NULL

for(i_gene in 1:length(list_of_gene)){
  
  
  gene<-list_of_gene[i_gene]
  expceted_cell_num<-list_of_expected_cells[i_gene]
  
  full_path_of_gene<-paste(path_of_photos,gene,"/",sep = "")

  to_csv<-NULL
if(dir.exists(full_path_of_gene)){
  for(i in 1:length(new)){
    #change to 47000 beacuse elav cells only
   # y_Vale_max_origin<-round((expceted_cell_num*ncol(new[[i]]))/47000) # to find how many sample suppose to be
    #y_Vale_max<-y_Vale_max_origin + 0.5 *(y_Vale_max_origin)
    
    y_Vale_max_origin<-round((expceted_cell_num*ncol(new[[i]]))/100000)
   expression_level<- head_FCA_sum(gene,y_Vale_max_origin,0,5,new[[i]],names_of_fca[i],full_path_of_gene,plot_or_not)
      temp<-c(expression_level,names_of_fca[i],gene)
    to_csv<-rbind(to_csv,temp)
  }
}else{
  dir.create(full_path_of_gene)
  for(i in 1:length(new)){
    y_Vale_max_origin<-round((expceted_cell_num*ncol(new[[i]]))/100000) # to find how many sample suppose to be
    #y_Vale_max<-y_Vale_max_origin + 0.5 *(y_Vale_max_origin)
   expression_level<- head_FCA_sum(gene,y_Vale_max_origin,0,5,new[[i]],names_of_fca[i],full_path_of_gene,plot_or_not)
   
    temp<-c(expression_level,names_of_fca[i],gene)
    # colnames(temp)<-gene

    to_csv<-rbind(to_csv,temp)
  }
}

of_all<-head_FCA_sum(gene,expceted_cell_num,0,5,SERUAT_HEAD,"ALL",full_path_of_gene,plot_or_not)

temp<-c(of_all,"ALL",gene)
to_csv<-rbind(to_csv,temp)
  
to_csv<-as.data.frame(to_csv)


all_gene_csv<-rbind(all_gene_csv,to_csv)



  
}







full_path_csv<-paste(path_of_photos,"all_genes",".csv",sep = "")
colnames(all_gene_csv)<-c("value","FCA","Gene")
all_gene_csv$value<-as.numeric(all_gene_csv$value)
write.csv(all_gene_csv, full_path_csv, row.names=FALSE)

```







```{r}
number_of_fca<-c("1","4","5","6","7","8","9","10","11","12","13","14","15")
names_of_fca<-paste("FCA",number_of_fca,sep="")

#threshold_values<-c(0.36,0.3,0.18,0.05,0.16,0.33,0.57)
gene_names<-c("Syt1","elav","brp","ple","NPF","NPFR","Tdc2","Crz","Tbh","fru")

fullname<-paste("s_",gene_names,sep="")


SERUAT_HEAD@meta.data$s_ple<-""
SERUAT_HEAD@meta.data$s_NPF<-""
SERUAT_HEAD@meta.data$s_Tdc2<-""
SERUAT_HEAD@meta.data$s_Crz<-""
SERUAT_HEAD@meta.data$s_Tbh<-""
SERUAT_HEAD@meta.data$s_fru<-""
SERUAT_HEAD@meta.data$s_Syt1<-""
SERUAT_HEAD@meta.data$s_brp<-""
SERUAT_HEAD@meta.data$s_elav<-""

```





threshold of 0
```{r}
#SERUAT_HEAD <-readRDS("D:/seq_data/FCA/elav.rds")

SERUAT_HEAD <-readRDS("D:/Lital/15_10_elav_pos_ok107_all_genes.rds")

number_of_fca<-c("1","4","5","6","7","8","9","10","11","12","13","14","15")
names_of_fca<-paste("FCA",number_of_fca,sep="")

#threshold_values<-c(0.36,0.3,0.18,0.05,0.16,0.33,0.57)
gene_names<-c("Syt1","elav","brp","ple","NPF","NPFR","Tdc2","Crz","Tbh","fru")

fullname<-paste("s_",gene_names,sep="")


SERUAT_HEAD@meta.data$s_ple<-""
SERUAT_HEAD@meta.data$s_NPF<-""
SERUAT_HEAD@meta.data$s_Tdc2<-""
SERUAT_HEAD@meta.data$s_Crz<-""
SERUAT_HEAD@meta.data$s_Tbh<-""
SERUAT_HEAD@meta.data$s_fru<-""
SERUAT_HEAD@meta.data$s_Syt1<-""
SERUAT_HEAD@meta.data$s_brp<-""
SERUAT_HEAD@meta.data$s_elav<-""


all_gene_csv<-as.data.frame(read.csv("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/threshold/all_genes.csv"))
 
for(gene_i in 1:length(gene_names)){

for(fca_i in 1:length(names_of_fca)){
FCA_LIST<- all_gene_csv[all_gene_csv$FCA %in% names_of_fca[fca_i],]

current_value_threshold<- FCA_LIST[FCA_LIST$Gene %in% gene_names[[gene_i]],]$value


SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],fullname[gene_i]]<-c(SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],gene_names[[gene_i]]] >current_value_threshold)

  
}
}


SERUAT_HEAD@meta.data$names<-""


for(i in 1:nrow(SERUAT_HEAD@meta.data)){

    if(SERUAT_HEAD@meta.data$s_Tdc2[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tdc2")

    }
}
table(SERUAT_HEAD@meta.data$names)


for(i in 1:nrow(SERUAT_HEAD@meta.data)){

    if(SERUAT_HEAD@meta.data$s_ple[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"ple")

    }

    if(SERUAT_HEAD@meta.data$s_NPF[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPF")

    }
    if(SERUAT_HEAD@meta.data$s_NPFR[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPFR")

    }
    if(SERUAT_HEAD@meta.data$s_Tdc2[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tdc2")

    }
      if(SERUAT_HEAD@meta.data$s_Crz[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Crz")

      }
      if(SERUAT_HEAD@meta.data$s_Tbh[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tbh")

      }
        if(SERUAT_HEAD@meta.data$s_fru[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"fru")

        }
            if(grepl("Kenyon cell",SERUAT_HEAD@meta.data$tissu[i])){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"OK107")

            }
  

}


```

```{r}

SERUAT_HEAD <-readRDS("D:/Lital/15_10_elav_pos_ok107_all_genes.rds")


SERUAT_HEAD@meta.data$names<-""


for(i in 1:nrow(SERUAT_HEAD@meta.data)){

    if(SERUAT_HEAD@meta.data$s_Tdc2[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tdc2")

    }
}
table(SERUAT_HEAD@meta.data$names)

Idents(object = SERUAT_HEAD) <- SERUAT_HEAD@meta.data$names


my_cols<- c(DiscretePalette(2 ,palette = "glasbey"))
my_cols[1]<-"#C0C0C0"
my_cols[2]<-"#ff0000"


names(my_cols)<-names(table(SERUAT_HEAD@meta.data$names))


  plotname<-paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/30.10.23/all_data_tdc2.tiff")
 tiff(file=plotname,units="in",height=15,width=15,res=600)

 DimPlot(object = SERUAT_HEAD,label.size
 =3.5,cols = my_cols)



dev.off()



t<-SplitObject(SERUAT_HEAD, split.by = "names")

tdc2<-t[[" Tdc2"]]
all_other_elav_n_tdc2<-t[[1]]


all.genes_head<-as.data.frame(rownames(SERUAT_HEAD))

# gene_names<-c("mGluR","Vmat","VGlut","Octalpha2R","Oamb","Rdl","GABA-B-R1","GABA-B-R3","GABA-B-R2")
# 
# FeaturePlot(tdc2, features = gene_names)s


  plotname<-paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/30.10.23/all_others_genes.tiff")
 tiff(file=plotname,units="in",height=15,width=15,res=600)


gene_names<-c("mGluR","Vmat","VGlut","Octalpha2R","Oamb","Rdl","GABA-B-R1","GABA-B-R3","GABA-B-R2")

FeaturePlot(all_other_elav_n_tdc2, features = gene_names)



dev.off()


```



```{r}
all_gene_csv<-as.data.frame(read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/threshold/all_genes.csv"))
 
for(gene_i in 1:length(gene_names)){

for(fca_i in 1:length(names_of_fca)){
FCA_LIST<- all_gene_csv[all_gene_csv$FCA %in% names_of_fca[fca_i],]

current_value_threshold<- FCA_LIST[FCA_LIST$Gene %in% gene_names[[gene_i]],]$value


SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],fullname[gene_i]]<-c(SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],gene_names[[gene_i]]] >current_value_threshold)

  
}
}


SERUAT_HEAD@meta.data$names<-""




# for(i in 1:nrow(SERUAT_HEAD@meta.data)){
#       if(SERUAT_HEAD@meta.data$s_elav[i] == TRUE){
#     SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"elav")
# 
#   }
# }


# for(i in 1:nrow(SERUAT_HEAD@meta.data)){
#   if(SERUAT_HEAD@meta.data$s_Syt1[i] == TRUE){
#     SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Syt1")
# 
#   }
#     if(SERUAT_HEAD@meta.data$s_brp[i] == TRUE){
#     SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"brp")
# 
#     }
#       if(SERUAT_HEAD@meta.data$s_elav[i] == TRUE){
#     SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"elav")
# 
#       }
# }

#SERUAT_HEAD<-sub_seted




for(i in 1:nrow(SERUAT_HEAD@meta.data)){
  # if(SERUAT_HEAD@meta.data$s_Syt1[i] == TRUE){
  #   SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Syt1")
  # 
  # }
  #   if(SERUAT_HEAD@meta.data$s_brp[i] == TRUE){
  #   SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"brp")
  # 
  #   }
  #     if(SERUAT_HEAD@meta.data$s_elav[i] == TRUE){
  #   SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"elav")
  # 
  #     }
    if(SERUAT_HEAD@meta.data$s_ple[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"ple")

  }
    if(SERUAT_HEAD@meta.data$s_NPF[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPF")

    }
    if(SERUAT_HEAD@meta.data$s_NPFR[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPFR")

    }
    if(SERUAT_HEAD@meta.data$s_Tdc2[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tdc2")

    }
      if(SERUAT_HEAD@meta.data$s_Crz[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Crz")

      }
      if(SERUAT_HEAD@meta.data$s_Tbh[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tbh")

      }
        if(SERUAT_HEAD@meta.data$s_fru[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"fru")

        }
            if(grepl("Kenyon cell",SERUAT_HEAD@meta.data$tissu[i])){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"OK107")

            }
  

}




# plotname<-"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/threshold/elav_pos_100.tiff"
# 
# tiff(file=plotname,units="in",height=13,width=18,res=600)
# 
# Idents(object = SERUAT_HEAD) <- SERUAT_HEAD@meta.data$names


# t<-SplitObject(glu, split.by = "names")
# # label=TRUE
# elav<-DimPlot(object = t[[" elav"]],label.size
# =3.5,pt.size = 1.5,cols ="white")


# DimPlot(object = SERUAT_HEAD,label.size
# =3.5,pt.size = 1.5)


# gene_names<-c("ple","NPF","NPFR","Tdc2","Crz","Tbh","fru","OK107")
# 
# FeaturePlot(SERUAT_HEAD, features = gene_names)
# 
# dev.off()


table(SERUAT_HEAD@meta.data$names)



 saveRDS(SERUAT_HEAD,"D:/seq_data/FCA/15_10_elav_pos_ok107_all_genes.rds")

```

```{r}
list_of_gene<-c(" ple"," NPFR"," fru"," Tdc2"," NPF"," Crz"," Tbh"," OK107")




Idents(object = SERUAT_HEAD) <- SERUAT_HEAD@meta.data$names



#par(mfrow = c(3, 3),mar = c(2.1, 3, 9, 3),xaxs = "i",yaxs = "i",cex.axis=1.1,cex.lab=1.1)
list_of_gene_names<-names(table(SERUAT_HEAD@meta.data$names))
#list_of_gene_names<-list_of_gene
  num_of_genes<-length(table(SERUAT_HEAD@meta.data$names))




for(gene in 2:length(list_of_gene_names)){
  Main_gene<-list_of_gene_names[gene]
  
  half_num_genes<-(num_of_genes)
  
my_cols<- c(DiscretePalette(half_num_genes ,palette = "glasbey"))
my_cols[1]<-"#C0C0C0"
names(my_cols)<-list_of_gene_names



my_plot_order_names<-c()
the_last_to_plot_names<-c()



  for(i in 2:num_of_genes){
    if(!(Main_gene == list_of_gene_names[i])){
      my_plot_order_names<-c(my_plot_order_names,list_of_gene_names[i])
      my_cols[list_of_gene_names[i]]<-"#C0C0C0"
      print(i)
    }else{
      the_last_to_plot_names<-c(the_last_to_plot_names,list_of_gene_names[i])
      print("here")
      my_cols[list_of_gene_names[i]]<-"#FF0000"

    }
  }
Main_gene<-trimws(Main_gene)


   plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/threshold/",Main_gene,".tiff")
  
 tiff(file=plotname,units="in",height=11,width=11,res=600)

t<-DimPlot(object = SERUAT_HEAD,cols = my_cols,label=FALSE,pt.size = 1,order =the_last_to_plot_names ) +ggtitle(Main_gene)+ theme(plot.title = element_text(hjust = 0.5,size = 20, face = "bold"),legend.position="none")
plot(t)
#plot(t,xaxt = "n")
dev.off()

}
```

```{r}
library(ggplot2)
all_gene_csv<-read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/threshold/all_genes.csv")


all_gene_csv$value<-as.numeric(all_gene_csv$value)


#path_of_photos<-"C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/30.4.23/"


plotname<-"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/threshold/threshold.tiff"

tiff(file=plotname,units="in",height=13,width=18,res=600)

#dittoHeatmap(TEST,top20$gene,annot.by = "names")

ggplot(all_gene_csv, aes( x=Gene, y=value, fill = Gene)) +
    geom_boxplot(outlier.shape = NA) +
  geom_jitter(aes(colour  = as.factor(FCA)))


  #  dittoHeatmap(TEST,top10$gene,annot.by = "names",show_colnames = FALSE,show_rownames = TRUE)

dev.off()



#colnames(all_gene_csv)<-c("value","FCA","Gene")

```




```{r}

head_FCA_sum_for_visual<-function(gene_name,FCA){
  
  #remmber to rename the path to the username of he computer
  #plotname<-paste("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/27.2.23/",gene_name,"/",NUMBER_OF_FCA,".tiff",sep = "")
  precnt_name<-paste("percent.",gene_name,sep="")
  FCA[[precnt_name]] <- PercentageFeatureSet(FCA,features =gene_name)
  
  gene_head<-as.data.frame(get(precnt_name,FCA@meta.data))
  colnames(gene_head)<-"head"
  
  
  #gene_head_density <- hist(gene_head$head, breaks=seq(0,10,l=1000),plot = FALSE)         # Store output of hist function
  #gene_head_density$density <- gene_head_density$counts /    # Compute density values
  # sum(gene_head_density$counts) * 100
  
  
  gene_sum_head <- hist(gene_head$head, breaks=seq(0,10,l=10000),plot = FALSE)                       # Store histogram info
  gene_sum_head$counts <- revcumsum((gene_sum_head$counts)) 
  
  return(gene_sum_head)
}



library(spatstat.utils)
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)


SERUAT_HEAD <-readRDS("D:/Lital/15_10_elav_pos_ok107_all_genes.rds")


new<-SplitObject(SERUAT_HEAD, split.by = "identity")



expceted_cell_num<-c(515,100,1454,265,40,300,265)

top_x_value<-c(0.5,0.5,0.5,0.5,0.8,0.5,0.5)

# list_of_freq<-c(20)
# list_of_xlimit<-c(2)
list_of_gene<-c("ple","NPFR","fru","Tdc2","NPF","Crz","Tbh")


#list_of_gene<-c("Crz")
#expceted_cell_num<-c(300)

#path_of_photos<-"C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/27.2.23/"

path_of_photos<-"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/threshold/hist/"
#gene<-"ple"
#expceted_cell_num<-515





number_of_fca<-c("1","4","5","6","7","8","9","10","11","12","13","14","15")
names_of_fca<-paste("FCA",number_of_fca,sep="")


for(i in 1:length(list_of_gene)){
  
  plotname<-paste(path_of_photos,"_gene_name_",list_of_gene[i],".tiff",sep = "")
  tiff(file=plotname,units="in",height=15,width=20,res=600)
  par(mfrow = c(5, 3),mar = c(2.1, 3, 9, 3),xaxs = "i",yaxs = "i",cex.axis=1.1,cex.lab=1.1)
  for(j in 1:length(new)){
  y_Vale_max_origin<-round((expceted_cell_num[i]*ncol(new[[j]]))/100000) # to find how many sample suppose to be

  current_FCA<-new[[j]]
 # main_title <-paste(current_gene)
  current_FCA_hist<-head_FCA_sum_for_visual(list_of_gene[i],current_FCA)
  

  
   # main_title <-paste("cumilative garph in ",NUMBER_OF_FCA,"need to be " ,y_value," cells of ",gene_name)
  new_yval<-y_Vale_max_origin + 0.5*(y_Vale_max_origin)
  
  
  exp_per_counts<-current_FCA_hist[["breaks"]][max(which(current_FCA_hist[["counts"]] > y_Vale_max_origin))]
  
  plot(current_FCA_hist,col=alpha('red',0.5), main=paste(names_of_fca[j],"expected cell is ",y_Vale_max_origin), xlab='% expression',ylab='number of cells',ylim =c(0,new_yval),xlim =rev(c(0, top_x_value[i])),cex.axis=2.2,cex.lab=1.5, cex.main=2,xaxt = "n")
  abline(h = y_Vale_max_origin, col = "darkgreen")
  abline(v =exp_per_counts, col = "blue") 
  axis(1, at = rev(seq(0,top_x_value[i], by = 0.01)),
       labels = rev(seq(0,top_x_value[i], by = 0.01)))
  
   title_<-paste(list_of_gene[i])
  #dev.off()
  mtext(title_, side = 3, line =-3, outer = TRUE ,cex=2)
}
  dev.off()
}


```




```{r}

library(spatstat.utils)
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)


SERUAT_HEAD <-readRDS("D:/Lital/15_10_elav_pos_ok107_all_genes.rds")

number_of_fca<-c("1","4","5","6","7","8","9","10","11","12","13","14","15")
names_of_fca<-paste("FCA",number_of_fca,sep="")

#threshold_values<-c(0.36,0.3,0.18,0.05,0.16,0.33,0.57)
gene_names<-c("Syt1","elav","brp","ple","NPF","NPFR","Tdc2","Crz","Tbh","fru")

fullname<-paste("s_",gene_names,sep="")


SERUAT_HEAD@meta.data$s_ple<-""
SERUAT_HEAD@meta.data$s_NPF<-""
SERUAT_HEAD@meta.data$s_Tdc2<-""
SERUAT_HEAD@meta.data$s_Crz<-""
SERUAT_HEAD@meta.data$s_Tbh<-""
SERUAT_HEAD@meta.data$s_fru<-""
SERUAT_HEAD@meta.data$s_Syt1<-""
SERUAT_HEAD@meta.data$s_brp<-""
SERUAT_HEAD@meta.data$s_elav<-""


all_gene_csv<-as.data.frame(read.csv("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/threshold/all_genes.csv"))
 
for(gene_i in 1:length(gene_names)){

for(fca_i in 1:length(names_of_fca)){
FCA_LIST<- all_gene_csv[all_gene_csv$FCA %in% names_of_fca[fca_i],]

current_value_threshold<- FCA_LIST[FCA_LIST$Gene %in% gene_names[[gene_i]],]$value


SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],fullname[gene_i]]<-c(SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],gene_names[[gene_i]]] >current_value_threshold)

  
}
}


SERUAT_HEAD@meta.data$names<-""


for(i in 1:nrow(SERUAT_HEAD@meta.data)){

    if(SERUAT_HEAD@meta.data$s_Tdc2[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tdc2")

    }
}


Idents(object = SERUAT_HEAD) <- SERUAT_HEAD@meta.data$names


SERUAT_Antena<-SERUAT_HEAD
SERUAT_Antena <- NormalizeData(object = SERUAT_Antena)
SERUAT_Antena <- FindVariableFeatures(object = SERUAT_Antena)
SERUAT_Antena <- ScaleData(object = SERUAT_Antena)
SERUAT_Antena <- RunPCA(object = SERUAT_Antena)
ElbowPlot(SERUAT_Antena)
SERUAT_Antena <- FindNeighbors(object = SERUAT_Antena, dims = 1:20)
SERUAT_Antena <- FindClusters(object = SERUAT_Antena)
SERUAT_Antena <- RunUMAP(object = SERUAT_Antena, dims = 1:20)

SERUAT_HEAD<-SERUAT_Antena


Idents(object = SERUAT_HEAD) <- SERUAT_HEAD@meta.data$seurat_clusters


list_of_gene_names<-names(table(SERUAT_HEAD@meta.data$seurat_clusters))


my_cols<- c(DiscretePalette(length(list_of_gene_names) ,palette = "glasbey"))
my_cols[1]<-"#C0C0C0"
names(my_cols)<-list_of_gene_names



 plotname<- paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/final_outline/last_analysis/Tdc2.tiff")
 tiff(file=plotname,units="in",height=20,width=20,res=600)
 
DimPlot(SERUAT_HEAD, reduction = 'umap',raster=FALSE,cols = my_cols)

dev.off()





for(i in 1:nrow(SERUAT_HEAD@meta.data)){

    if(SERUAT_HEAD@meta.data$s_ple[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"ple")

    }

    if(SERUAT_HEAD@meta.data$s_NPF[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPF")

    }
    if(SERUAT_HEAD@meta.data$s_NPFR[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPFR")

    }
    if(SERUAT_HEAD@meta.data$s_Tdc2[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tdc2")

    }
      if(SERUAT_HEAD@meta.data$s_Crz[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Crz")

      }
      if(SERUAT_HEAD@meta.data$s_Tbh[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tbh")

      }
        if(SERUAT_HEAD@meta.data$s_fru[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"fru")

        }
            if(grepl("Kenyon cell",SERUAT_HEAD@meta.data$tissu[i])){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"OK107")

            }
  

}

```



```{r}
SERUAT_HEAD <-readRDS("/home/alu/aluguest/Lital_galitLab/15_10_elav_pos_ok107_all_genes.rds")

number_of_fca<-c("1","4","5","6","7","8","9","10","11","12","13","14","15")
names_of_fca<-paste("FCA",number_of_fca,sep="")

#threshold_values<-c(0.36,0.3,0.18,0.05,0.16,0.33,0.57)
gene_names<-c("Syt1","elav","brp","ple","NPF","NPFR","Tdc2","Crz","Tbh","fru")

fullname<-paste("s_",gene_names,sep="")


SERUAT_HEAD@meta.data$s_ple<-""
SERUAT_HEAD@meta.data$s_NPF<-""
SERUAT_HEAD@meta.data$s_Tdc2<-""
SERUAT_HEAD@meta.data$s_Crz<-""
SERUAT_HEAD@meta.data$s_Tbh<-""
SERUAT_HEAD@meta.data$s_fru<-""
SERUAT_HEAD@meta.data$s_Syt1<-""
SERUAT_HEAD@meta.data$s_brp<-""
SERUAT_HEAD@meta.data$s_elav<-""


all_gene_csv<-as.data.frame(read.csv("/home/alu/aluguest/Lital_galitLab/all_genes.csv"))
 
for(gene_i in 1:length(gene_names)){

for(fca_i in 1:length(names_of_fca)){
FCA_LIST<- all_gene_csv[all_gene_csv$FCA %in% names_of_fca[fca_i],]

current_value_threshold<- FCA_LIST[FCA_LIST$Gene %in% gene_names[[gene_i]],]$value


SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],fullname[gene_i]]<-c(SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],gene_names[[gene_i]]] >current_value_threshold)

  
}
}




SERUAT_HEAD@meta.data$names<-""

gene_name<-"fru"

for(i in 1:nrow(SERUAT_HEAD@meta.data)){

        if(SERUAT_HEAD@meta.data$s_fru[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"fru")

        }
}


Idents(object = SERUAT_HEAD) <- SERUAT_HEAD@meta.data$names

new<-SplitObject(SERUAT_HEAD, split.by = "names")

SERUAT_Antena<-new[[2]]
#SERUAT_Antena<-SERUAT_HEAD
SERUAT_Antena <- NormalizeData(object = SERUAT_Antena)
SERUAT_Antena <- FindVariableFeatures(object = SERUAT_Antena)
SERUAT_Antena <- ScaleData(object = SERUAT_Antena)
SERUAT_Antena <- RunPCA(object = SERUAT_Antena)
ElbowPlot(SERUAT_Antena)
SERUAT_Antena <- FindNeighbors(object = SERUAT_Antena, dims = 1:10)
SERUAT_Antena <- FindClusters(object = SERUAT_Antena)
SERUAT_Antena <- RunUMAP(object = SERUAT_Antena, dims = 1:10)

SERUAT_HEAD<-SERUAT_Antena


Idents(object = SERUAT_HEAD) <- SERUAT_HEAD@meta.data$seurat_clusters


list_of_gene_names<-names(table(SERUAT_HEAD@meta.data$seurat_clusters))


my_cols<- c(DiscretePalette(length(list_of_gene_names) ,palette = "glasbey"))
my_cols[1]<-"#C0C0C0"
names(my_cols)<-list_of_gene_names
if(length(list_of_gene_names)>3){
  
  my_cols[3]<-"#0000FF"

}


 plotname<- paste0("/home/alu/aluguest/Lital_galitLab/",gene_name,".tiff")
 tiff(file=plotname,units="in",height=20,width=20,res=600)
 
DimPlot(SERUAT_HEAD, reduction = 'umap',raster=FALSE,cols = my_cols,pt.size
=1.7)

dev.off()





markers <- FindAllMarkers(SERUAT_HEAD,logfc.threshold = 1,only.pos = TRUE)
markers<-subset(markers,p_val_adj<0.05)


write.csv(markers,paste0("/home/alu/aluguest/Lital_galitLab/sig_",gene_name,".csv"))





for(i in 1:nrow(SERUAT_HEAD@meta.data)){




    if(SERUAT_HEAD@meta.data$s_Tdc2[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tdc2")

    }
      if(SERUAT_HEAD@meta.data$s_Crz[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Crz")

      }
      if(SERUAT_HEAD@meta.data$s_Tbh[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tbh")

      }
        if(SERUAT_HEAD@meta.data$s_fru[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"fru")

        }
            if(grepl("Kenyon cell",SERUAT_HEAD@meta.data$tissu[i])){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"OK107")

            }
  

}

```




original no threshold
```{r}

library(spatstat.utils)
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)
library(tidyr)
SERUAT_HEAD <-readRDS("D:/seq_data/FCA/seuruat_head5_12.rds")



SERUAT_HEAD@meta.data$Syt1<- FetchData(SERUAT_HEAD, vars = "Syt1")


SERUAT_HEAD@meta.data$elav<- FetchData(SERUAT_HEAD, vars = "elav")
SERUAT_HEAD@meta.data$brp<- FetchData(SERUAT_HEAD, vars = "brp")

SERUAT_HEAD@meta.data$NPF<- FetchData(SERUAT_HEAD, vars = "NPF")

SERUAT_HEAD@meta.data$ple<- FetchData(SERUAT_HEAD, vars = "ple")
SERUAT_HEAD@meta.data$NPFR<- FetchData(SERUAT_HEAD, vars = "NPFR")
SERUAT_HEAD@meta.data$Tdc2<- FetchData(SERUAT_HEAD, vars = "Tdc2")
SERUAT_HEAD@meta.data$Crz<- FetchData(SERUAT_HEAD, vars = "Crz")

SERUAT_HEAD@meta.data$Tbh<- FetchData(SERUAT_HEAD, vars = "Tbh")
SERUAT_HEAD@meta.data$fru<- FetchData(SERUAT_HEAD, vars = "fru")
SERUAT_HEAD$sample <- rownames(SERUAT_HEAD@meta.data)

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "__", "_")

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "-", "_")

View(SERUAT_HEAD@meta.data)
SERUAT_HEAD@meta.data <- separate(SERUAT_HEAD@meta.data, col = 'sample', into = c("test",'Barcode','identity', 'Sex'),
                                  sep = '_')


number_of_fca<-c("1","4","5","6","7","8","9","10","11","12","13","14","15")
names_of_fca<-paste("FCA",number_of_fca,sep="")

#threshold_values<-c(0.36,0.3,0.18,0.05,0.16,0.33,0.57)
gene_names<-c("Syt1","elav","brp","ple","NPF","NPFR","Tdc2","Crz","Tbh","fru")

fullname<-paste("s_",gene_names,sep="")


SERUAT_HEAD@meta.data$s_ple<-""
SERUAT_HEAD@meta.data$s_NPF<-""
SERUAT_HEAD@meta.data$s_Tdc2<-""
SERUAT_HEAD@meta.data$s_Crz<-""
SERUAT_HEAD@meta.data$s_Tbh<-""
SERUAT_HEAD@meta.data$s_fru<-""
SERUAT_HEAD@meta.data$s_Syt1<-""
SERUAT_HEAD@meta.data$s_brp<-""
SERUAT_HEAD@meta.data$s_elav<-""


all_gene_csv<-as.data.frame(read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/threshold/all_genes_zero.csv"))
 
for(gene_i in 1:length(gene_names)){

for(fca_i in 1:length(names_of_fca)){
FCA_LIST<- all_gene_csv[all_gene_csv$FCA %in% names_of_fca[fca_i],]

current_value_threshold<- FCA_LIST[FCA_LIST$Gene %in% gene_names[[gene_i]],]$value
#current_value_threshold<-0

SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],fullname[gene_i]]<-c(SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],gene_names[[gene_i]]] >current_value_threshold)

  
}
}




for(j in 1:8){
  
  SERUAT_HEAD@meta.data$names<-""
  
   if(j == 1) {
       SERUAT_HEAD@meta.data$names<-""

     for(i in 1:nrow(SERUAT_HEAD@meta.data)){

              if(SERUAT_HEAD@meta.data$s_fru[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"fru")

              }
     }
     table(SERUAT_HEAD@meta.data$names)

  }
  if(j == 2){
      SERUAT_HEAD@meta.data$names<-""

    for(i in 1:nrow(SERUAT_HEAD@meta.data)){

          if(SERUAT_HEAD@meta.data$s_Tbh[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tbh")

          }
    }
    table(SERUAT_HEAD@meta.data$names)

  }

  if(j == 3){
      SERUAT_HEAD@meta.data$names<-""

    for(i in 1:nrow(SERUAT_HEAD@meta.data)){

        if(SERUAT_HEAD@meta.data$s_ple[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"ple")

        }
    }
    table(SERUAT_HEAD@meta.data$names)

  }
  if(j == 4){
      SERUAT_HEAD@meta.data$names<-""

    for(i in 1:nrow(SERUAT_HEAD@meta.data)){

          if(SERUAT_HEAD@meta.data$s_Crz[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Crz")

          }
    }
    table(SERUAT_HEAD@meta.data$names)

  }
  if(j == 5 ){
      SERUAT_HEAD@meta.data$names<-""

    for(i in 1:nrow(SERUAT_HEAD@meta.data)){

        if(SERUAT_HEAD@meta.data$s_NPFR[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPFR")

        }
    }
    table(SERUAT_HEAD@meta.data$names)

  }
  
  if( j == 6){
      SERUAT_HEAD@meta.data$names<-""

    for(i in 1:nrow(SERUAT_HEAD@meta.data)){

        if(SERUAT_HEAD@meta.data$s_Tdc2[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tdc2")

        }
    }
    table(SERUAT_HEAD@meta.data$names)

  }

  if(j== 7){
      SERUAT_HEAD@meta.data$names<-""

    for(i in 1:nrow(SERUAT_HEAD@meta.data)){

    if(SERUAT_HEAD@meta.data$s_NPF[i] == TRUE){
SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPF")

    }
    }
    table(SERUAT_HEAD@meta.data$names)

  }
  
    if(j== 8){
      SERUAT_HEAD@meta.data$names<-""

    for(i in 1:nrow(SERUAT_HEAD@meta.data)){

             if(grepl("Kenyon cell",SERUAT_HEAD@meta.data$tissu[i])){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"OK107")

            }
    }
    table(SERUAT_HEAD@meta.data$names)

  }
  
  



  

}


#tmp_head<-SERUAT_HEAD
# SERUAT_HEAD@meta.data$names<-""
# 
# 
# 
# #gene_name<-"NPF"
# 
# for(i in 1:nrow(SERUAT_HEAD@meta.data)){
# 
#     if(SERUAT_HEAD@meta.data$s_NPF[i] == TRUE){
# SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPF")
# 
#       }
#   
# 
# }
# 
# 
# 
# #Idents(object = SERUAT_HEAD) <- SERUAT_HEAD@meta.data$names
# 
# table(SERUAT_HEAD@meta.data$names)
# list_of_gene_names<-names(table(SERUAT_HEAD@meta.data$names))
# 
# 
# my_cols<- c(DiscretePalette(length(list_of_gene_names) ,palette = "glasbey"))
# my_cols[1]<-"#C0C0C0"
# my_cols[2]<-"#FF0000"
# names(my_cols)<-list_of_gene_names
# 
# 
#  plotname<- paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/threshold/NO_CROSS/with_threshold/",gene_name,".tiff")
#  tiff(file=plotname,units="in",height=20,width=20,res=600)
#  
# DimPlot(SERUAT_HEAD, reduction = 'umap',raster=FALSE,cols = my_cols,pt.size
# =1.7)
# 
# dev.off()


 if(j == 1) {
              if(SERUAT_HEAD@meta.data$s_fru[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"fru")

        }
  }
  if(j == 2){
          if(SERUAT_HEAD@meta.data$s_Tbh[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tbh")

      }
  }

  if(j == 3){
        if(SERUAT_HEAD@meta.data$s_ple[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"ple")

}
  }
  if(j == 4){
    
          if(SERUAT_HEAD@meta.data$s_Crz[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Crz")

      }
  }
  if(j == 5 ){
    
        if(SERUAT_HEAD@meta.data$s_NPFR[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPFR")

    }
  }
  
  if( j == 6){
        if(SERUAT_HEAD@meta.data$s_Tdc2[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tdc2")

    }
  }

  if(j== 7){
    if(SERUAT_HEAD@meta.data$s_NPF[i] == TRUE){
SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPF")

      }
  }



```


```{r}

library(spatstat.utils)
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)
library(tidyr)
SERUAT_HEAD <-readRDS("D:/seq_data/FCA/15_10_elav_pos_ok107_all_genes.rds")





number_of_fca<-c("1","4","5","6","7","8","9","10","11","12","13","14","15")
names_of_fca<-paste("FCA",number_of_fca,sep="")

#threshold_values<-c(0.36,0.3,0.18,0.05,0.16,0.33,0.57)
gene_names<-c("Syt1","elav","brp","ple","NPF","NPFR","Tdc2","Crz","Tbh","fru")

fullname<-paste("s_",gene_names,sep="")


SERUAT_HEAD@meta.data$s_ple<-""
SERUAT_HEAD@meta.data$s_NPF<-""
SERUAT_HEAD@meta.data$s_Tdc2<-""
SERUAT_HEAD@meta.data$s_Crz<-""
SERUAT_HEAD@meta.data$s_Tbh<-""
SERUAT_HEAD@meta.data$s_fru<-""
SERUAT_HEAD@meta.data$s_Syt1<-""
SERUAT_HEAD@meta.data$s_brp<-""
SERUAT_HEAD@meta.data$s_elav<-""


all_gene_csv<-as.data.frame(read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/threshold/all_genes.csv"))
 
for(gene_i in 1:length(gene_names)){

for(fca_i in 1:length(names_of_fca)){
FCA_LIST<- all_gene_csv[all_gene_csv$FCA %in% names_of_fca[fca_i],]

current_value_threshold<- FCA_LIST[FCA_LIST$Gene %in% gene_names[[gene_i]],]$value
#current_value_threshold<-0

SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],fullname[gene_i]]<-c(SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],gene_names[[gene_i]]] >current_value_threshold)

  
}
}



#tmp_head<-SERUAT_HEAD
# SERUAT_HEAD@meta.data$names<-""
# 
# gene_name<-"NPF"
# 
# for(i in 1:nrow(SERUAT_HEAD@meta.data)){
# 
#     if(SERUAT_HEAD@meta.data$s_NPF[i] == TRUE){
# SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPF")
# 
#       }
#   
# 
# }

for(j in 1:8){
  
 # SERUAT_HEAD@meta.data$names<-""
  
   if(j == 1) {
       SERUAT_HEAD@meta.data$names<-""

     for(i in 1:nrow(SERUAT_HEAD@meta.data)){

              if(SERUAT_HEAD@meta.data$s_fru[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"fru")

              }
     }
     table(SERUAT_HEAD@meta.data$names)

  }
  if(j == 2){
      SERUAT_HEAD@meta.data$names<-""

    for(i in 1:nrow(SERUAT_HEAD@meta.data)){

          if(SERUAT_HEAD@meta.data$s_Tbh[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tbh")

          }
    }
    table(SERUAT_HEAD@meta.data$names)

  }

  if(j == 3){
      SERUAT_HEAD@meta.data$names<-""

    for(i in 1:nrow(SERUAT_HEAD@meta.data)){

        if(SERUAT_HEAD@meta.data$s_ple[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"ple")

        }
    }
    table(SERUAT_HEAD@meta.data$names)

  }
  if(j == 4){
      SERUAT_HEAD@meta.data$names<-""

    for(i in 1:nrow(SERUAT_HEAD@meta.data)){

          if(SERUAT_HEAD@meta.data$s_Crz[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Crz")

          }
    }
    table(SERUAT_HEAD@meta.data$names)

  }
  if(j == 5 ){
      SERUAT_HEAD@meta.data$names<-""

    for(i in 1:nrow(SERUAT_HEAD@meta.data)){

        if(SERUAT_HEAD@meta.data$s_NPFR[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPFR")

        }
    }
    table(SERUAT_HEAD@meta.data$names)

  }
  
  if( j == 6){
      SERUAT_HEAD@meta.data$names<-""

    for(i in 1:nrow(SERUAT_HEAD@meta.data)){

        if(SERUAT_HEAD@meta.data$s_Tdc2[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tdc2")

        }
    }
    table(SERUAT_HEAD@meta.data$names)

  }

  if(j== 7){
      SERUAT_HEAD@meta.data$names<-""

    for(i in 1:nrow(SERUAT_HEAD@meta.data)){

    if(SERUAT_HEAD@meta.data$s_NPF[i] == TRUE){
SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPF")

    }
    }
    table(SERUAT_HEAD@meta.data$names)

  }
  
    if(j== 8){
      SERUAT_HEAD@meta.data$names<-""

    for(i in 1:nrow(SERUAT_HEAD@meta.data)){

             if(grepl("Kenyon cell",SERUAT_HEAD@meta.data$tissu[i])){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"OK107")

            }
    }
    table(SERUAT_HEAD@meta.data$names)

  }
  
  



  

}




Idents(object = SERUAT_HEAD) <- SERUAT_HEAD@meta.data$names


list_of_gene_names<-names(table(SERUAT_HEAD@meta.data$names))


my_cols<- c(DiscretePalette(length(list_of_gene_names) ,palette = "glasbey"))
my_cols[1]<-"#C0C0C0"
my_cols[2]<-"#FF0000"
names(my_cols)<-list_of_gene_names


 plotname<- paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/threshold/NO_CROSS/with_threshold/",gene_name,".tiff")
 tiff(file=plotname,units="in",height=20,width=20,res=600)
 
DimPlot(SERUAT_HEAD, reduction = 'umap',raster=FALSE,cols = my_cols,pt.size
=1.7)

dev.off()
```




```{r}
 if(j == 1) {
              if(SERUAT_HEAD@meta.data$s_fru[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"fru")

        }
  }
  if(j == 2){
          if(SERUAT_HEAD@meta.data$s_Tbh[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tbh")

      }
  }

  if(j == 3){
        if(SERUAT_HEAD@meta.data$s_ple[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"ple")

}
  }
  if(j == 4){
    
          if(SERUAT_HEAD@meta.data$s_Crz[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Crz")

      }
  }
  if(j == 5 ){
    
        if(SERUAT_HEAD@meta.data$s_NPFR[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPFR")

    }
  }
  
  if( j == 6){
        if(SERUAT_HEAD@meta.data$s_Tdc2[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"Tdc2")

    }
  }

  if(j== 7){
    if(SERUAT_HEAD@meta.data$s_NPF[i] == TRUE){
SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"NPF")

      }
  }
```




bar plot
```{r}
 fru <- c(1454,50778)
barplot(fru,col = c("#1b98e0", "#353436"),
        beside = TRUE)


data <- as.matrix(data.frame(NPF = c(41,962),         # Create matrix for stacked barchart
                             NPFR = c(100, 3128),
                             OK107 = c(2000, 2071),
                             Crz = c(300, 1895),
                             Tdc2 = c(265,490),
                             ple = c(515,4509)))
rownames(data) <- c("known", "data set")
data




 plotname<- paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/final_outline/barplot_wo_fru.tiff")
 tiff(file=plotname,units="in",height=20,width=20,res=600)
 
barplot(data,                                         # Create grouped barchart
        col = c("#1b98e0", "#353436"),
        beside = TRUE,cex.axis=2)

legend("topleft",                                    # Add legend to barplot
       legend =  c("known", "data set"),
       fill = c("#1b98e0", "#353436"))

dev.off()



 plotname<- paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/final_outline/barplot_fru.tiff")
 tiff(file=plotname,units="in",height=20,width=20,res=600)
 fru <- c(1454,50778)
barplot(fru,col = c("#1b98e0", "#353436"),
        beside = TRUE)
dev.off()

```

