---
title: "Untitled"
author: "lital barak"
date: "2023-06-19"
output: html_document
---





```{r}
library(spatstat.utils)
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)



library(edgeR) # BiocManager::install("edgeR")
library(limma)
library(Seurat)
library(ggplot2)
library(dplyr)
library(ggplot2)
library(Matrix)
library(tidyr)
library(stringr)
library("gridExtra")
library(loomR)



#SERUAT_HEAD <-readRDS("D:/seq_data/FCA/seuruat_head30_4.rds")
 

SERUAT_HEAD <-readRDS("D:/seq_data/FCA/elav.rds")

# 
# SERUAT_HEAD$sample <- rownames(SERUAT_HEAD@meta.data)
# 
# SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "__", "_")
# 
# SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "-", "_")
# 
# View(SERUAT_HEAD@meta.data)
# SERUAT_HEAD@meta.data <- separate(SERUAT_HEAD@meta.data, col = 'sample', into = c("test",'Barcode','identity', 'Sex'), 
#                                   sep = '_')

new<-SplitObject(SERUAT_HEAD, split.by = "identity")


all.genes_head<-as.data.frame(rownames(SERUAT_HEAD))

head_FCA_sum<-function(gene_name,y_value,bottom_x_value,top_x_value,FCA,NUMBER_OF_FCA,path_of_photos,to_plot){
  
  #remmber to rename the path to the username of he computer
  plotname<- paste(path_of_photos,"/",NUMBER_OF_FCA,".tiff",sep = "")
  #plotname<-paste("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/27.2.23/",gene_name,"/",NUMBER_OF_FCA,".tiff",sep = "")
  
  #precnt_name<- paste(gene_name,"$",gene_name,sep="")

 # precnt_name<-paste("percent.",gene_name,sep="")
  #FCA[[precnt_name]] <- PercentageFeatureSet(FCA,features =gene_name)
  
  #gene_head<-as.data.frame(get(precnt_name,FCA@meta.data))
  gene_head<-as.data.frame(FCA@meta.data[[gene_name]])
  colnames(gene_head)<-"head"
  
  
  #gene_head_density <- hist(gene_head$head, breaks=seq(0,10,l=1000),plot = FALSE)         # Store output of hist function
  #gene_head_density$density <- gene_head_density$counts /    # Compute density values
  # sum(gene_head_density$counts) * 100
  
  
  gene_sum_head <- hist(gene_head$head, breaks=seq(0,20,l=20000),plot = FALSE)                       # Store histogram info
  gene_sum_head$counts <- revcumsum((gene_sum_head$counts)) 
  
  
  main_title <-paste("cumilative garph in ",NUMBER_OF_FCA,"need to be " ,y_value," cells of ",gene_name)

  new_yval<-y_value + 0.5*(y_value)
  
  
  exp_per_counts<-gene_sum_head[["breaks"]][max(which(gene_sum_head[["counts"]] > y_value))]
  
  if(to_plot == TRUE){
      tiff(file=plotname,units="in",height=13,width=18,res=600)
      t<-plot(gene_sum_head,col=alpha('red',0.5), main=main_title, xlab='% expression',ylab='number of cells',ylim =c(0,new_yval),xlim =rev(c(bottom_x_value, top_x_value)),cex.axis=2.2,cex.lab=1.5, cex.main=2,xaxt = "n")
  abline(h = y_value, col = "darkgreen")
  abline(v =exp_per_counts, col = "blue") 
  
  axis(1, at = rev(seq(bottom_x_value,top_x_value, by =
                         0.01)),
       labels = rev(seq(bottom_x_value,top_x_value, by = 0.01)))
  
  
  dev.off()
  }else{
      return(exp_per_counts)
      dev.off()

  }

}
```


```{r}

#max(which(gene_sum_head[["counts"]] > 4))

number_of_fca<-c("1","4","5","6","7","8","9","10","11","12","13","14","15")
names_of_fca<-paste("FCA",number_of_fca,sep="")

plot_or_not<-FALSE
path_of_photos<-"C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/18.6.23/"
#gene<-"ple"
#expceted_cell_num<-515


list_of_gene<-c("ple","NPFR","fru","Tdc2","NPF","Crz","Tbh")
list_of_expected_cells<-c(515,100,1454,265,40,300,265)

all_gene_csv<-NULL

for(i_gene in 1:length(list_of_gene)){
  
  
  gene<-list_of_gene[i_gene]
  expceted_cell_num<-list_of_expected_cells[i_gene]
  
  full_path_of_gene<-paste(path_of_photos,gene,"/",sep = "")

  to_csv<-NULL
if(dir.exists(full_path_of_gene)){
  for(i in 1:length(new)){
    #change to 47000 beacuse elav cells only
    y_Vale_max_origin<-round((expceted_cell_num*ncol(new[[i]]))/47000) # to find how many sample suppose to be
    #y_Vale_max<-y_Vale_max_origin + 0.5 *(y_Vale_max_origin)
   expression_level<- head_FCA_sum(gene,y_Vale_max_origin,0,5,new[[i]],names_of_fca[i],full_path_of_gene,plot_or_not)
      temp<-c(expression_level,names_of_fca[i],gene)
    to_csv<-rbind(to_csv,temp)
  }
}else{
  dir.create(full_path_of_gene)
  for(i in 1:length(new)){
    y_Vale_max_origin<-round((expceted_cell_num*ncol(new[[i]]))/47000) # to find how many sample suppose to be
    #y_Vale_max<-y_Vale_max_origin + 0.5 *(y_Vale_max_origin)
   expression_level<- head_FCA_sum(gene,y_Vale_max_origin,0,5,new[[i]],names_of_fca[i],full_path_of_gene,plot_or_not)
   
    temp<-c(expression_level,names_of_fca[i],gene)
    # colnames(temp)<-gene

    to_csv<-rbind(to_csv,temp)
  }
}

of_all<-head_FCA_sum(gene,expceted_cell_num,0,5,SERUAT_HEAD,"ALL",full_path_of_gene,plot_or_not)

temp<-c(of_all,"ALL",gene)
to_csv<-rbind(to_csv,temp)
  
to_csv<-as.data.frame(to_csv)


all_gene_csv<-rbind(all_gene_csv,to_csv)



  
}







full_path_csv<-paste(path_of_photos,"all_genes",".csv",sep = "")
colnames(all_gene_csv)<-c("value","FCA","Gene")
all_gene_csv$value<-as.numeric(all_gene_csv$value)
write.csv(all_gene_csv, full_path_csv, row.names=FALSE)

```

