---
title: "seruat"
output: html_document
date: "2022-11-16"
---

#packeges

```{r}

BiocManager::install("edgeR")
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("celldex")
install.packages("stringer")
BiocManager::install("dittoSeq")
library(edgeR) # BiocManager::install("edgeR")
library(limma)
library("dittoSeq")
library("celldex")
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(ggplot2)
library(Matrix)
library(tidyr)
library(stringr)
```


#without the annotations
```{r}
# Load loomR
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
setwd("E:/seq_data/FCA/")

loom_file <- connect(filename = "r_fca_biohub_head_10x.loom", mode = "r+", skip.validate=TRUE)




matrix_data <- as.data.frame(loom_file[["matrix"]][,])
  rownames(matrix_data) <- loom_file[["col_attrs/CellID"]][]
  colnames(matrix_data) <- loom_file[["row_attrs/Gene"]][]

  highNpfr<-(matrix_data[matrix_data$NPFR>1,])
    drops <- c("annotation")
    woAnn<-highNpfr[ , !(names(highNpfr) %in% drops)]

    SERUAT_NPFR <- CreateSeuratObject(counts = t(woAnn), project = "high Npfr", min.cells = 0, min.features=0)
  

```
#higly expressed gene
```{r}
library(ggplot2)
library(Matrix)
library(Seurat)

SERUAT_NPFR <-readRDS("C:/dev/genomics/FCA/FCA_22_11.rds")


most_expressed_boxplot <- function(object, ngenes = 20){

  # matrix of raw counts
  cts <- Seurat::GetAssayData(object, assay = "RNA", slot = "counts")

  # get percentage/cell
  cts <- t(cts)/colSums(cts)*100
  medians <- apply(cts, 2, median)

  # get top n genes
  most_expressed <- order(medians, decreasing = T)[ngenes:1]
  most_exp_matrix <- as.matrix((cts[,most_expressed]))

  # prepare for plotting
  most_exp_df <- stack(as.data.frame(most_exp_matrix))
  colnames(most_exp_df) <- c("perc_total", "gene")

  # boxplot with ggplot2
  boxplot <- ggplot(most_exp_df, aes(x=gene, y=perc_total)) +
    geom_boxplot() +
    coord_flip()
  return(boxplot)
}

most_expressed_boxplot(SERUAT_NPFR, 5)

```



```{r}
SERUAT_NPFR <- Seurat::NormalizeData(SERUAT_NPFR,
                     normalization.method = "LogNormalize",
                     scale.factor = 10000)

SERUAT_NPFR <- Seurat::FindVariableFeatures(SERUAT_NPFR,
                            selection.method = "vst",
                            nfeatures = 1500)

# Identify the 10 most highly variable genes
top10 <- head(Seurat::VariableFeatures(SERUAT_NPFR), 10)
top10

vf_plot <- Seurat::VariableFeaturePlot(SERUAT_NPFR)
Seurat::LabelPoints(plot = vf_plot,
            points = top10, repel = TRUE)


SERUAT_NPFR <- Seurat::ScaleData(SERUAT_NPFR,
                 features = rownames(SERUAT_NPFR))



#saveRDS(SERUAT_NPFR, "seu_day1.rds")

#rm(list = ls())
#gc()
#.rs.restartR()
```

#check the wanted gene names

```{r}



    all.genes <- rownames(SERUAT_NPFR)

    all_genes<-as.data.frame(rownames(SERUAT_NPFR))
    
    gene_of_interest <- "Syt1"

    gene_of_interest %in% all.genes
  
    list_of_gene_yulia<-c("Dh44","NPF","NPFR","Tdc2","Crz","Trh","trh","fru","Syt1")

   test<- grep('Obp', all.genes, value=TRUE)

```



```{r}

  

#SERUAT_NPFR <-readRDS("E:/seq_data/FCA/FCA17_11.rds")
library(ggplot2)
 # SERUAT_NPFR[["percent.mt"]] <- PercentageFeatureSet(SERUAT_NPFR, pattern = "^MT-")
  VlnPlot(SERUAT_NPFR, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)

FeatureScatter(SERUAT_NPFR, feature1 = "nCount_RNA", feature2 = "nFeature_RNA") +
  geom_smooth(method = 'lm')
  SERUAT_NPFR <- NormalizeData(SERUAT_NPFR, normalization.method = "LogNormalize", scale.factor= 10000)
  View(SERUAT_NPFR@meta.data)
  
  SERUAT_NPFR <- FindVariableFeatures(SERUAT_NPFR, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(SERUAT_NPFR), 10)

plot1 <- VariableFeaturePlot(SERUAT_NPFR)
LabelPoints(plot = plot1, points = top10, repel = TRUE)


all.genes <- rownames(SERUAT_NPFR)
SERUAT_NPFR <- ScaleData(SERUAT_NPFR, features = all.genes)
str(SERUAT_NPFR)
SERUAT_NPFR <- RunPCA(SERUAT_NPFR, features = VariableFeatures(object = SERUAT_NPFR))

print(SERUAT_NPFR[["pca"]], dims = 1:5, nfeatures = 5)


Seurat::ElbowPlot(SERUAT_NPFR, ndims = 40)
DimHeatmap(SERUAT_NPFR, dims = 1:10, cells = 200, balanced = TRUE)
DimHeatmap(SERUAT_NPFR)

SERUAT_NPFR <- FindNeighbors(SERUAT_NPFR, dims = 1:15)

SERUAT_NPFR <- FindClusters(SERUAT_NPFR, resolution = c(0.1,0.3, 0.5, 0.7, 1))
View(SERUAT_NPFR@meta.data)

#check what kind of resulution is the best
DimPlot(SERUAT_NPFR, group.by = "RNA_snn_res.0.3", label = TRUE)
#Idents(SERUAT_NPFR)
Idents(SERUAT_NPFR) <- "RNA_snn_res.0.3"

#Idents(SERUAT_NPFR)

SERUAT_NPFR <- RunUMAP(SERUAT_NPFR, dims = 1:15)
DimPlot(SERUAT_NPFR, reduction = "umap")
DefaultAssay(SERUAT_NPFR) <- "RNA"
Seurat::FeaturePlot(SERUAT_NPFR, "brp")


neruon_cell_genes <- c("elav", "NPF", "Syt1", "brp")
 list_of_gene_yulia<-c("Dh44","NPF","NPFR","Tdc2","Crz","Trh","trh","fru","Syt1")
Seurat::FeaturePlot(SERUAT_NPFR, neruon_cell_genes, ncol=2)
Seurat::FeaturePlot(SERUAT_NPFR, list_of_gene_yulia, ncol=3)


#monocyte_genes <- c("CD14", "CST3", "CD68", "CTSS")

#plot <- DimPlot(SERUAT_NPFR, reduction = "umap")
#LabelClusters(plot = plot, id = "ident")
  

Seurat::VlnPlot(SERUAT_NPFR,
                features = neruon_cell_genes,
                ncol = 2)


Seurat::VlnPlot(SERUAT_NPFR,
                features = list_of_gene_yulia,
                ncol = 3)

SERUAT_NPFR <- Seurat::AddModuleScore(SERUAT_NPFR,
                              features = list(neruon_cell_genes),
                              name = "neruon_cell_genes")

SERUAT_NPFR <- Seurat::AddModuleScore(SERUAT_NPFR,
                              features = list(list_of_gene_yulia),
                              name = "list_of_gene_yulia")



View(SERUAT_NPFR@meta.data)

#Seurat::FeaturePlot(SERUAT_NPFR, #"neruon_cell_genes1")

#s.genes <- Seurat::cc.genes.updated.2019$s.genes
#g2m.genes <- Seurat::cc.genes.updated.2019$g2m.genes


#SERUAT_NPFR <- Seurat::CellCycleScoring(SERUAT_NPFR,
#                                     s.features #=s.genes,
 #                                    g2m.features = #g2m.genes)

colnames(SERUAT_NPFR@meta.data)[colnames(SERUAT_NPFR@meta.data) == 'oldName'] <- 'newName'

```

```{r}
#BiocManager::install("edgeR")
#if (!require("BiocManager", quietly = TRUE))
 #   install.packages("BiocManager")
#BiocManager::install("celldex")
#install.packages("stringer")
#BiocManager::install("dittoSeq")
library(Seurat)
library(edgeR) # BiocManager::install("edgeR")
library(limma)
library("dittoSeq")
library("celldex")
de_genes <- Seurat::FindAllMarkers(SERUAT_NPFR,  min.pct = 0.25,
                                   only.pos = TRUE)
de_genes <- subset(de_genes, de_genes$p_val_adj<0.05)
write.csv(de_genes, "C:/dev/genomics/FCA/de_genes_FindAllMarkers.csv", row.names = F, quote = F)


library(dplyr)
top_specific_markers <- de_genes %>%
  group_by(cluster) %>%
  top_n(3, avg_log2FC)


dittoSeq::dittoDotPlot(SERUAT_NPFR, vars = unique(g$gene), 
                       group.by = "RNA_snn_res.0.3")


```


```{r}


# Load loomR
library(loomR)
library(Seurat)

setwd("E:/seq_data/FCA/")

loom_file <- connect(filename = "r_fca_biohub_head_10x.loom", mode = "r+", skip.validate=TRUE)



#please check if in the rds file there is only the gene that are high of NPFR,do sinty check
matrix_data <- as.data.frame(loom_file[["matrix"]][,])
  rownames(matrix_data) <- loom_file[["col_attrs/CellID"]][]
  colnames(matrix_data) <- loom_file[["row_attrs/Gene"]][]
  matrix_data$annotation<-loom_file[["col_attrs/S_annotation"]][]

  highNpfr<-(matrix_data[matrix_data$NPFR>1,])
    drops <- c("annotation")
    woAnn<-highNpfr[ , !(names(highNpfr) %in% drops)]
    ann<- highNpfr["annotation"]

    
    
    
    


```




#oegenize the name and the barcode in the seruat object


```{r}

SERUAT_NPFR <-readRDS("C:/dev/genomics/FCA/FCA_22_11.rds")
library(tidyr)
library(stringr)

SERUAT_NPFR$sample <- rownames(SERUAT_NPFR@meta.data)

SERUAT_NPFR$sample<-str_remove(SERUAT_NPFR$sample, "Adult_")
SERUAT_NPFR$sample<-str_replace(SERUAT_NPFR$sample, "__", "_")


SERUAT_NPFR@meta.data <- separate(SERUAT_NPFR@meta.data, col = 'sample', into = c('Barcode','Test', 'Gender','Origin'), 
         sep = '_')
SERUAT_NPFR@meta.data$tissu<-ann$annotation
#colnames(SERUAT_NPFR@meta.data$tissu$annotation)<-c#("tissue")
View(SERUAT_NPFR@meta.data)
unique(SERUAT_NPFR@meta.data$Gender)
unique(SERUAT_NPFR@meta.data$tissu)
saveRDS(SERUAT_NPFR, "C:/dev/genomics/FCA/FCA_22_11.rds")




```



```{r}
# Include additional data to display alongside cell names by passing in a data frame of
# information Works well when using FetchData
FeaturePlot(SERUAT_NPFR, features = "NPFR", min.cutoff = 1, max.cutoff = 3)

#plot <- FeaturePlot(SERUAT_NPFR, features = "NPFR")
#HoverLocator(plot = plot, information = FetchData(SERUAT_NPFR, vars = c("ident", "PC_1")))
```



```{r}
library(gridExtra)

library(purrr)

split_seurat <- SplitObject(SERUAT_NPFR, split.by = "tissu_new")


new_list <- discard(test, .p = ~str_detect(.x,"unannotated"))

ttest<-MergeSTData(split_seurat)

split_seurat <- split_seurat[new_list]

#tried to give diffrent color palte ,didnt work
p1 <- DimPlot(SERUAT_NPFR, reduction = 'umap', group.by = 'tissu')+guides(color = guide_legend(override.aes = list(size=1), ncol=2) )+theme(legend.title = element_text(size = 5), 
               legend.text = element_text(size = 5))
#install.packages("wesanderson")


p6<- DimPlot(SERUAT_NPFR, reduction = 'umap',split.by ="tissu_new",ncol = 5)+theme(legend.title = element_text(size = 4), 
               legend.text = element_text(size = 4))
#install.packages("wesanderson")
library(wesanderson)
library(RColorBrewer)



temp<-as.data.frame(SERUAT_NPFR@meta.data$tissu_new)
p2 <- DimPlot(SERUAT_NPFR, reduction = 'umap', group.by = 'Gender')
p3<-DimPlot(SERUAT_NPFR, reduction = "umap")


neruon_cell_genes <- c("elav", "NPF", "Syt1", "brp")
 list_of_gene_yulia<-c("Dh44","NPF","NPFR","Tdc2","Crz","Trh","trh","fru","Syt1")
p4<-Seurat::FeaturePlot(SERUAT_NPFR, neruon_cell_genes, ncol=2)
p5<-Seurat::FeaturePlot(SERUAT_NPFR, list_of_gene_yulia, ncol=3)


grid.arrange(p3, p2, ncol = 2, nrow = 2)

```

```{r}

#install.packages("randomcoloR")

colors38 = c("#466791","#60bf37","#953ada","#4fbe6c","#ce49d3","#a7b43d","#5a51dc","#d49f36","#552095","#507f2d","#db37aa","#84b67c","#a06fda","#df462a","#5b83db","#c76c2d","#4f49a3","#82702d","#dd6bbb","#334c22","#d83979","#55baad","#dc4555","#62aad3","#8c3025","#417d61","#862977","#bba672","#403367","#da8a6d","#a79cd4","#71482c","#c689d0","#6b2940","#d593a7","#895c8b","#bd5975","#FFFFFF")

highlight_gene_expression <- function(seurat, gene_counts, cells = rownames(seurat@meta.data), colors = NULL){
  Idents(seurat) <- 'cell_type'
  p <- DimPlot(
    seurat,
    raster = FALSE,
    shuffle = TRUE,
    reduction = "umap",
    cols.highlight = colors,
    pt.size = 0.01,
    sizes.highlight = 0.01,
    cells.highlight = seurat@meta.data[cells,] %>% split(.$cell_type) |> lapply(rownames),
  )
  p <- p + guides(color = guide_legend(override.aes = list(size = 4), ncol = 1))

  expression_level <- {gene_counts |> rowSums()} / {gene_counts |> rowSums() |> max()}
  p[[1]]$layers[[1]]$aes_params$alpha <- expression_level
  p
}
```

```{r}

tissue_name<-unique(SERUAT_NPFR@meta.data$tissu_new)
cell_names <- c("unannotated")
DimPlot(object = SERUAT_NPFR, cells.highlight = "cell_names, cols.highlight = "red", cols = "gray", order = TRUE)

DimPlot(SERUAT_NPFR, label=T, group.by="tissu_new", cells.highlight= "", cols.highlight = "red", cols= "grey")
```

