---
title: "seruat_head"
author: "lital barak"
date: "2022-11-30"
output: html_document
---

```{r}
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
setwd("D:/seq_data/FCA/")

loom_file <- connect(filename = "r_fca_biohub_head_10x.loom", mode = "r+", skip.validate=TRUE)




matrix_data <- as.data.frame(loom_file[["matrix"]][,])
  rownames(matrix_data) <- loom_file[["col_attrs/CellID"]][]
  colnames(matrix_data) <- loom_file[["row_attrs/Gene"]][]


  SERUAT_HEAD <- CreateSeuratObject(counts = t(matrix_data), project = "Head", min.cells = 0, min.features=0)
  saveRDS(SERUAT_HEAD, "seuruat_head_non_norm.rds")
  

```

```{r}
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
  SERUAT_HEAD <-readRDS("D:/seq_data/FCA/seuruat_head.rds")
SERUAT_HEAD <- subset(SERUAT_HEAD, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 )

```



```{r}
    all.genes <- rownames(SERUAT_HEAD)

    all_genes<-as.data.frame(rownames(SERUAT_HEAD))
    
    gene_of_interest <- "Syt1"

    gene_of_interest %in% all.genes
  
    neruon_cell_genes <- c("elav", "NPF", "Syt1", "brp")
    list_of_gene_yulia<-c("Dh44","NPF","NPFR","Tdc2","Crz","Trh","trh","fru","Syt1")
```


```{r}
# SERUAT_HEAD <- Seurat::NormalizeData(SERUAT_HEAD,
#                      normalization.method = "LogNormalize",
#                      scale.factor = 10000)
# 
# SERUAT_HEAD <- Seurat::FindVariableFeatures(SERUAT_HEAD,
#                             selection.method = "vst",
#                             nfeatures = 1500)




#saveRDS(SERUAT_HEAD,"D:/seq_data/FCA/seuruat_head_scaled.rds")


# Identify the 10 most highly variable genes
top10 <- head(Seurat::VariableFeatures(SERUAT_HEAD), 10)
top10

vf_plot <- Seurat::VariableFeaturePlot(SERUAT_HEAD)
Seurat::LabelPoints(plot = vf_plot,
            points = top10, repel = TRUE)


SERUAT_HEAD <- Seurat::ScaleData(SERUAT_HEAD,
                 features = rownames(SERUAT_HEAD))

SERUAT_HEAD <- RunPCA(SERUAT_HEAD, features = VariableFeatures(object = SERUAT_HEAD))

SERUAT_HEAD <- RunTSNE(SERUAT_HEAD, dims.use = 1:30, do.fast = T)
SERUAT_HEAD <- FindNeighbors(SERUAT_HEAD, dims = 1:15)

SERUAT_HEAD <- FindClusters(SERUAT_HEAD , resolution = seq(0.1,4,0.2))
Idents(SERUAT_HEAD) <- "RNA_snn_res.0.3"

#check what kind of resulution is the best
DimPlot(SERUAT_HEAD, group.by = "RNA_snn_res.3.9", label = TRUE,raster=FALSE)

DimPlot(SERUAT_HEAD, group.by = "RNA_snn_res.3.9", label = TRUE,raster=FALSE)

FeaturePlot(object = SERUAT_HEAD, features = c('NPFR', 'Dh44'), blend = TRUE,raster=FALSE,blend.threshold = 0.1,pt.size = 2)


 Idents(SERUAT_HEAD) <-WhichCells(object = SERUAT_HEAD, expression = NPFR > 4)
 DimPlot(SERUAT_HEAD, label = TRUE,raster=FALSE)
 
 
 cell_typeA_marker_gene_list <- list(c("Dh44","NPF","NPFR","Tdc2","Crz","Trh","trh","fru","Syt1"))
SERUAT_HEAD <- AddModuleScore(object = SERUAT_HEAD, features = cell_typeA_marker_gene_list, name = "ten_cell")
FeaturePlot(object = SERUAT_HEAD, features = "ten_cell1",raster=FALSE)
 
DimPlot(SERUAT_HEAD, cells.highlight= WhichCells(SERUAT_HEAD,expression = "NPFR"> 0 ), raster=FALSE)



#Cluster_Highlight_Plot(seurat_object = SERUAT_HEAD, cluster_name = "7", highlight_color = "navy",
  #  background_color = "lightgray")
#library(scCustomize)
#devtools::install_github(repo = "samuel-marsh/scCustomize")


test <- c("Dh44","NPF","NPFR","Tdc2","Crz","Trh","trh","fru","Syt1")
FeaturePlot(object = SERUAT_HEAD, features.plot = c("Dh44","NPF","NPFR","Tdc2","Crz","Trh","trh","fru","Syt1"),raster=FALSE )
```


```{r}
SERUAT_HEAD <- Seurat::NormalizeData(SERUAT_HEAD,
                     normalization.method = "LogNormalize",
                     scale.factor = 10000)

SERUAT_HEAD <- Seurat::FindVariableFeatures(SERUAT_HEAD,
                            selection.method = "vst",
                            nfeatures = 1500)

# Identify the 10 most highly variable genes
top10 <- head(Seurat::VariableFeatures(SERUAT_HEAD), 10)
top10

vf_plot <- Seurat::VariableFeaturePlot(SERUAT_HEAD)
Seurat::LabelPoints(plot = vf_plot,
            points = top10, repel = TRUE)


SERUAT_HEAD <- Seurat::ScaleData(SERUAT_HEAD,
                 features = rownames(SERUAT_HEAD))



#SERUAT_NPFR <-readRDS("E:/seq_data/FCA/FCA17_11.rds")
library(ggplot2)
 # SERUAT_NPFR[["percent.mt"]] <- PercentageFeatureSet(SERUAT_NPFR, pattern = "^MT-")

#  VlnPlot(SERUAT_HEAD, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)

#FeatureScatter(SERUAT_HEAD, feature1 = "nCount_RNA", feature2 = "nFeature_RNA") +
 # geom_smooth(method = 'lm')
  



# pbmc33k <- PCAFast(pbmc33k, pc.genes = pbmc33k@var.genes, pcs.compute = 40, pcs.print = 30)
# 
# PCElbowPlot(pbmc33k, num.pc = 40)
# PrintPCA(pbmc33k,pcs.print = 1:36)
# PCHeatmap(pbmc33k,pc.use = 1:12,100)
# PCHeatmap(pbmc33k,pc.use = 13:24,100)
# PCHeatmap(pbmc33k,pc.use = 25:36,100)


SERUAT_HEAD <- RunPCA(SERUAT_HEAD, features = VariableFeatures(object = SERUAT_HEAD))


#saveRDS(SERUAT_HEAD, "seuruat_head_pca.rds")


#Seurat::ElbowPlot(SERUAT_HEAD, ndims = 40)
#DimHeatmap(SERUAT_HEAD, dims = 1:10, cells = 200, balanced = TRUE)
#DimHeatmap(SERUAT_HEAD)
SERUAT_HEAD <- FindNeighbors(SERUAT_HEAD, dims = 1:15)

  View(SERUAT_HEAD@meta.data)



SERUAT_HEAD <- FindClusters(SERUAT_HEAD, resolution = c(0.1,0.3, 0.5, 0.7, 1,1.2))
View(SERUAT_HEAD@meta.data)


#Idents(SERUAT_NPFR)


Idents(SERUAT_HEAD) <- "RNA_snn_res.0.1"

#check what kind of resulution is the best
DimPlot(SERUAT_HEAD, group.by = "RNA_snn_res.0.1", label = TRUE,raster=FALSE)

Idents(SERUAT_HEAD) <- "RNA_snn_res.1.2"

#check what kind of resulution is the best
DimPlot(SERUAT_HEAD, group.by = "RNA_snn_res.1.2", label = TRUE,raster=FALSE)

FeaturePlot(object = SERUAT_HEAD, features = c('NPFR', 'fru'), blend = TRUE,raster=FALSE,blend.threshold = 0.1,pt.size = 3)






```


```{r}
SERUAT_HEAD <- RunTSNE(SERUAT_HEAD, dims.use = 1:30, do.fast = T)
SERUAT_HEAD <- FindClusters(SERUAT_HEAD , resolution = seq(0.1,3,0.2))
Idents(SERUAT_HEAD) <- "RNA_snn_res.0.1"

#check what kind of resulution is the best
DimPlot(SERUAT_HEAD, group.by = "RNA_snn_res.0.1", label = TRUE,raster=FALSE)

FeaturePlot(object = SERUAT_HEAD, features = c('NPFR', 'Dh44'), blend = TRUE,raster=FALSE,blend.threshold = 0.5,pt.size = 2)
```

```{r}

SERUAT_HEAD <- FindClusters(SERUAT_HEAD ,pc.use = 1:10, resolution = seq(2,4,0.5), save.SNN = T, do.sparse = T)


```

```{r}
  View(SERUAT_HEAD@meta.data)

```

```{r}
SERUAT_HEAD <- RunUMAP(SERUAT_HEAD, dims = 1:15,reduction ="tsne")
DimPlot(SERUAT_HEAD, reduction = "umap")
DefaultAssay(SERUAT_HEAD) <- "RNA"
#Seurat::FeaturePlot(SERUAT_HEAD, "brp")


FeaturePlot(object = SERUAT_HEAD, features = c('NPFR', 'Dh44'), blend = TRUE,raster=FALSE,blend.threshold = 0.5,pt.size = 2)


Seurat::FeaturePlot(SERUAT_HEAD, neruon_cell_genes, ncol=2,raster=FALSE)
Seurat::FeaturePlot(SERUAT_HEAD, list_of_gene_yulia, ncol=3,raster=FALSE)
```

