---
title: "antena_head"
output: html_document
date: "2023-01-25"
---

```{r}

```

cumulative hist function of head and antena 
```{r}
library(spatstat.utils)
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)



main_path<-"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/basal_level"

SERUAT_HEAD <-readRDS("D:/seq_data/FCA/seuruat_head_non_norm.rds")

SERUAT_Antena <-readRDS("D:/seq_data/FCA/seuruat_antena_non_normelize.rds")
head_antena_sum<-function(gene_name,y_value,x_value){
  
  precnt_name<-paste("percent.",gene_name,sep="")
  SERUAT_Antena[[precnt_name]] <- PercentageFeatureSet(SERUAT_Antena,features =gene_name)
  SERUAT_HEAD[[precnt_name]] <- PercentageFeatureSet(SERUAT_HEAD,features =gene_name)
  
  gene_head<-as.data.frame(get(precnt_name,SERUAT_HEAD@meta.data))
  gene_antena<-as.data.frame(get(precnt_name,SERUAT_Antena@meta.data))
  colnames(gene_head)<-"head"
  colnames(gene_antena)<-"antena"
  
  
  
  gene_sum_head <- hist(gene_head$head,breaks=seq(0,10,l=500))                     # Store histogram info
  gene_sum_head$counts <- revcumsum((gene_sum_head$counts))    # Change histogram counts
  
  gene_sum_antena <-hist(gene_antena$antena,breaks=seq(0,10,l=500)) 
  gene_sum_antena$counts <- revcumsum((gene_sum_antena$counts))    # Change histogram counts

  
  plotname<-paste("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/basal_level/","freq",gene_name,"y_lim",y_value,".tiff",sep = "")
  
tiff(file=plotname,units="in",height=11,width=11,res=600)
  main_title <-paste("head (red) vs antena (green)",gene_name)

  plot(gene_sum_head,col=alpha('red',0.5),xlim=rev(c(0, x_value)),ylim =c(0,y_value),main=main_title,ylab = "sum of sampels") 
  plot(gene_sum_antena,col=alpha('green',0.5),xlim=rev(c(0, x_value)),ylim =c(0,y_value),add = TRUE)
dev.off()



}

head_antena_sum("NPFR",13,2)

#fru 200
#Tdc2 35
#NPF 5
#NPFR 13
```


 hist of frq based on xlim and ylim choice of all the data on the same plot! all the permuatuion
```{r}
library(spatstat.utils)
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)

SERUAT_HEAD <-readRDS("D:/seq_data/FCA/seuruat_head_non_norm.rds")

SERUAT_Antena <-readRDS("D:/seq_data/FCA/seuruat_antena_non_normelize.rds")
list_of_freq<-c(100,50,20,10,5,2,1,0.5,0.1,0.05)

list_of_xlimit<-c(10,5,2)


# list_of_freq<-c(20)
# list_of_xlimit<-c(2)
list_of_gene<-c("Crz","ple","Tdc2","trh","fru","NPF","Obp69a","Or67d","Or65a","brp","sNPF","Tbh","Adar","orb2","NPFR")


for(m in 1:length(list_of_xlimit)){
for(j in 1: length(list_of_freq)){
precentage<-list_of_freq[j]
xlimit<-list_of_xlimit[m]
plotname<-paste("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/11.1.23/","freq",precentage,"exp",xlimit,".tiff",sep = "")
tiff(file=plotname,units="in",height=11,width=11,res=600)
par(mfrow = c(3, 5),mar = c(2.1, 2.1, 6, 2.1),xaxs = "i",yaxs = "i",cex.axis=1.1,cex.lab=1.1)
for(i in 1:length(list_of_gene)){
current_gene<-list_of_gene[i]
main_title <-paste(current_gene)
antena_and_head_list<-head_antena(current_gene)

gene_antena_density<-antena_and_head_list[[1]]
gene_head_density<-antena_and_head_list[[2]]
# plot(gene_head_density, freq = FALSE,col=alpha('red',0.5), main=main_title, xlab='%',ylim =c(0,y_value),xlim = c(0,5)) 
 #plot(gene_antena_density,freq = FALSE, col=alpha('green',0.5),ylim =c(0,y_value),add = TRUE,xlim = c(0,5))
 
 
  plot(gene_antena_density,freq = FALSE, col=alpha('blue',0.7),ylim =c(0,precentage),main=main_title, xlab="relative expression",ylab = "frequency",xlim = c(0,xlimit))
  plot(gene_head_density, freq = FALSE,col=alpha('yellow',0.5), add = TRUE,ylim =c(0,precentage),xlim = c(0,xlimit)) 
 title_<-paste("frequency is",precentage,"relative expression is",xlimit,"yellow is head blue is antena ")
  #dev.off()
  mtext(title_, side = 3, line =-2, outer = TRUE ,cex=1)
}
dev.off()
}
}

```

hist based on xlim and ylim choice on all the gene diffrent plots

```{r}
library(spatstat.utils)
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)

SERUAT_HEAD <-readRDS("D:/seq_data/FCA/seuruat_head_non_norm.rds")

SERUAT_Antena <-readRDS("D:/seq_data/FCA/seuruat_antena_non_normelize.rds")
all.genes_antena<-as.data.frame(rownames(SERUAT_Antena))
all.genes_head<-as.data.frame(rownames(SERUAT_HEAD))

head_antena<-function(gene_name){
  
  precnt_name<-paste("percent.",gene_name,sep="")
  SERUAT_Antena[[precnt_name]] <- PercentageFeatureSet(SERUAT_Antena,features =gene_name)
  SERUAT_HEAD[[precnt_name]] <- PercentageFeatureSet(SERUAT_HEAD,features =gene_name)
  
  gene_head<-as.data.frame(get(precnt_name,SERUAT_HEAD@meta.data))
  gene_antena<-as.data.frame(get(precnt_name,SERUAT_Antena@meta.data))
  colnames(gene_head)<-"head"
  colnames(gene_antena)<-"antena"
  
  
  gene_head_density <- hist(gene_head$head, breaks=seq(0,10,l=200),plot = FALSE)         # Store output of hist function
gene_head_density$density <- gene_head_density$counts /    # Compute density values
  sum(gene_head_density$counts) * 100


gene_antena_density <- hist(gene_antena$antena, breaks=seq(0,10,l=200),plot = FALSE)         # Store output of hist function
gene_antena_density$density <- gene_antena_density$counts /    # Compute density values
  sum(gene_antena_density$counts) * 100

# 
# main_title <-paste(gene_name)
# 
# # plot(gene_head_density, freq = FALSE,col=alpha('red',0.5), main=main_title, xlab='%',ylim =c(0,y_value),xlim = c(0,5)) 
#  #plot(gene_antena_density,freq = FALSE, col=alpha('green',0.5),ylim =c(0,y_value),add = TRUE,xlim = c(0,5))
#  
#  
#   plot(gene_antena_density,freq = FALSE, col=alpha('green',0.5),ylim =c(0,y_value),main=main_title, xlab='%',xlim = c(0,xlimit))
#   plot(gene_head_density, freq = FALSE,col=alpha('red',0.5), add = TRUE,ylim =c(0,y_value),xlim = c(0,xlimit)) 

return(list(gene_antena_density,gene_head_density))
}



list_of_gene<-c("Crz","ple","Tdc2","trh","fru","NPF","Obp69a","Or67d","Or65a","brp","sNPF","Tbh","Adar","orb2","NPFR")

list_of_freq<-c(100,50,20,10,5,2,1,0.5,0.1,0.05)

list_of_xlimit<-c(10,5,2)
#main_path<-"C:/Users/barakli8\OneDrive - Bar Ilan University/Lital/weekly presentation/basal_level"
for(m in 1:length(list_of_xlimit)){
for(j in 1: length(list_of_freq)){
par(mfrow = c(3, 5))
for(i in 1:length(list_of_gene)){
current_gene<-list_of_gene[i]
precentage<-list_of_freq[j]
xlimit<-list_of_xlimit[m]
dir.create(paste(main_path,"/",precentage,sep = ""))
dir.create(paste(main_path,"/",precentage,"/",xlimit,sep = ""))
plotname<-paste("C:/Users/lital/Desktop/seruat_head_anetna/",precentage,"/",xlimit,"/",current_gene,".png",sep = "")
png(file=plotname)
main_title <-paste(current_gene)
antena_and_head_list<-head_antena(current_gene)

gene_antena_density<-antena_and_head_list[[1]]
gene_head_density<-antena_and_head_list[[2]]
# plot(gene_head_density, freq = FALSE,col=alpha('red',0.5), main=main_title, xlab='%',ylim =c(0,y_value),xlim = c(0,5)) 
 #plot(gene_antena_density,freq = FALSE, col=alpha('green',0.5),ylim =c(0,y_value),add = TRUE,xlim = c(0,5))
 
 
  plot(gene_antena_density,freq = FALSE, col=alpha('blue',0.7),ylim =c(0,precentage),main=main_title, xlab="relative expression",ylab = "frequency",xlim = c(0,xlimit))
  plot(gene_head_density, freq = FALSE,col=alpha('yellow',0.5), add = TRUE,ylim =c(0,precentage),xlim = c(0,xlimit)) 
dev.off()
}
}
}



```

