```{r}

library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
loom_file <- connect(filename = "D:/seq_data/FCA/s_fca_biohub_male_reproductive_glands_10x.loom", mode = "r+", skip.validate=TRUE)
matrix_data <- as.data.frame(loom_file[["matrix"]][,])
  rownames(matrix_data) <- loom_file[["col_attrs/CellID"]][]
  colnames(matrix_data) <- loom_file[["row_attrs/Gene"]][]
  SERUAT_Antena <- CreateSeuratObject(counts = t(matrix_data), project = "antena", min.cells = 0, min.features=0)
 # saveRDS(SERUAT_antena_N, "/home/alu/aluguest/Lital_galitLab/seuruat_antena_non_normelize.rds")
  
  
SERUAT_Antena <- NormalizeData(object = SERUAT_Antena)
SERUAT_Antena <- FindVariableFeatures(object = SERUAT_Antena)
SERUAT_Antena <- ScaleData(object = SERUAT_Antena)
SERUAT_Antena <- RunPCA(object = SERUAT_Antena)
ElbowPlot(SERUAT_Antena)
SERUAT_Antena <- FindNeighbors(object = SERUAT_Antena, dims = 1:20)
SERUAT_Antena <- FindClusters(object = SERUAT_Antena)
SERUAT_Antena <- RunUMAP(object = SERUAT_Antena, dims = 1:20)

saveRDS(SERUAT_Antena, "D:/seq_data/FCA/seuruat_male_reproductive_glands_13_9.rds")
```



```{r}
library(tidyr)
library(dplyr)
library(stringr)
SERUAT_HEAD<- readRDS("D:/seq_data/FCA/seuruat_antena_13_9.rds")

SERUAT_HEAD$sample <- rownames(SERUAT_HEAD@meta.data)

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "__", "_")

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "-", "_")

View(SERUAT_HEAD@meta.data)
SERUAT_HEAD@meta.data <- separate(SERUAT_HEAD@meta.data, col = 'sample', into = c("test",'Barcode','identity', 'Sex'),
                                  sep = '_')

SERUAT_HEAD@meta.data$obp69a<- FetchData(SERUAT_HEAD, vars = "Obp69a")

SERUAT_HEAD@meta.data$lush<- FetchData(SERUAT_HEAD, vars = "lush")
SERUAT_HEAD@meta.data$obp28a<- FetchData(SERUAT_HEAD, vars = "Obp28a")

   plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/male_reproductive_glands_sex.tiff")
  
 tiff(file=plotname,units="in",height=11,width=11,res=600)

DimPlot(SERUAT_HEAD, reduction = 'umap', group.by = 'Sex',raster=FALSE)+guides(color = guide_legend(override.aes = list(size=1), ncol=2) )+theme(legend.title = element_text(size = 5), 
               legend.text = element_text(size = 7))

dev.off()




plotname<-"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/male_reproductive_glands_Obp28a_wo_threshold_Sex.tiff"

tiff(file=plotname,units="in",height=13,width=18,res=600)

#FeaturePlot(SERUAT_HEAD,features ="Obp28a",split.by = "Sex")

FeaturePlot(SERUAT_HEAD,features ="Obp28a")

dev.off()


plotname<-"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/male_reproductive_glands_Obp69a_wo_threshold_Sex.tiff"

tiff(file=plotname,units="in",height=13,width=18,res=600)

#FeaturePlot(SERUAT_HEAD,features ="Obp69a",split.by = "Sex")

FeaturePlot(SERUAT_HEAD,features ="Obp69a")
dev.off()



plotname<-"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/male_reproductive_glands_lush_wo_threshold_Sex.tiff"

tiff(file=plotname,units="in",height=13,width=18,res=600)

#FeaturePlot(SERUAT_HEAD,features ="lush",split.by = "Sex")
FeaturePlot(SERUAT_HEAD,features ="lush")

dev.off()

```

```{r}
SERUAT_HEAD<- readRDS("D:/seq_data/FCA/16_10_antena_obp.rds")


    all_genes<-as.data.frame(rownames(SERUAT_HEAD))
```

```{r}
t<-SplitObject(SERUAT_HEAD, split.by = "Sex")

tmp_SERUAT_HEAD<-SERUAT_HEAD

SERUAT_HEAD<-t[["MaleFemale"]]

```


```{r}
library(tidyr)
library(dplyr)
library(stringr)

 library(Seurat)
 library(ggplot2)
 library(scCustomize)

SERUAT_HEAD<- readRDS("D:/seq_data/FCA/seuruat_antena_13_9.rds")

SERUAT_HEAD$sample <- rownames(SERUAT_HEAD@meta.data)

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "__", "_")

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "-", "_")

View(SERUAT_HEAD@meta.data)
SERUAT_HEAD@meta.data <- separate(SERUAT_HEAD@meta.data, col = 'sample', into = c("test",'Barcode','identity', 'Sex'),
                                  sep = '_')

SERUAT_HEAD@meta.data$obp69a<- FetchData(SERUAT_HEAD, vars = "Obp69a")

SERUAT_HEAD@meta.data$lush<- FetchData(SERUAT_HEAD, vars = "lush")
SERUAT_HEAD@meta.data$obp28a<- FetchData(SERUAT_HEAD, vars = "Obp28a")
# SERUAT_HEAD@meta.data$obp69a<- FetchData(SERUAT_HEAD, vars = "Obp69a")
# 
# SERUAT_HEAD@meta.data$lush<- FetchData(SERUAT_HEAD, vars = "lush")
# SERUAT_HEAD@meta.data$obp28a<- FetchData(SERUAT_HEAD, vars = "Obp28a")

SERUAT_HEAD$sample <- rownames(SERUAT_HEAD@meta.data)

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "__", "_")

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "-", "_")

SERUAT_HEAD@meta.data <- separate(SERUAT_HEAD@meta.data, col = 'sample', into = c("test",'Barcode','identity', 'Sex'), 
                                  sep = '_')
#its above 0 its dosent matter.it is for the markers per FCA
all_gene_csv<-as.data.frame(read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/all_genes_for_leg.csv"))


number_of_fca<-c("3","43","44","55","56")
names_of_fca<-paste("FCA",number_of_fca,sep="")

#threshold_values<-c(0.36,0.3,0.18,0.05,0.16,0.33,0.57)
gene_names<-c("obp69a","lush","obp28a")

fullname<-paste("s_",gene_names,sep="")


SERUAT_HEAD@meta.data$s_obp69a<-""
SERUAT_HEAD@meta.data$s_lush<-""
SERUAT_HEAD@meta.data$s_obp28a<-""




for(gene_i in 1:length(gene_names)){

for(fca_i in 1:length(names_of_fca)){
FCA_LIST<- all_gene_csv[all_gene_csv$FCA %in% names_of_fca[fca_i],]

current_value_threshold<- FCA_LIST[FCA_LIST$Gene %in% gene_names[[gene_i]],]$value


SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],fullname[gene_i]]<-c(SERUAT_HEAD@meta.data[SERUAT_HEAD@meta.data$identity %in% names_of_fca[fca_i],gene_names[[gene_i]]] > current_value_threshold)

  
}
}



SERUAT_HEAD@meta.data$names<-""


#table(SERUAT_HEAD@meta.data$s_elav)


for(i in 1:nrow(SERUAT_HEAD@meta.data)){
  if(SERUAT_HEAD@meta.data$s_obp69a[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"obp69a")

  }
    if(SERUAT_HEAD@meta.data$s_lush[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"lush")

    }
      if(SERUAT_HEAD@meta.data$s_obp28a[i] == TRUE){
    SERUAT_HEAD@meta.data$names[i]<-paste(SERUAT_HEAD@meta.data$names[i],"obp28a")

      }
}

 saveRDS(SERUAT_HEAD,"D:/seq_data/FCA/16_10_antena_obp.rds")



 SERUAT_HEAD<- readRDS("D:/seq_data/FCA/16_10_antena_obp.rds")

 

sub_Seted<-subset(SERUAT_HEAD, names != "")
#sub_Seted<-SERUAT_HEAD




```

```{r}
SERUAT_Antena<-sub_Seted
SERUAT_Antena <- NormalizeData(object = SERUAT_Antena)
SERUAT_Antena <- FindVariableFeatures(object = SERUAT_Antena)
SERUAT_Antena <- ScaleData(object = SERUAT_Antena)
SERUAT_Antena <- RunPCA(object = SERUAT_Antena)
ElbowPlot(SERUAT_Antena)
SERUAT_Antena <- FindNeighbors(object = SERUAT_Antena, dims = 1:20)
SERUAT_Antena <- FindClusters(object = SERUAT_Antena)
SERUAT_Antena <- RunUMAP(object = SERUAT_Antena, dims = 1:20)

sub_Seted<-SERUAT_Antena

Idents(object = sub_Seted) <- sub_Seted@meta.data$Sex


  #  all.genes <- rownames(SERUAT_Antena)

    all_genes<-as.data.frame(rownames(SERUAT_Antena))

#test<-WhichCells(object = sub_Seted, ident.remove = "MaleFemale")

 t<-SplitObject(sub_Seted, split.by = "Sex")
# 
# #object_list <- list(t[["Male"]], t[["Female"]])
# # merged_object <- Merge_Seurat_List(list_seurat = object_list)
# only_m_f<-
# 
# plotname<-"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/antena_only_markers_sex.tiff"
# 
# tiff(file=plotname,units="in",height=13,width=18,res=600)

#Idents(object = sub_Seted) <- sub_Seted@meta.data$names

Idents(object = sub_Seted) <- sub_Seted@meta.data$Sex

#markers <- FindAllMarkers(sub_Seted,only.pos = TRUE,logfc.threshold = 1)

markers_m_f <- FindMarkers(object = sub_Seted, ident.1 ="Female", ident.2 = "Male",only.pos = TRUE)

markers<-subset(markers_m_f,p_val_adj<0.05)

write.csv(markers,"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/antena_female_to_male.csv")


# t<-SplitObject(glu, split.by = "names")
# # label=TRUE
# elav<-DimPlot(object = t[[" elav"]],label.size
# =3.5,pt.size = 1.5,cols ="white")

# 
# DimPlot(object = sub_Seted,label.size
# =3.5,pt.size = 1.5,split.by = "Sex")
# 
# DimPlot(sub_Seted, reduction = 'umap', group.by = 'Sex',raster=FALSE)+guides(color = guide_legend(override.aes = list(size=1), ncol=2) )+theme(legend.title = element_text(size = 5), 
#                legend.text = element_text(size = 7))

#dev.off()
```


```{r}

my_markers<-unique(read.csv("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/antena_gene_marker_pos.csv")$gene)

for(i in 1:length(my_markers)){
  current_gene<-my_markers[i]
  plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/antena_only_markers_sex_",current_gene,".tiff")

tiff(file=plotname,units="in",height=13,width=18,res=600)

FeaturePlot(sub_Seted,features =current_gene,split.by = "Sex")

dev.off()
}





DimPlot(sub_Seted, reduction = 'umap', group.by = 'Sex',raster=FALSE)+guides(color = guide_legend(override.aes = list(size=1), ncol=2) )+theme(legend.title = element_text(size = 5), 
               legend.text = element_text(size = 7))


FeaturePlot(sub_Seted,features ="lncRNA:roX2",split.by = "Sex")


FeaturePlot(sub_Seted,features ="lncRNA:roX1",split.by = "Sex")

```
```{r}

 SERUAT_HEAD<- readRDS("D:/seq_data/FCA/16_10_antena_obp_m_and_f.rds")
 #saveRDS(sub_Seted,"D:/seq_data/FCA/16_10_antena_obp_m_and_f.rds")


    all.genes <- rownames(SERUAT_Antena)


obps_gene<- grep('Obp', all.genes, value=TRUE)

my_markers<-obps_gene

sub_Seted<-subset(SERUAT_HEAD, Sex != "MaleFemale")

SERUAT_HEAD<-sub_Seted
for(i in 1:length(my_markers)){
  current_gene<-"lush"
  #current_gene<-my_markers[i]
  plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/antena_only_markers_m_f_only_",current_gene,".tiff")

tiff(file=plotname,units="in",height=13,width=18,res=600)

print(FeaturePlot(sub_Seted,features =current_gene,split.by = "Sex"))

dev.off()
}

```





```{r}
 SERUAT_HEAD<- readRDS("D:/seq_data/FCA/16_10_antena_obp_m_and_f.rds")
SERUAT_Antena<-SERUAT_HEAD

SERUAT_Antena <- NormalizeData(object = SERUAT_Antena)
SERUAT_Antena <- FindVariableFeatures(object = SERUAT_Antena)
SERUAT_Antena <- ScaleData(object = SERUAT_Antena)
SERUAT_Antena <- RunPCA(object = SERUAT_Antena)
ElbowPlot(SERUAT_Antena)
SERUAT_Antena <- FindNeighbors(object = SERUAT_Antena, dims = 1:20)
SERUAT_Antena <- FindClusters(object = SERUAT_Antena)
SERUAT_Antena <- RunUMAP(object = SERUAT_Antena, dims = 1:20)

saveRDS(SERUAT_Antena, "D:/seq_data/FCA/16_10_antena_obp_m_and_f_reclustered.rds")
```




```{r}


  plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/antena_m_f_sex.tiff")
  
 tiff(file=plotname,units="in",height=11,width=11,res=600)

DimPlot(SERUAT_HEAD, reduction = 'umap', group.by = 'Sex',raster=FALSE)+guides(color = guide_legend(override.aes = list(size=1), ncol=2) )+theme(legend.title = element_text(size = 5), 
               legend.text = element_text(size = 7))

dev.off()



Idents(object = SERUAT_Antena) <- SERUAT_Antena@meta.data$names


DimPlot(SERUAT_Antena)

list_of_gene_names<-names(table(SERUAT_Antena@meta.data$names))


my_cols<- c(DiscretePalette(length(list_of_gene_names) ,palette = "glasbey"))
my_cols[1]<-"#C0C0C0"
names(my_cols)<-list_of_gene_names


  plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/antena_m_f_genes.tiff")
 tiff(file=plotname,units="in",height=11,width=11,res=600)


DimPlot(object = SERUAT_Antena,cols = my_cols)

dev.off()

```
```{r}
 t<-SplitObject(SERUAT_Antena, split.by = "Sex")
male_marker<-table(t[["Male"]]@meta.data$names)
female_marker<-table(t[["Female"]]@meta.data$names)


male_vs_female<-male_marker/female_marker

  plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/antena_m_f_ratio.tiff")
 tiff(file=plotname,units="in",height=15,width=15,res=600)


#test<-as.data.frame.matrix(male_vs_female) 


plot(male_vs_female,xlab = "gene name",ylab = "ratio",main = "ratio of male vs female")

dev.off()

```
```{r}
Idents(object = SERUAT_Antena) <- SERUAT_Antena@meta.data$Sex

markers <- FindAllMarkers(SERUAT_Antena,logfc.threshold = 1)
markers<-subset(markers,p_val_adj<0.05)


Idents(object = SERUAT_Antena) <- SERUAT_Antena@meta.data$names

markers <- FindAllMarkers(SERUAT_Antena,logfc.threshold = 1)
markers<-subset(markers,p_val_adj<0.05)

write.csv(markers,"D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/gene_markers_mf.csv")
# my_markers<-unique(markers$gene)
```

```{r}

#SERUAT_Antena@meta.data$tra<- FetchData(SERUAT_Antena, vars = "tra")


  plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/all_antena_m_f_obp69a.tiff")
 tiff(file=plotname,units="in",height=15,width=15,res=600)

#,split.by = "Sex"
  FeaturePlot(SERUAT_Antena,features ="Obp69a")


dev.off()

```

```{r}
SERUAT_HEAD<- readRDS("D:/seq_data/FCA/seuruat_leg_13_9.rds")


  plotname<-paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/all_leg_obp69a.tiff")
 tiff(file=plotname,units="in",height=15,width=15,res=600)

#,split.by = "Sex"
  FeaturePlot(SERUAT_HEAD,features ="Obp69a")


dev.off()
```

```{r}
library(spatstat.utils)
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)



library(edgeR) # BiocManager::install("edgeR")
library(limma)
library(Seurat)
library(ggplot2)
library(dplyr)
library(ggplot2)
library(Matrix)
library(tidyr)
library(stringr)
library("gridExtra")
library(loomR)



#OK107 <-readRDS("D:/seq_data/FCA/17_7_head_elav_genes.rds")
 
SERUAT_HEAD<- readRDS("D:/seq_data/FCA/16_10_antena_obp_m_and_f.rds")


#SERUAT_HEAD <-readRDS("D:/seq_data/FCA/elav.rds")

# 
# SERUAT_HEAD$sample <- rownames(SERUAT_HEAD@meta.data)
# 
# SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "__", "_")
# 
# SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "-", "_")
# 
# View(SERUAT_HEAD@meta.data)
# SERUAT_HEAD@meta.data <- separate(SERUAT_HEAD@meta.data, col = 'sample', into = c("test",'Barcode','identity', 'Sex'), 
#                                   sep = '_')

new<-SplitObject(SERUAT_HEAD, split.by = "Sex")


all.genes_head<-as.data.frame(rownames(SERUAT_HEAD))

head_FCA_sum<-function(gene_name,y_value,bottom_x_value,top_x_value,FCA,NUMBER_OF_FCA,path_of_photos,to_plot){
  
  #remmber to rename the path to the username of he computer
  plotname<- paste(path_of_photos,"/",NUMBER_OF_FCA,".tiff",sep = "")

  #gene_head<-as.data.frame(get(precnt_name,FCA@meta.data))
  gene_head<-as.data.frame(FCA@meta.data[[gene_name]])
  colnames(gene_head)<-"head"
  
  
  #gene_head_density <- hist(gene_head$head, breaks=seq(0,10,l=1000),plot = FALSE)         # Store output of hist function
  #gene_head_density$density <- gene_head_density$counts /    # Compute density values
  # sum(gene_head_density$counts) * 100
  
  
  gene_sum_head <- hist(gene_head$head, breaks=seq(0,20,l=20000),plot = FALSE)                       # Store histogram info
  gene_sum_head$counts <- revcumsum((gene_sum_head$counts)) 
  
  
  main_title <-paste("cumilative garph in ",NUMBER_OF_FCA,"need to be " ,y_value," cells of ",gene_name)

  new_yval<-y_value + 0.5*(y_value)
  
  
  exp_per_counts<-gene_sum_head[["breaks"]][max(which(gene_sum_head[["counts"]] > y_value))]
  
  if(to_plot == TRUE){
      tiff(file=plotname,units="in",height=13,width=18,res=600)
      t<-plot(gene_sum_head,col=alpha('red',0.5), main=main_title, xlab='% expression',ylab='number of cells',ylim =c(0,new_yval),xlim =rev(c(bottom_x_value, top_x_value)),cex.axis=2.2,cex.lab=1.5, cex.main=2,xaxt = "n")
  abline(h = y_value, col = "darkgreen")
  abline(v =exp_per_counts, col = "blue") 
  
  axis(1, at = rev(seq(bottom_x_value,top_x_value, by =
                         0.01)),
       labels = rev(seq(bottom_x_value,top_x_value, by = 0.01)))
  
  
  dev.off()
  }else{
      return(exp_per_counts)
      dev.off()

  }

}




```

```{r}
# SERUAT_HEAD <-readRDS("D:/seq_data/FCA/seuruat_head_non_norm.rds")
# 
# SERUAT_Antena <-readRDS("D:/seq_data/FCA/seuruat_antena_non_normelize.rds")


SERUAT_HEAD<- readRDS("D:/seq_data/FCA/16_10_antena_obp_m_and_f.rds")


new<-SplitObject(SERUAT_HEAD, split.by = "Sex")

SERUAT_HEAD<-new[["Female"]]
SERUAT_Antena<-new[["Female"]]
all.genes_antena<-as.data.frame(rownames(SERUAT_Antena))
all.genes_head<-as.data.frame(rownames(SERUAT_HEAD))
head_antena_sum<-function(gene_name,y_value,x_value){
  
  precnt_name<-gene_name
  # SERUAT_Antena[[precnt_name]] <- PercentageFeatureSet(SERUAT_Antena,features =gene_name)
  # SERUAT_HEAD[[precnt_name]] <- PercentageFeatureSet(SERUAT_HEAD,features =gene_name)
  View(SERUAT_HEAD@meta.data)
View(SERUAT_Antena@meta.data)
  
  gene_head<-as.data.frame(get(precnt_name,SERUAT_HEAD@meta.data))
  gene_antena<-as.data.frame(get(precnt_name,SERUAT_Antena@meta.data))
  colnames(gene_head)<-"head"
  colnames(gene_antena)<-"antena"
  
  
  
  gene_sum_head <- hist(gene_head$head,breaks=seq(0,10,l=1000))                     # Store histogram info
  gene_sum_head$counts <- revcumsum((gene_sum_head$counts))    # Change histogram counts
  
  gene_sum_antena <-hist(gene_antena$antena,breaks=seq(0,10,l=1000)) 
  gene_sum_antena$counts <- revcumsum((gene_sum_antena$counts))    # Change histogram counts

  
 plotname<- paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/male_female_",gene_name,".tiff")
  
 # plotname<-paste("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/basal_level/","freq",gene_name,"y_lim",y_value,".tiff",sep = "")
  
tiff(file=plotname,units="in",height=15,width=15,res=600)
  main_title <-paste("female (red) vs male (green)",gene_name)

  plot(gene_sum_head,col=alpha('red',0.5),xlim=rev(c(0, x_value)),ylim =c(0,y_value),main=main_title,ylab = "sum of sampels") 
  plot(gene_sum_antena,col=alpha('green',0.5),xlim=rev(c(0, x_value)),ylim =c(0,y_value),add = TRUE)
dev.off()




 plotname<- paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/male_",gene_name,".tiff")
  
 # plotname<-paste("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/basal_level/","freq",gene_name,"y_lim",y_value,".tiff",sep = "")
  
tiff(file=plotname,units="in",height=15,width=15,res=600)
  main_title <-paste("male (green)",gene_name)

  plot(gene_sum_antena,col=alpha('green',0.5),xlim=rev(c(0, x_value)),ylim =c(0,y_value),main=main_title,ylab = "sum of sampels") 
dev.off()

 plotname<- paste0("D:/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/female_",gene_name,".tiff")
  
 # plotname<-paste("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/basal_level/","freq",gene_name,"y_lim",y_value,".tiff",sep = "")
  
tiff(file=plotname,units="in",height=15,width=15,res=600)
  main_title <-paste("female (red)",gene_name)

  plot(gene_sum_head,col=alpha('red',0.5),xlim=rev(c(0, x_value)),ylim =c(0,y_value),main=main_title,ylab = "sum of sampels") 
dev.off()
}

head_antena_sum("lush",8000,8)
```




```{r}
#SERUAT_HEAD<- readRDS("D:/Lital/16_10_antena_obp_m_and_f_reclustered.rds")


 plotname<- paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/obp69a_splited.tiff")
  

  
tiff(file=plotname,units="in",height=20,width=20,res=600)

FeaturePlot(SERUAT_HEAD,features ="Obp69a",split.by = "Sex")


dev.off()



 plotname<- paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/lush_splited.tiff")
  

  
tiff(file=plotname,units="in",height=20,width=20,res=600)

FeaturePlot(SERUAT_HEAD,features ="lush",split.by = "Sex")


dev.off()



 plotname<- paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/obp28a_splited.tiff")
  

  
tiff(file=plotname,units="in",height=20,width=20,res=600)

FeaturePlot(SERUAT_HEAD,features ="Obp28a",split.by = "Sex")


dev.off()
```

```{r}

    all_genes<-as.data.frame(rownames(SERUAT_HEAD))


 plotname<- paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/Rox1_splited.tiff")
  

  
tiff(file=plotname,units="in",height=20,width=20,res=600)

FeaturePlot(SERUAT_HEAD,features ="lncRNA:roX1",split.by = "Sex")


dev.off()


 plotname<- paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/Rox2_splited.tiff")
  

  
tiff(file=plotname,units="in",height=20,width=20,res=600)

FeaturePlot(SERUAT_HEAD,features ="lncRNA:roX2",split.by = "Sex")


dev.off()


 plotname<- paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/Hr38_splited.tiff")
  

  

FeaturePlot(SERUAT_HEAD,features ="Hr38",split.by = "Sex")


dev.off()



 plotname<- paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/sxe2_splited.tiff")
  

  
tiff(file=plotname,units="in",height=20,width=20,res=600)

FeaturePlot(SERUAT_HEAD,features ="sxe2",split.by = "Sex")


dev.off()


 plotname<- paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/dsx_splited.tiff")
  

  
tiff(file=plotname,units="in",height=20,width=20,res=600)

FeaturePlot(SERUAT_HEAD,features ="dsx",split.by = "Sex")


dev.off()


 plotname<- paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/tra_splited.tiff")
  

  
tiff(file=plotname,units="in",height=20,width=20,res=600)

FeaturePlot(SERUAT_HEAD,features ="tra",split.by = "Sex")


dev.off()


 plotname<- paste0("C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/thesis/obp_analysis/only_m_f/Or65a_splited.tiff")
  

  
tiff(file=plotname,units="in",height=20,width=20,res=600)

FeaturePlot(SERUAT_HEAD,features ="Or65a",split.by = "Sex")


dev.off()

```

