---
title: "R Notebook"
output: html_notebook
---



```{r}
test<-c("a","b")
ttest<-c("c","d")
a<-NULL
a<-rbind(a,test)
```


```{r}

library(spatstat.utils)
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)



library(edgeR) # BiocManager::install("edgeR")
library(limma)
library(Seurat)
library(ggplot2)
library(dplyr)
library(ggplot2)
library(Matrix)
library(tidyr)
library(stringr)
library("gridExtra")
library(loomR)



SERUAT_HEAD <-readRDS("D:/seq_data/FCA/seuruat_head5_12.rds")
 
SERUAT_HEAD$sample <- rownames(SERUAT_HEAD@meta.data)

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "__", "_")

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "-", "_")

View(SERUAT_HEAD@meta.data)
SERUAT_HEAD@meta.data <- separate(SERUAT_HEAD@meta.data, col = 'sample', into = c("test",'Barcode','identity', 'Sex'), 
                                  sep = '_')

new<-SplitObject(SERUAT_HEAD, split.by = "identity")


all.genes_head<-as.data.frame(rownames(SERUAT_HEAD))

head_FCA_sum<-function(gene_name,y_value,bottom_x_value,top_x_value,FCA,NUMBER_OF_FCA,path_of_photos){
  
  #remmber to rename the path to the username of he computer
  plotname<- paste(path_of_photos,"/",NUMBER_OF_FCA,".tiff",sep = "")
  #plotname<-paste("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/27.2.23/",gene_name,"/",NUMBER_OF_FCA,".tiff",sep = "")
  precnt_name<-paste("percent.",gene_name,sep="")
  FCA[[precnt_name]] <- PercentageFeatureSet(FCA,features =gene_name)
  
  gene_head<-as.data.frame(get(precnt_name,FCA@meta.data))
  colnames(gene_head)<-"head"
  
  
  #gene_head_density <- hist(gene_head$head, breaks=seq(0,10,l=1000),plot = FALSE)         # Store output of hist function
  #gene_head_density$density <- gene_head_density$counts /    # Compute density values
  # sum(gene_head_density$counts) * 100
  
  
  gene_sum_head <- hist(gene_head$head, breaks=seq(0,10,l=10000),plot = FALSE)                       # Store histogram info
  gene_sum_head$counts <- revcumsum((gene_sum_head$counts)) 
  
  
  main_title <-paste("cumilative garph in ",NUMBER_OF_FCA,"need to be " ,y_value," cells of ",gene_name)
  tiff(file=plotname,units="in",height=13,width=18,res=600)
  new_yval<-y_value + 0.5*(y_value)
  
  
  exp_per_counts<-gene_sum_head[["breaks"]][max(which(gene_sum_head[["counts"]] > y_value))]
  
  
  t<-plot(gene_sum_head,col=alpha('red',0.5), main=main_title, xlab='% expression',ylab='number of cells',ylim =c(0,new_yval),xlim =rev(c(bottom_x_value, top_x_value)),cex.axis=2.2,cex.lab=1.5, cex.main=2,xaxt = "n")
  abline(h = y_value, col = "darkgreen")
  abline(v =exp_per_counts, col = "blue") 
  
  axis(1, at = rev(seq(bottom_x_value,top_x_value, by = 0.01)),
       labels = rev(seq(bottom_x_value,top_x_value, by = 0.01)))
  
  
  dev.off()
  return(exp_per_counts)
}
```


```{r}




#max(which(gene_sum_head[["counts"]] > 4))

number_of_fca<-c("1","4","5","6","7","8","9","10","11","12","13","14","15")
names_of_fca<-paste("FCA",number_of_fca,sep="")

path_of_photos<-"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/27.2.23/"
gene<-"ple"
expceted_cell_num<-515


full_path_of_gene<-paste(path_of_photos,gene,"/",sep = "")

  to_csv<-NULL
if(dir.exists(full_path_of_gene)){
  for(i in 1:length(new)){
    y_Vale_max_origin<-round((expceted_cell_num*ncol(new[[i]]))/100000) # to find how many sample suppose to be
    #y_Vale_max<-y_Vale_max_origin + 0.5 *(y_Vale_max_origin)
   expression_level<- head_FCA_sum(gene,y_Vale_max_origin,0,0.5,new[[i]],names_of_fca[i],full_path_of_gene)
      temp<-c(expression_level,names_of_fca[i])
    to_csv<-rbind(to_csv,temp)
  }
}else{
  dir.create(full_path_of_gene)
  for(i in 1:length(new)){
    y_Vale_max_origin<-round((expceted_cell_num*ncol(new[[i]]))/100000) # to find how many sample suppose to be
    #y_Vale_max<-y_Vale_max_origin + 0.5 *(y_Vale_max_origin)
   expression_level<- head_FCA_sum(gene,y_Vale_max_origin,0,0.3,new[[i]],names_of_fca[i],full_path_of_gene)
   
    temp<-c(expression_level,names_of_fca[i])
    to_csv<-rbind(to_csv,temp)
  }
}

of_all<-head_FCA_sum(gene,expceted_cell_num,0,0.5,SERUAT_HEAD,"ALL",full_path_of_gene)

temp<-c(of_all,"ALL")
to_csv<-rbind(to_csv,temp)
  
to_csv<-as.data.frame(to_csv)
full_path_csv<-paste(full_path_of_gene,gene,".csv",sep = "")
write.csv(to_csv, full_path_csv, row.names=FALSE)



```

```{r}

path_of_photos<-"C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/27.2.23/"

gene<-"ple"

full_path_of_gene<-paste(path_of_photos,gene,"/",sep = "")

#y_Vale_max_origin<-round((expceted_cell_num*ncol(SERUAT_HEAD))/100000) # to find how many sample suppose to be

y_Vale_max_origin<-515

of_all<-head_FCA_sum(gene,y_Vale_max_origin,0,0.5,SERUAT_HEAD,"ALL",full_path_of_gene)


```





```{r}

head_FCA_sum_for_visual<-function(gene_name,FCA){
  
  #remmber to rename the path to the username of he computer
  #plotname<-paste("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/27.2.23/",gene_name,"/",NUMBER_OF_FCA,".tiff",sep = "")
  precnt_name<-paste("percent.",gene_name,sep="")
  FCA[[precnt_name]] <- PercentageFeatureSet(FCA,features =gene_name)
  
  gene_head<-as.data.frame(get(precnt_name,FCA@meta.data))
  colnames(gene_head)<-"head"
  
  
  #gene_head_density <- hist(gene_head$head, breaks=seq(0,10,l=1000),plot = FALSE)         # Store output of hist function
  #gene_head_density$density <- gene_head_density$counts /    # Compute density values
  # sum(gene_head_density$counts) * 100
  
  
  gene_sum_head <- hist(gene_head$head, breaks=seq(0,10,l=10000),plot = FALSE)                       # Store histogram info
  gene_sum_head$counts <- revcumsum((gene_sum_head$counts)) 
  
  return(gene_sum_head)
}

```


```{r}

library(spatstat.utils)
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)

expceted_cell_num<-c(300,515,265,989,1454,40,1000,1000,100,6)

top_x_value<-c(0.5,0.5,0.5,0.5,0.8,0.5,0.5,0.5,0.5,0.5)

# list_of_freq<-c(20)
# list_of_xlimit<-c(2)
list_of_gene<-c("Crz","ple","Tdc2","Trh","fru","NPF","Tbh","Adar","NPFR","Dh44")


#list_of_gene<-c("Crz")
#expceted_cell_num<-c(300)

path_of_photos<-"C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/27.2.23/"




number_of_fca<-c("1","4","5","6","7","8","9","10","11","12","13","14","15")
names_of_fca<-paste("FCA",number_of_fca,sep="")


for(i in 1:length(list_of_gene)){
  
  plotname<-paste(path_of_photos,"_gene_name_",list_of_gene[i],".tiff",sep = "")
  tiff(file=plotname,units="in",height=15,width=20,res=600)
  par(mfrow = c(5, 3),mar = c(2.1, 3, 9, 3),xaxs = "i",yaxs = "i",cex.axis=1.1,cex.lab=1.1)
  for(j in 1:length(new)){
  y_Vale_max_origin<-round((expceted_cell_num[i]*ncol(new[[j]]))/100000) # to find how many sample suppose to be

  current_FCA<-new[[j]]
 # main_title <-paste(current_gene)
  current_FCA_hist<-head_FCA_sum_for_visual(list_of_gene[i],current_FCA)
  

  
   # main_title <-paste("cumilative garph in ",NUMBER_OF_FCA,"need to be " ,y_value," cells of ",gene_name)
  new_yval<-y_Vale_max_origin + 0.5*(y_Vale_max_origin)
  
  
  exp_per_counts<-current_FCA_hist[["breaks"]][max(which(current_FCA_hist[["counts"]] > y_Vale_max_origin))]
  
  plot(current_FCA_hist,col=alpha('red',0.5), main=paste(names_of_fca[j],"expected cell is ",y_Vale_max_origin), xlab='% expression',ylab='number of cells',ylim =c(0,new_yval),xlim =rev(c(0, top_x_value[i])),cex.axis=2.2,cex.lab=1.5, cex.main=2,xaxt = "n")
  abline(h = y_Vale_max_origin, col = "darkgreen")
  abline(v =exp_per_counts, col = "blue") 
  axis(1, at = rev(seq(0,top_x_value[i], by = 0.01)),
       labels = rev(seq(0,top_x_value[i], by = 0.01)))
  
   title_<-paste(list_of_gene[i])
  #dev.off()
  mtext(title_, side = 3, line =-3, outer = TRUE ,cex=2)
}
  dev.off()
}



```







```{r}
head_FCA_sum<-function(gene_name,y_value,bottom_x_value,top_x_value,FCA,NUMBER_OF_FCA,path_of_photos){
  
  #remmber to rename the path to the username of he computer
  plotname<- paste(path_of_photos,"/",NUMBER_OF_FCA,".tiff",sep = "")
  #plotname<-paste("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/27.2.23/",gene_name,"/",NUMBER_OF_FCA,".tiff",sep = "")
  precnt_name<-paste("percent.",gene_name,sep="")
  FCA[[precnt_name]] <- PercentageFeatureSet(FCA,features =gene_name)
  
  gene_head<-as.data.frame(get(precnt_name,FCA@meta.data))
  colnames(gene_head)<-"head"
  
  
  #gene_head_density <- hist(gene_head$head, breaks=seq(0,10,l=1000),plot = FALSE)         # Store output of hist function
  #gene_head_density$density <- gene_head_density$counts /    # Compute density values
  # sum(gene_head_density$counts) * 100
  
  gene_head %>% 
    mutate(bin_num=cut(head,c(seq(-1,1,0.001)))) %>%
    tidyr::separate(bin_num,c("low","high"),",") %>%
    mutate(bin = gsub("]","",high)) %>%
    select(head, bin) %>% 
    group_by(bin) %>% summarise(number_samples_bin=n()) %>% ungroup() %>% 
    mutate(bin = as.numeric(bin))-> df_test

  
  df_test %>% 
    filter(bin >0) %>% 
    ggplot(aes(x = bin, y= number_samples_bin ))  +geom_point() + geom_line() +theme_bw()
  
  
```

```{r}
  
  (max(gene_head$head) -min(gene_head$head))/10000
 test<- as.data.frame(ntile(gene_head$head, 10000))
  
  
  gene_sum_head <- hist(gene_head$head, breaks=seq(0,10,l=10000),plot = FALSE)                       # Store histogram info
  gene_sum_head$counts <- revcumsum((gene_sum_head$counts)) 
  
  
  main_title <-paste("cumilative garph in ",NUMBER_OF_FCA,"need to be " ,y_value," cells of ",gene_name)
  tiff(file=plotname,units="in",height=13,width=18,res=600)
  new_yval<-y_value + 0.5*(y_value)
  
  
  exp_per_counts<-gene_sum_head[["breaks"]][max(which(gene_sum_head[["counts"]] > y_value))]
  
  t<-plot(gene_sum_head,col=alpha('red',0.5), main=main_title, xlab='% expression',ylab='number of cells',ylim =c(0,new_yval),xlim =rev(c(bottom_x_value, top_x_value)),cex.axis=2.2,cex.lab=1.5, cex.main=2,xaxt = "n")
  abline(h = y_value, col = "darkgreen")
  abline(v =exp_per_counts, col = "blue") 
  
  axis(1, at = rev(seq(bottom_x_value,top_x_value, by = 0.01)),
       labels = rev(seq(bottom_x_value,top_x_value, by = 0.01)))
  
  
  dev.off()
  
}

```

