--- 
title: "threshold"
output: html_document
date: "2023-03-30"
---


```{r}
library(Seurat)
SERUAT_HEAD <-readRDS("D:/seq_data/FCA/seuruat_head12_3.rds")


library(ggpubr)
library(ggplot2)
#removed the 0 from the dataset 

test<-subset(SERUAT_HEAD,subset = percent.fru > 0)


# the number of reads vs the precentage seprate by the threshold

ggplot(data=test@meta.data,aes(x = (nCount_RNA * percent.fru)/100 , 
                               y =percent.fru,
                               color=ifelse(percent.fru >=0.57,T,F)
                             # color=ifelse(percent.fru >=0.3,T,F)

                               ))+
  geom_point(size =2, alpha =0.3)+theme_bw() +
  # facet_grid(~(nCount_RNA * percent.fru)/100 >50)+
  geom_smooth() + stat_cor()



# the reads vs number of genes per cell ,we see that cells that pass the threshold don't have a lot of genes that expressed
ggplot(data=test@meta.data,aes(x = (nCount_RNA * percent.fru)/100 , 
                               y =nFeature_RNA ,
                               color=ifelse(percent.fru >=0.57,T,F)
                             # color=ifelse(percent.fru >=0.3,T,F)

                               ))+
  geom_point(size =2, alpha =0.3)+theme_bw() +
  # facet_grid(~(nCount_RNA * percent.fru)/100 >50)+
  geom_smooth() + stat_cor()






# number of counts vs the % of cells 

ggplot(data=test@meta.data,aes(x = percent.fru , 
                               y =nFeature_RNA,
                               color=ifelse(percent.fru >=0.57,T,F)
                             # color=ifelse(percent.fru >=0.3,T,F)

                               ))+
  geom_point(size =2, alpha =0.3)+theme_bw() +
  # facet_grid(~(nCount_RNA * percent.fru)/100 >50)+
  geom_smooth() + stat_cor()
```

caret', 'tclust', 'ranger', 'dtw', 'SDMTools', 'Hmisc', 'metap




##NPF 

```{r}

test<-subset(SERUAT_HEAD,subset = percent.NPF > 0)




ggplot(data=test@meta.data,aes(x = (nCount_RNA * percent.NPF)/100 , 
                               y =percent.NPF,
                               color=ifelse(percent.NPF >=0.3,T,F)
                             # color=ifelse(percent.fru >=0.3,T,F)

                               ))+
  geom_point(size =2, alpha =0.3)+theme_bw() +
  # facet_grid(~(nCount_RNA * percent.fru)/100 >50)+
   stat_cor()

ggplot(data=test@meta.data,aes(x = (nCount_RNA * percent.NPF)/100 , 
                               y =nFeature_RNA ,
                               color=ifelse(percent.NPF >=0.3,T,F)
                             # color=ifelse(percent.fru >=0.3,T,F)

                               ))+
  geom_point(size =2, alpha =0.3)+theme_bw() +
  # facet_grid(~(nCount_RNA * percent.fru)/100 >50)+
  stat_cor()



ggplot(data=test@meta.data,aes(x = percent.NPF , 
                               y =nFeature_RNA ,
                               color=ifelse(percent.NPF >=0.3,T,F)
                             # color=ifelse(percent.fru >=0.3,T,F)

                               ))+
  geom_point(size =2, alpha =0.3)+theme_bw() +
  # facet_grid(~(nCount_RNA * percent.fru)/100 >50)+
  stat_cor()

```




# histogram of number of genes per cell

```{r}
 hist(SERUAT_HEAD@meta.data$nFeature_RNA,breaks = 1000,xlim = c(0,2000))
```



```{r}

test <-readRDS("D:/seq_data/FCA/seuruat_head5_12.rds")
 hist(test@meta.data$nFeature_RNA,breaks = 1000,xlim = c(0,2000))

```
```{r}
library(Seurat)
SERUAT_HEAD <-readRDS("D:/seq_data/FCA/seuruat_head12_3.rds")


library(ggpubr)
library(ggplot2)
#removed the 0 from the dataset 

test<-subset(SERUAT_HEAD,subset = percent.fru > 0)


```

```{r}


 #hist(test@meta.data$nFeature_RNA,breaks = 1000,xlim = c(0,2000))


library(edgeR) # BiocManager::install("edgeR")
library(limma)
library(Seurat)
library(ggplot2)
library(dplyr)
library(ggplot2)
library(Matrix)
library(tidyr)
library(stringr)
library("gridExtra")
library(loomR)

SERUAT_HEAD$sample <- rownames(SERUAT_HEAD@meta.data)

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "__", "_")

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "-", "_")

View(SERUAT_HEAD@meta.data)
SERUAT_HEAD@meta.data <- separate(SERUAT_HEAD@meta.data, col = 'sample', into = c("test",'Barcode','identity', 'Sex'), 
                                    sep = '_')

new<-SplitObject(SERUAT_HEAD, split.by = "identity")


#FCA1<-new$FCA1

FCA1<-new$FCA1
FCA4<-new$FCA4
FCA5<-new$FCA5
FCA6<-new$FCA6
FCA7<-new$FCA7
FCA8<-new$FCA8
FCA9<-new$FCA9
FCA10<-new$FCA10
FCA11<-new$FCA11
FCA12<-new$FCA12
FCA13<-new$FCA13
FCA14<-new$FCA14
FCA15<-new$FCA15



hist(FCA1@meta.data$nFeature_RNA,breaks = 500, col='red')
hist(FCA4@meta.data$nFeature_RNA,breaks = 500, col='green',add = TRUE)
hist(FCA5@meta.data$nFeature_RNA,breaks = 500, col='blue',add = TRUE,alpha())


"https://www.geeksforgeeks.org/how-to-plot-multiple-histograms-in-r/"
"https://www.hdsu.org/irtg2021/day2/01.html"
```








```{r}
library(spatstat.utils)
library(loomR)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)



gene_name<-"all"

SERUAT_HEAD$sample <- rownames(SERUAT_HEAD@meta.data)

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "__", "_")

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "-", "_")

#View(SERUAT_HEAD@meta.data)
SERUAT_HEAD@meta.data <- separate(SERUAT_HEAD@meta.data, col = 'sample', into = c("test",'Barcode','identity', 'Sex'), 
                                    sep = '_')

################################################
#test<-subset(SERUAT_HEAD,subset = percent.ple > 0)


new<-SplitObject(SERUAT_HEAD, split.by = "identity")




plotname<-paste("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/9.4.23/",gene_name,"_all_hist_reads.tiff",sep = "")
tiff(file=plotname,units="in",height=11,width=11,res=600)
par(mfrow = c(3, 5),mar = c(2.1, 2.1, 6, 2.1),xaxs = "i",yaxs = "i",cex.axis=1.1,cex.lab=1.1)
for(i in 1:length(new)){



  hist(new[[i]]@meta.data$nCount_RNA,breaks = 1000, col='red',main =paste0("FCA",i,sep=""))

 title_<-paste("hist reads per fca ",gene_name,sep = "")
  #dev.off()
  mtext(title_, side = 3, line =-2, outer = TRUE ,cex=1)
}
dev.off()



```


```{r}
SERUAT_HEAD <-readRDS("D:/seq_data/FCA/seuruat_head12_3.rds")

test<-subset(SERUAT_HEAD,subset = percent.Tbh > 0)
glu<-test
glu <- NormalizeData(object = glu)
glu <- FindVariableFeatures(object = glu)
glu <- ScaleData(object = glu)
glu <- RunPCA(object = glu)
ElbowPlot(SERUAT_HEAD)

glu <- FindNeighbors(object = glu, dims = 1:20)
glu <- FindClusters(object = glu)
glu <- RunUMAP(object = glu, dims = 1:20)


Idents(object = glu) <- glu@meta.data$Tbh


plotname<-paste("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/9.4.23/thresh_Tbh_.tiff",sep = "")
tiff(file=plotname,units="in",height=11,width=11,res=600)

DimPlot(object = glu,label.size
=3.5,pt.size = 1.5)

dev.off()

```




```{r}




Idents(object = glu) <- glu@meta.data$percent.fru

DimPlot(object = glu,label=TRUE,label.size
=3.5,pt.size = 1.5)

```




```{r}

test<-subset(SERUAT_HEAD,subset = percent.NPF > 0)


  plotname<-paste("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/9.4.23/gene_vs_reads_NPF_test_.tiff",sep = "")


tiff(file=plotname,units="in",height=11,width=11,res=600)

ggplot(data=test@meta.data,aes(x = nCount_RNA, 
                               y =nFeature_RNA,
                              # color=ifelse(percent.fru >=0.57,T,F)
                             # color=ifelse(percent.fru >=0.3,T,F)

                               ))+
  geom_point(size =2, alpha =0.3)+theme_bw() +
  # facet_grid(~(nCount_RNA * percent.fru)/100 >50)+
  geom_smooth() + stat_cor(method = "spearman")


dev.off()

```





```{r}


library(spatstat.utils)

library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)



gene_name<-"all"

SERUAT_HEAD$sample <- rownames(SERUAT_HEAD@meta.data)

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "__", "_")

SERUAT_HEAD$sample<-str_replace(SERUAT_HEAD$sample, "-", "_")

#View(SERUAT_HEAD@meta.data)
SERUAT_HEAD@meta.data <- separate(SERUAT_HEAD@meta.data, col = 'sample', into = c("test",'Barcode','identity', 'Sex'), 
                                    sep = '_')

################################################
#test<-subset(SERUAT_HEAD,subset = percent.ple > 0)


new<-SplitObject(SERUAT_HEAD, split.by = "identity")




#test<-subset(SERUAT_HEAD,subset = percent.ple > 0)


for(i in 1:length(new)){
fca_number=i
plotname<-paste("C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/9.4.23/","fca number_",fca_number,"_.tiff",sep = "")
tiff(file=plotname,units="in",height=11,width=11,res=600)
print(ggplot(data=new[[fca_number]]@meta.data,aes(x = nCount_RNA, 
                               y =nFeature_RNA,
                              # color=ifelse(percent.fru >=0.57,T,F)
                             # color=ifelse(percent.fru >=0.3,T,F)

                               ))+
  geom_point(size =2, alpha =0.3)+theme_bw() +
  # facet_grid(~(nCount_RNA * percent.fru)/100 >50)
    geom_smooth()+stat_cor(method = "spearman")+ggtitle(paste0("gene vs reads in FCA number ",i,sep="")))


dev.off()
}







```

